### ISSUE TITLE
Born To Fight

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1025]
![borntofi](https://user-images.githubusercontent.com/51386955/114284739-f6de8380-9a49-11eb-8aa4-988d40d8caa9.png)

Clearly a Operation Wolf rip off with game assets stolen from Taito's game but it's not all bad, just need someone to 
test it in this core, i've given it a good go using my Xbox MAME72 test core and it seems to be fine.

I had to cut a few corners with this one it's using the NEC compatible I86 CPU rather than simply using the NEC V20 
to save me updating the whole NEC CPU core which would be required for the game to boot, plus as the sound doesn't
seem to work if using the I88 i've switched it to use a I86 instead.

As well as the above i've left out some input tagging code from the VIDEO_UPDATE call as it's not compatible with
this core, as a result you wont be able to use Lightguns with this game but luckly it has a joystick mode which im
defaulting to via the dips, it can be played with Trackballs i've never tried that myself but according to the driver
notes they dont work too well.

Anyway please give it a whirl and lemmie know sometime if everything's good.

**Comment by mahoneyt944** [comment]
It's seems to play ok. 
![borntofi-210411-094941](https://user-images.githubusercontent.com/49591133/114306900-66d12600-9aab-11eb-9dc4-47d262fead0e.png)

**Comment by mahoneyt944** [comment]
Maybe a pinch loud, would have to compare to opwolf

**Comment by arcadez2003** [comment]
Thanks for trying it out it's good to see it's working in this core, as for the sound levels yeah i agree 
they're a bit on the loud side, same as in current MAME the MSM is set to 100 we could always just 
half that down to 50 to make it less severe on the ole ears

**Comment by mahoneyt944** [comment]
I knocked it down to 50, the game plays well. Sounds good. The mame menu mapping is a bit confusing though with all the extra inputs. Did this game ever have a official trackball? I wouldn't think so?

**Comment by mahoneyt944** [comment]
I commited some cleanups /  labels. It seems like these extra inputs maybe left over junk when they ripped from the original game or something.

I was able to get the light gun to move with buttons 1 and 2 so something's definitely off with those ports.

**Comment by arcadez2003** [comment]
Thanks

> 
> 
> I knocked it down to 50, the game plays well. Sounds good. The mame menu mapping is a bit confusing though with all the extra inputs. Did this game ever have a official trackball?

Yeah it's unusual for an arcade game to have as many input types as in this case Light Guns Trackballs and Joysticks,
maybe they wanted it to appeal to as many arcade operators as possible seeing as this game would certainly have
dropped into almost all cab types.

Anyway thanks for looking at the inputs i think the game will play fine and well using the joystick mode, i've not tried
the trackballs to know if they work or not.?? the driver says they dont function too well, as for the Lightguns they should
work but we're missing the on screen crosshare due to leaving out the following code with port tagging we cannot
support....

VIDEO_UPDATE( fantland )
{
	int portx, porty;

	fillbitmap(bitmap,Machine->pens[0],cliprect);
	fantland_draw_sprites(bitmap,cliprect);

	// Draw the crosshairs for lightgun games

	if (	(portx = port_tag_to_index("Controls")) > 0	&&
			((readinputport(portx) & 3) != 3)			)
		return;

	if (	(portx = port_tag_to_index("P1 Lightgun X")) > 0	&&
			(porty = port_tag_to_index("P1 Lightgun Y")) > 0	)
	{
		draw_crosshair(bitmap,
			readinputport(portx) * 2 - 0x0e,
			readinputport(porty) * 2 - 0xf8,
			cliprect,0);
	}

	if (	(portx = port_tag_to_index("P2 Lightgun X")) > 0	&&
			(porty = port_tag_to_index("P2 Lightgun Y")) > 0	)
	{
		draw_crosshair(bitmap,
			readinputport(portx) * 2 - 0x0e,
			readinputport(porty) * 2 - 0xf8,
			cliprect,1);
	}
}

It might be possible to mod the above to work in this core but as the game is playing fine with the Joysticks 
is it really worth the hastle.?? BTW there is another game in the driver Wheels Runner a knock off Super Sprint
type deal which we cant support for the same reasons more or less as it has no Joystick mode to fall back on.

![wheelrun](https://user-images.githubusercontent.com/51386955/114400145-94949880-9b99-11eb-8dac-a8c2e68822fd.png)

**Comment by mahoneyt944** [comment]
I imagine we would just use something like this maybe:

```
// Draw the crosshairs for lightgun games

if( (readinputport(7) & 3) != 3)	
	return;

if ( (readinputport(8) > 0) && (readinputport(9) > 0) )
{
	draw_crosshair(bitmap,
		readinputport(9) * 2 - 0x0e,
		readinputport(8) * 2 - 0xf8,
		cliprect,0);
}

if ( (readinputport(10) > 0) && (readinputport(11) > 0) )
{
	draw_crosshair(bitmap,
		readinputport(11) * 2 - 0x0e,
		readinputport(10) * 2 - 0xf8,
		cliprect,1);
}
```

**Comment by arcadez2003** [comment]
That looks very close maybe spot on even i'll test it now

**Comment by mahoneyt944** [comment]
I made a new branch "borntofi" with the changes. Tested and works. Though this is hard coded for borntofi. We'd have to add variables set by game name to hot swap the port numbers.

**Comment by arcadez2003** [comment]
Good job the code works a treat, listen we have the video code for Wheels Runner already if i send you an updated
fantland.c with that game hooked up would you mind taking a look to see if we can roll back the inputs for that one
to get it contralable in this core.??

**Comment by mahoneyt944** [comment]
Sure. I'll check it out when I wake up later 😴

**Comment by arcadez2003** [comment]
Ha Ha yeah you might need another lie down when you see what where up against :) 

Anyway it'll all depend of if the game wants to play with the I86 CPU vs the V20 if it doesn't
then we're dead in the water i'll start porting across then

**Comment by arcadez2003** [comment]
@mahoneyt944 Here ya go i've added support for Wheels Runner to fantland.c it seems to work fine with the I86 CPU
if you fancy having a look at the broken inputs for turning the car left or right sometime here is the driver.....

[stuff.zip](https://github.com/libretro/mame2003-plus-libretro/files/6299914/stuff.zip)

**Comment by mahoneyt944** [comment]
Ok I'll look at. Also, I updated the lightgun ports to center them with full screen range and moved borntofi to it's own video update since the readinputports are specific to that game. Looks perfect to me. Pull the new changes from master (driver and vidhrdw) if you want them for your port. Otherwise I'll see if I can get the inputs going on this next one.

**Comment by mahoneyt944** [comment]
Ok I made some progress, though it's still turning to the right. Ports are now hooked together. I'm using on screen logging to verify what they are doing for player 1 (index 0). It seems to be really close. https://github.com/libretro/mame2003-plus-libretro/compare/wheelrun-wip

**Comment by arcadez2003** [comment]
Good to hear you've made some good progress you may well be close to the winning flag :)

I came up with this madness earlier but no dice

static int wheelrun_wheel_r(int param)
{
	//int player = (FPTR)param;
	int player1 = readinputport(0);
	int player2 = readinputport(1);

	if(player1);
	{
    int delta = readinputport(4);
	delta = (delta & 0x7f) - (delta & 0x80) + 4;

	if		(delta > 7)	delta = 7;
	else if	(delta < 1)	delta = 1;

//	if (player == 0)	popmessage("%x",delta);
	return delta;
	}

	if(player2);
	{
    int delta = readinputport(4);
	delta = (delta & 0x7f) - (delta & 0x80) + 4;
	

	if		(delta > 7)	delta = 7;
	else if	(delta < 1)	delta = 1;

//	if (player == 0)	popmessage("%x",delta);
	return delta;
	}
}

static READ_HANDLER( wheelrun_dial_0_r )
{
	return wheelrun_wheel_r(0);
}

static READ_HANDLER( wheelrun_dial_1_r )
{
	return wheelrun_wheel_r(1);
}


static DRIVER_INIT( wheelrun )
{
    install_port_read_handler(0,  0x70, 0x70, wheelrun_dial_0_r ); // IN0.??
    install_port_read_handler(0,  0x70, 0x70, wheelrun_dial_1_r ); // IN1.??
}

**Comment by arcadez2003** [comment]
This was the closest i ever got i ripped this from another driver and piped it through player1 ports only

#define WHEELRUN_WHEEL_R( _n_ ) \
static READ8_HANDLER( wheelrun_wheel_##_n_##_r ) \
{ \
   int player = (FPTR)param;\
   int delta = readinputportbytag(player ? "WHEEL1" : "WHEEL0");\
   delta = (delta & 0x7f) - (delta & 0x80) + 4; \
   if      (delta > 7)   delta = 7;\
   else if   (delta < 1)   delta = 1;\
   return delta;\
}\

WHEELRUN_WHEEL_R( 0 )
WHEELRUN_WHEEL_R( 1 )

	PORT_BITX( 0x70, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT  | IPF_PLAYER1, "wheelrun_wheel_r, 0", IP_KEY_DEFAULT, IP_JOY_DEFAULT )

	PORT_BITX( 0x70, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT  | IPF_PLAYER1, "wheelrun_wheel_r, 1", IP_KEY_DEFAULT, IP_JOY_DEFAULT )

	PORT_START_TAG("WHEEL0")
	PORT_ANALOG( 0xff, 0, IPT_DIAL | IPF_CENTER | IPF_REVERSE | IPF_PLAYER1, 25, 10, 0, 0 )
	
	PORT_START_TAG("WHEEL1")
	PORT_ANALOG( 0xff, 0, IPT_DIAL | IPF_CENTER | IPF_REVERSE | IPF_PLAYER1, 25, 10, 0, 0 )


You could control the car turn it left and right etc etc as a single player only game if not for it constantly turning still

**Comment by mahoneyt944** [comment]
I got it, check #1031 for the solution. It appears the high bits control the steering. there maybe a way to make it more precise when using a real analog stick but haven't looked into it. You also have a dip switch for sensitivity that works well.

**Comment by arcadez2003** [comment]
Well done i had a feeling you'd get it and im not often wrong in that regard :)

**Comment by mahoneyt944** [comment]
Just use #1031 I had to revert the other commit after. And thanks, it was more difficult than I thought it would be. Trial and error prevails.

**Comment by mahoneyt944** [comment]
And actually getting to play and win a race. Ha
![wheelrun-210414-092625](https://user-images.githubusercontent.com/49591133/114719041-a0e93480-9d04-11eb-91ce-003f050d7d45.png)

**Comment by arcadez2003** [comment]
Aye your the first person in the whole wide world to do so using this core ;)

**Comment by mahoneyt944** [comment]
fixed the slideout now. Plays perfect to me. Any chance of hooking up the few missing sounds? I believe missing sounds are startling light, coin inserted, picking up items, maybe some others idk? I tested against fbneo for comparison

**Comment by mahoneyt944** [comment]
Current mame has all the sounds, 2010 still missing like ours.

**Comment by arcadez2003** [comment]
Sure i'll take a look the code seems simple enough or was that famous last words :)

https://github.com/mamedev/mame/commit/eaa489c55dd31f365ed9d6c7b4036d835bdae803#diff-c0aff156133b51cbf8c53d5e67cd5aa99434f9b8f872ed91fe781b7c3cf2cf75

**Comment by arcadez2003** [comment]
@mahoneyt944 What'ya think sounding ok.??

https://github.com/libretro/mame2003-plus-libretro/commit/9974d5e16170bbef7a83cb9b2397dbcd03c15e88

**Comment by mahoneyt944** [comment]
Perfect :) nice work.

**Comment by mahoneyt944** [comment]
As commented in that commit you linked, the steering wheel setup is rather odd in wheelrun. I spent a long time manipulating the high bits and have a general understanding of how it works. This also is sight into how custom ports are working in newer mame but that's a separate thing.

From what I can tell, input port 0 (player1) returns all the bits for that player, the low bits being the coin and gas/start button. The steering wheel would have detected it's position and added these as a high bit value with the low bits. The high bits being 128 - right, 255 left.

Without manipulating the high bits, a value of 143 was being returned. To the machine this is interpreted as hard right with no low bits pressed.

The low bits are pretty straight forward. You press and it subtracts the bit value 1 or 2 .. or 3 for both.

The high bits are a bit more complex, as I mentioned 128 is right and 255 is left. However all values leading to the centering values (192 - 207) turn the vehicle at the same speed. So you might wonder then... why would it need such a range? The range is designed to determine the vehicle slideout. This is when you are traveling at speed and bump left or right. Depending on how far you turn the wheel determines how much the vehicle slides before returning to the intended direction.

What I've done, is use the delta function to determine if our dial (port 4) is left, right, or center. Then if it's left, I return the first value from center that turns the vehicle left without activating the low bits, 211. Likewise for right, this would be 191. Center 199.

This allows us to turn left right and center with minimal slideout.

The high bit steering values are represented by every 4th value. The values in-between represent the direction with a low bit button press So:

Full range 255 to 128

223 - left
222 - left + coin
221 - left + gas
220 - left + coin + gas
219 - left
~
215 - left
~
211 - left
~
207 - center
~
203 - center
~
199 - center
~
195 - center
~
191 - right
~
187 - right
~
183 - right
~
179 - right

As the code is now, the game plays great but will not work with a dial because when the dial stops it returns 0 - center.  We would have to track the dials movements and increment the high bit value by 4 within it's range and continue to return that value until the dial moves again. Good for dial, bad for analog / dpad.

Probably better the way it is now since it accommodates more controller options. Maybe a toggle hack could be made but I'm not diving into that right now.

**Comment by mahoneyt944** [comment]
I also suspect the original steering wheel to actually be a large potentiometer, which polls the contacts and determines what value to add to the low bits when returning. That would make the most sense since the wheel will always have an exact value to return based on position.

I say this because my first thought at creating a hack dip option for dial / joystick would be it's starting value when the games fires up. Logically I'd assume centered, but what if I started the game up with the wheel to the left? The hack would assume this position as center when it's not. On a "spinner" dial, no issue but on a fixed steering wheel (spring to center without 360 rotation) it would mess things up. The game would have to know where the steering wheel was regardless of it's position at boot.

A potentiometer would address all these issues.

**Comment by arcadez2003** [comment]
Yeah there was a slight difference of opinion around whether the dump they have was from a dedicated joystick version
of the game i suppose if indeed that was the case and they had added as such it would have saved you the hastle here
but from your comments i think you actually enjoyed the challenge. :)

With regards to the code when i ported it across to my Xbox cores Wheels Runner is fine in MAME72 which has the exact
same input style as this core, but when i tried it in MAME84 which is slap bang in the middle of the huge input rewrite 
the car still spins constantly to the right as soon as you attempt to turn which is par for the course as the analog controls
were always flakey in that core.

No big deal though the main thing is the game now works in this core.

**Comment by mahoneyt944** [comment]
Hmm. The code determines when to stop turning when the input port returns zero. Perhaps that's the issue?

**Comment by mahoneyt944** [comment]
I guess we can close this now. For mame84, I'd recommend writing input port4's value to a log to see what it's doing since the code heavily relies on that ports value. When nothing is being pressed port4 should read zero for the code to work properly (Stop turning that is). Other that that, you can log the main return. Left = 211, center = 199, and right = 191
