### ISSUE TITLE
Save hiscore files regularly to prevent loss of hiscore when exiting abnormally 

### ISSUE THREAD

**Issue by LuoZhongYao** [libretro/mame2003-plus-libretro#1053]
At present, hiscore is only saved when mame exits or resets. On embedded platforms, the power of the machine is usually turned off directly, which will cause hiscore to be lost.

**Comment by mahoneyt944** [comment]
Hiscore saving is considered an add-on as it's typically managed by hacking the memory and reloading it later. Some of these hacks though require the user to coin up and start a new game for the previous high score to be moved into the correct memory location used by the hack for when you do exit.

Above mentioned creates a challenge because these conditions may not be met if you try pulling the memory every so often which could lead to corrupted memory saves. It would also add another routine constantly running in the background of the emulation which could cause slowdowns on weaker platforms.

While I don't discouraged anyone from trying to integrate this somehow, it might be a easier solution to modify your shutdown script to always exit "ESC" the emulator before powering off. This would require more info on your particular platform though.

**Comment by LuoZhongYao** [comment]
> 
> 
> Hiscore saving is considered an add-on as it's typically managed by hacking the memory and reloading it later. Some of these hacks though require the user to coin up and start a new game for the previous high score to be moved into the correct memory location used by the hack for when you do exit.
> 
> Above mentioned creates a challenge because these conditions may not be met if you try pulling the memory every so often which could lead to corrupted memory saves. It would also add another routine constantly running in the background of the emulation which could cause slowdowns on weaker platforms.
> 
> While I don't discouraged anyone from trying to integrate this somehow, it might be a easier solution to modify your shutdown script to always exit "ESC" the emulator before powering off. This would require more info on your particular platform though.

There is a physical switch on my platform, which will directly turn off the power supply of the SoC.

The current implementation, each time saving hiscore will reopen and close the file, which does affect performance, but if you open the file during load, wait until you exit and then close the file and the cache of modern operating systems, it should not bring much Performance problems, and the synchronization period can be increased to reduce the number of synchronizations

**Comment by mahoneyt944** [comment]
This still does not account for the high scores that require the user to do an action for the hack to work properly.... like starting a new game to update the high score, which could cause bad saves or corrupted memory.

https://github.com/libretro/mame2003-plus-libretro/blob/1bb8fc4753f53a4598c8ff1095a5b52c98ccb3ee/metadata/hiscore.dat#L7216

**Comment by markwkidd** [comment]
RetroArch as a frontend has an autosave feature that is active by default on most platforms (including desktop platforms). I think it's typically set to save every few seconds.

We could put a call to save the hiscore in the `retro_serialize` function so that the hiscore is dumped every time the libretro frontend calls to for a save. I wonder what the performance impact would be.

**Comment by mahoneyt944** [comment]
Closed with Merge of #1108
