### ISSUE TITLE
Aladdin inputs

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1131]
@arcadez2003 for some reason the inputs are messed up.

start button - jump
Button 1 - throw
Button 2 - start
Button 3 - sword

Don't really want to swap the port bits yet because it's hiding something. I wonder if this is the case with any other games?

Thinking it's a clash with genesis_68000_io_r / genesis_68000_io_w.

**Comment by mahoneyt944** [comment]
Maybe a clash with genesis_68000_io_w?

**Comment by mahoneyt944** [comment]
Crap barek3b has the same input issue.

**Comment by mahoneyt944** [comment]
Ok I swapped the inputs to what I believe the layout is suppose to be for bare knuckle 3 and Aladdin. There's not much to go on so I referenced the mega drive manual for streets of rage 3. Barek3 input is odd because it uses start as a "4th button" input to swap players in game. There's also a divide with a 3 button Genesis controller vs 6 button mega drive controller.

I'm not sure why the inputs don't line in the order current mame uses, my guess is the io hook up is manipulating the offsets differently or maybe current mame is just wrong too.

**Comment by arcadez2003** [comment]
Yeah i was aware of this personally but anytime i tried to switch the button ordering around on the driver end 
it seemed to break the inputs, although that might be an xbox issue so in the end i just left em as they were and 
remapped em to my liking on the emu side which i just assumed users would do likewise when playing these
in our core.

Sorry about this i thought it an easy quick little test to make sure the inputs were working in this core, all of this
is likely due to me for ease of porting using older genesis input code and these two games are setup input wise
to use the newer Megadrive inputs which are ordered differently hence the buttons are out of line.

Although in my defence all i wanted ya to do was boot the game coin it and see if all the inputs are working
i never mentioned anything about remapping LOL

**Comment by mahoneyt944** [comment]
Not an issue at all. I was actually looking at Aladdin some time ago and passed on it so with the work you put into getting this going, the inputs were nothing.

It seems to be correct now for the old code / inputs but I'm no expert on these games. If you're happy I'm happy lol.

**Comment by grant2258** [comment]
I usually just adjust inputs if I don't work on the defaults too. Don't see it as a big deal

**Comment by mahoneyt944** [comment]
I was just trying to get the IPT_BUTTON# to match the button labels in respect to something concrete, the manuals were really all I could find. How users remap is totally up to them. I just wanted to get a working default of sorts. Documentation isn't an exact science here though either, being a genesis layout to mame layout.

**Comment by grant2258** [comment]
Might be worth checking out the genesis/megadrive cores  to see how they map to the retropad.

**Comment by mahoneyt944** [comment]
That would be Y - B - A

So this
https://github.com/libretro/mame2003-plus-libretro/commit/6d17bcc733f1344f64bb6eaf8a581fd674759c70

**Comment by grant2258** [comment]
That how I would map games like renegade, dragon etc with 3 buttons on a gamepad only. You won't be able to please everyone makes sense with ra to use the retropad as that what ra input is based on.

**Comment by mahoneyt944** [comment]
Good enough for me 🙂 lol
