### ISSUE TITLE
Double Dragon Samples Missing

### ISSUE THREAD

**Issue by ToniBC** [libretro/mame2003-plus-libretro#1140]
Hi, it's been a long time since when you generate the .dat or .xml to complete the romset, the following Double Dragon samples shown in the image are missing.

![Captura de pantalla 2021-08-26 123239](https://user-images.githubusercontent.com/45365478/130948282-0505f11b-62cb-459f-8a59-ebc36b0eccf8.png)

Apparently according to comments in the forums, these samples do not exist, it is a dat error. The game plays with the new music without problems even though those samples are missing.

It could be verified and in case of an error, remove them from the list.

Thanks.

**Comment by KMFDManic** [comment]
@ToniBC @grant2258 @mahoneyt944 @markwkidd Some platforms are incapable of running the "alt" samples sets, due to memory load limitations.  Remember, depending on the Core and file types, some instances require loading "into memory".  This doesn't work so well on RetroPie or the Mini Classics, and can actually lead to crashing or non-load of the games, due to not being able to allocate enough memory!  The samples "we" posted are smaller sized to compensate for the potential crashes.  But, if you have a platform where you CAN load more into memory, such as a PC!  Or, utilize Zram Virtual Ram Swap, they would also work!  I upgraded my Google Drive to be 2 TB and will throw the samples up within the next several days, as I had intended to have these available for the next Release I post, anyways.  But, yeah, the "Stereo" ones did not work properly, for the longest time, simply due to inability to load 300+ MB into memory for "MAME Samples!", at least on the select platforms that have RAM issues.  256 MB of ram ain't gonna cut it!  This cumulative RAM loading effectively counts the size of the rom, the size of the samples, as well as the core size!  So, it all adds up!  It becomes messy when playing PSP games, too!  Anyways, I will link to my Google Drive once I get these up.  They sound fantastic, and I did one video showcasing the SUPER large Stereo Samples, fairly recently, too!  So, you can see how much better they sound than the mono ones!

I have recently upgraded my video setup, which is far better than this earlier video.  And, I do videos with talking, as well as without.  An example of this pristine quality would be my 2 latest Mega Man 4 CUSTOM OST vids, as a comparison...The Mega Man 4 ones sound as amazing as the NEWER MAME ones!  But, you get the idea:)  

https://www.youtube.com/watch?v=1oTii_i0ad0

**Comment by grant2258** [comment]
@KMFDManic I had issues with the big samples it was the loading and unloading that caused it. It is fixable to work properly but the sample code will need tweaking for dynamic loading/unloading for low memory devices.

**Comment by KMFDManic** [comment]
@grant2258 

Let me know if u feel anything can be done hard code wise.  Street Fighter 2 OST generally wont work at all on MD/SNES/NES and similar, without Zram.  Would be beautiful to be able to work around that.  Hope all else is well with you!

**Comment by mahoneyt944** [comment]
@KMFDManic aren't all these samples in wav format? Couldn't we use mp3 or something more compressed?

**Comment by KMFDManic** [comment]
@mahoneyt944 legally, we can really only do wav format.  The necessary coding needed to run mp3s, as far as I'm aware, cannot be "publicly" used...just privately (license wise).  If you look at the genesis plus gx hub, you will see what i mean, viewing the readme there, regarding mp3 usage with that Core.  Mp3s would certainly be nice, if we could legally get away with them.  But, wavs can still be smaller, near mp3 size, per the already current posted samples.

**Comment by mahoneyt944** [comment]
Mp3 is generally 8 to 10 times smaller. So it's definitely interesting. Other than that, there's wav compression tools out there... maybe we read in a wav file as it is one by one, then filter it through a compression method, then copy our filtered version into memory instead of the original? Active compression on large WAV files? Maybe a core option?

**Comment by grant2258** [comment]
@KMFDManic I was just going to fix up into fixing what we had the allocate and deallocate when needed. I patched sf2 on my core to work for sf2 as the samples would stop randomly if @mahoneyt944 wants to add compressed wavs or another format will leave it for him. Only issue with using compressed formats is eating cpu power o lower end devices but all roads lead to Rome.

**Comment by mahoneyt944** [comment]
I don't have much investment into ost samples since I don't really use them personally. what I find most valuable is making sure the originality of the driver is left intact for those who want to play them with original sound. Which means there should never be a "missing samples" notification if the user has this option turned off.

Likewise if the user wishes to use ost samples then notifications of missing samples can useful in most cases.

At some point I recall adding `options.use_samples` to ost driver conditions for this reason to ensure a good user experience however they wish to use or not use these.

I'd be curious to add the sf2 fixes too. Though it's also a game I haven't played much.

**Comment by grant2258** [comment]
Well sf2 did need some fixes I just stopped the big samples from freeing to stop the silence that happened when it did. The problem is we need to store the same being played to free / allocate on the fly

**Comment by srk15372** [comment]
>  I upgraded my Google Drive to be 2 TB and will throw the samples up within the next several days, as I had intended to have these available for the next Release

Hi, any chance to give us a download link for the missing samples track 2 of ddragon and moonwalker? It would be very graceful. Thanks
Regards

**Comment by mahoneyt944** [comment]
We can't link here. @KMFDManic did you locate these samples?

**Comment by mahoneyt944** [comment]
@KMFDManic any progress on this?

**Comment by KMFDManic** [comment]
@ToniBC @mahoneyt944 @grant2258 @arcadez2003 @markwkidd @Wilstorm  I apologize for the delay.  I have temporarily hosted the pertinent sample sets on Google Drive.  Confirm once you have grabbed them, as I will take some of them down.  There are 8 and 16 bit mono and stereo wavs and or flacs for some of them.  A few were previously done before @gpstar81 incorporated the higher level flac awesomeness!  Attached is an older text file with some notes about Moonwalker, as an example.  I will update the notes about this stuff in the near future, to coincide with the Next Release I post.  Source files are also included, for some of the games, if anyone wants to do 16 bit stereo wav or flacs for the ones that were not done yet.  Still, this many years later, I have little or no interest in even listening to the original soundtracks, anymore:)  I am just too much a fan of these masterpieces!  So, for now, be sure to let me know when you've grabbed the pertinent files.  This issue should be able to be closed now.  If anyone wants to try to "help encode" better quality sample sets in 16 bit stereo wav or flacs, be sure to let me know, and we can go from there!  But, grab them now, while you can...And, let me know once you've grabbed them! @Wilstorm , I believe you may have been the one that was interested in the samples before?  If my memory serves me right, you'd probably be the best bet for the higher encodes! 

gpstar81 (porting and backporting entirely different C coding from higher MAME to 2003 (true devotion) and bigbluefrontend (original Final Fight Custom OST origination, SFII), as well as markwkidd, grant2258, have all been instrumental in this amazing implementation and overall Custom OST Project!  Very glad it has worked out so well!  I believe we STILL need to get Street Fighter II Custom OST support into 2003 Plus, however!  There was a reason it was added, then removed, if I recall?  This can be a NEW Issue, if the support is to be added back in...That is, if it has not yet!  And, I find this a bit odd.  I am not even sure if the guy who had communicated with me about this was just messing around or not.  But, he had told me he was able to run Custom OST on Double Dragon II.  I realize they are on the same driver.  I haven't tested this, YET.  But, it would be an interesting test to see what happens if you attempted to run a Custom OST with Double Dragon II, hehe.  Might be a two birds with one stone sort of affair, via an interesting exploit of sorts!  If it DOES work, then, it should be hopefully be easy to pad in the TurboGrafx CD version of Double Dragon II into Plus/Xtreme!  

Thanks, everyone, for all your pure awesomeness.  If we need to continue things, Custom OST wise, feel free to ping me anytime!  Otherwise, will chat with you all on the other "Open" Issues, in the interim!

https://drive.google.com/drive/folders/13Lzqdx2kH-G3t4aStfkznu5uQK7ThMwi

[_km_mame2003_xtreme_moonwalker_7_14_18.txt](https://github.com/libretro/mame2003-plus-libretro/files/7731753/_km_mame2003_xtreme_moonwalker_7_14_18.txt)

**Comment by mahoneyt944** [comment]
@ToniBC once you confirm to have the sample I'll close this. @KMFDManic thanks!

**Comment by ToniBC** [comment]
At the moment everything seems to be working correctly. I like that some of them are in Mono 8bits for the more limited devices and others in Flac that I have not tried yet. The one from Street Fighter 2 still does not appear in the database (xml) so for the moment when passing it CLR it detects it as unknown.

**Comment by mahoneyt944** [comment]
Might not be hooked up here yet.

**Comment by KMFDManic** [comment]
@mahoneyt944 @ToniBC As far as I am aware, SFII Custom OST was added, then removed from MAME 2003 Plus Fork.  For now, it should only work on my fork with MAME 2003 Xtreme.  So, it shouldn't even work, currently, to my last check.  But, it should be able to be readded, if @grant2258 analyzes things and feels comfortable with it.

**Comment by grant2258** [comment]
i added the share last night will download it now. I done a bit of work on sf2 for my port for the sf2 ost. Plus is the only one that doesnt have it not sure why it was removed to be honest would need to as whoever removed it. Ill grab the samples now will let you know when ive downloaded them cheers!

**Comment by mahoneyt944** [comment]
The only thing I recall is this https://github.com/libretro/mame2003-plus-libretro/commit/e6681171d0116e581687e57d65a1275e7839c359 where I believe @Wilstorm was trying to remove ffight ost Samples them from the dat. This was before we had ost specific labeling. I'm sure it's safe to add it in though?

Also I recall https://github.com/libretro/mame2003-plus-libretro/commit/62e938d2b9cdb1c006037444945e0d524dc9467c which allows full bypass so users with the samples turned off don't get the missing samples notifications

**Comment by grant2258** [comment]
de2fbbde7536028d10f4c576f0184fbe2788c03a is where it was reverted no idea why its not showing for you maybe you checked cps2? Ill leave this one to you I done some updates on my port

**Comment by mahoneyt944** [comment]
I never use ost but I think we should isolate these customizations from the original writes that way if there are any issues then the core option can completely bypass them using the original functionality. Maybe we could create a write for the regular sound and for the ost write and use a  ternary operator in the memory map?

**Comment by grant2258** [comment]
there already an option to disable ost

**Comment by mahoneyt944** [comment]
Yes I know, it falls back to the original return. But these long customizations are messy and can introduce bugs which maybe why it was removed at one point. Not to mention the "is playing" and other related flags. Everything is functional just not very tidy.

**Comment by mahoneyt944** [comment]
I'm thinking we should create ost.c and include all the ost functions here. Then include that in the driver's that use it. If the option is turned off it will use the original function is it's on it uses the function is ost.c

**Comment by grant2258** [comment]
feel free to un messy it if you feel that way I think gpstar did a good job with this. one function wont work for every game it still hase to be embedded into the drive to use faded sound ect aka sf2.

**Comment by grant2258** [comment]
https://github.com/libretro/mame2003-plus-libretro/commit/60df6b3b4b4121a6afffd27d41a12a8cb9e40144#diff-1b37a8eb83a3826c81974ada8ac0b94866748064f2bb83f3c3bbf2b0f1344eac just variables needing fixed maybe other issues beyond that in this core I know i dont a few teaks on mine

**Comment by Wilstorm** [comment]
I wasn’t trying to remove them, it was cleanup. If I recall the OST’s were removed but for some reason the Anniversary Edition was still in the DAT. It didn’t make sense to have…that set only…in the DAT. The PR was for continuity. It’s been a while since I’ve rebuilt my set so I’ve no idea if they are in or out at this point.


@KMFDManic - I’m out of the country on holiday for a few more weeks. I’ll see if I can get on a machine to get these beauties downloaded. Huge fan, thank you, thank you!! Once I get back home…if I can get back into the country, as this Omicron variant spreads. :-/ I just did my booster a month ago so that helps. Nah it should be fine. Any support or help I can offer in anyway count me in.

@grant2258 - Thanks so much for all your expertise on the OST’s too. You sure you weren’t a core MAME developer in another life!! :) 

Happy holidays and Merry Christmas to you guys. We’ve been drinking and making merry damn near every night at the local pubs to wee hours in the morning. I’m getting to old for this shit but the mood around the holidays keeps the energy going. It’s going to be a rough go getting back to reality in a few weeks.

**Comment by mahoneyt944** [comment]
@grant2258 this is a preliminary move but we can structure things neatly like this https://github.com/libretro/mame2003-plus-libretro/compare/OST

Some of the init states are not set in the drivers... I'm not sure if that matters but I've copied them as is for now just to get a visual of things.

**Comment by grant2258** [comment]
@mahoneyt944 So far this is just refactoring moving stuff (variables and structures) to another file no real bug changes you where talking about. just copy and pasting else where ill keep my eye on this for the bug fixes. 

@Wilstorm you need real talent to be a mamedev most coders can port other work thats why a lot of people think they are devs because people make open source available so people can use it as they wish they are the real superstars that make things work. I think the best credits belong arcadez he does work for nothing and gets hassle left right and center for all his hard work he does for nothing.

**Comment by mahoneyt944** [comment]
@grant2258 no fixes, just structuring. I'm not sure what I want to do for the functions themselves yet but this at least consolidates things for easier plug and play / updating and later fixes.

Does this look good to you though so far? Haven't missed any flags did I?

**Comment by arcadez2003** [comment]
I think the best credits belong arcadez he does work for nothing and gets hassle left right and center for all his hard work he does for nothing.

Ach just a handful of very vocal MAME dev's that no one outside of their offbeat immediate circles takes any
notice of, a few puddins more or less so not exactly getting flack from all sides here  anyway they're not worth
bothering about :)

**Comment by grant2258** [comment]
@mahoneyt944 nothings changed you just moved some stuff to another file and renamed the some interface sample names should be fine

**Comment by mahoneyt944** [comment]
Alrighty. I just want to say that while I do not use ost samples personally, I do not diminish the work and dedication to those who got these samples to work properly. My previous comments regarding "bugs" was just a generalization and not a strike against anyone's work or pointer to any actual faults. I admire the work put into these and I know people very much like these as an addition to the core. The reason for isolating these is that this core receives lots of updates on drivers and it's easy for a newcomer to disturb these integrations accidentally or even unknowingly. I'm hoping to make these more "plug and play" to the drivers so that the drivers can be modified without too much attention to breaking these integrations. My focus isn't to "fix the ost samples" but to create a structure around them that makes development easier and hopefully to prevent any accidental regressions.

That said, I typically like to include the input of everyone who cares to be involved before structuring things a certain way.

In regards to the term "dev", I think this is a mixed bag.... Certainly some devs pack more punch than others, but any work that makes things better in some way for the end user is development to me. Otherwise the core would be dead. As far as I'm concerned, people that put in hours for no compensation are not frowned upon. The framework of "dev" is so limiting. I'm just a guy that likes old games, if that benefits others in anyway....power to the player.

**Comment by grant2258** [comment]
@mahoneyt944 I wouldnt worry about anyone getting upset if you think things can be done better just do it. It a lot easier to work on the core now than it was before. The resistance we got in changing things in the past was like you bit someone leg off. No one seems to bother now.

**Comment by Wilstorm** [comment]
@grant2258 - I think some people’s minds are just wired for this type of “leisure” activity. When you got it, ya got it! 😎 I would love to see Scotland some day. I’ll have to look you and Arcadez up and buy you a beer…or three. We are deep in the Caribbean just north of Venezuela. They have what are called “safe zones”. You have to show vaccine status, ID, wash your hands, etc. to hang out at these outdoor pubs. It’s alright but the culture dictates drinking and socializing go hand-in-hand and to be honest I just can’t pack it away as well as I used to. My kids are older than half of these guys but they are young, loud and fun. Youth. Cultural differences are a hoot. It’s like a drunk foreign exchange program. 🤔

**Comment by mahoneyt944** [comment]
Since the op has the supported sample packs I'm going to close this. I'm opening an ost issue though to continue discussions. All are welcome to join.

**Comment by grant2258** [comment]
@Wilstorm never seen this post for some reason it didnt show up on my blue bell at the top sounds like your having a nice time there you all stay safe and enjoy the setive season!

**Comment by mahoneyt944** [comment]
@KMFDManic you should try to contact https://samples.mameworld.info/ they have a email link on their page, maybe they will add these as unofficial samples so they are more open to the public?
