### ISSUE TITLE
Star Blade with no ads data

### ISSUE THREAD

**Issue by spielvan** [libretro/mame2003-plus-libretro#1153]
Star Blade without ads data, for this reason, at the beginning, the ship doesn't appear leaving the base.

**Comment by mahoneyt944** [comment]
https://github.com/libretro/mame2003-plus-libretro/commit/b9b23ffc83435b8ba7341608977ffca4113ef84f

Fixes the address but there's still a lot of backporting needed to get that sequence correct.

**Comment by spielvan** [comment]
Ng: Ads Data

**Comment by mahoneyt944** [comment]
> Ng: Ads Data

Delete the starblad.nv file after updating to the latest commit for it to load. This is in mame2003-plus/nvram/starblad.nv

This commit fixes the startup check but not the issue itself.

**Comment by mahoneyt944** [comment]
Maybe @arcadez2003 or @grant2258 see a way to patch this in without a total overhaul? But it looks like a bigger job since starblad wasn't enhanced until much later in mame. Looks to be geared around the master and slave code around mame99u4 ish. There's a note about missing startup graphics in the main driver that was removed around that time. Assuming lots of machine code additions.

**Comment by grant2258** [comment]
I dont know any history of this game to be honest. I doubt it will run well on low end hardware anyway. IF your hardware is capable of running this you probably should be using later version of mame anyway. This version only has 4 cpus from the wip looks like we need 5 or 6. Doesnt mean someone cant updated it just think its beyond the scope of what this core is aimed at for me anyway.

**Comment by mahoneyt944** [comment]
Yeah based on what I'm seeing mame2010 probably has this game functioning more faithfully. I may take another crack at it in this core though but its not a priority right now.
