### ISSUE TITLE
problems with the mouse and pointer device

### ISSUE THREAD

**Issue by ghost** [libretro/mame2003-plus-libretro#1166]
Hi ive compiled the lasted mame as of posting this and the pointer and mouse are acting up using othunder. Its not a driver issue on linux as my port blaster barcade is working properly. lightgun works as it should the other two one randomy works or both dont.

@mahoneyt944  and @mahoneyt944 if you can test your end and let me know how you get on

**Comment by mahoneyt944** [comment]
It seems to be working for me on andriod. Which rev of RA do you have? And you have to select the device you want to read under core options, which you probably know already, Or they won't be read.

**Comment by mahoneyt944** [comment]
the pointer issue is probably the zero return thats under else

**Comment by mahoneyt944** [comment]
@grant2258 does this fix it?
https://github.com/libretro/mame2003-plus-libretro/pull/1167/files

**Comment by grant2258** [comment]
this code needs fixed up more than that your looking for button presses with a pointer position you should be able to get the xy regardless. I can see the light gun and mouse are in one function now ill need to check the input side to see how we are getting the relative and absolute sent to mame now

**Comment by mahoneyt944** [comment]
Ok. Let me know if you need me test something. I'm working on an exhaust job right now but I'll be done in a bit

**Comment by grant2258** [comment]
no problems i think I can see whats happening here the pointer is being read as a relative device instead of an analog one. I think this came from the old legacy apple code that was out of spec with the api. I need to sort one of my cars as well getting a click only when i jerk the steering wheel lightly ive already changed the droplinks and innner and outer tie rods. ball joints are fine need to drop the subframe to check the steering rack adjustment cant be bothered doing that atm.
