### ISSUE TITLE
Lightgun overriding dial control in luckywld

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1275]
When playing luckywld with a lightgun, the lightgun will override the dial control making it impossible to control the dial properly even when remapping the dial inputs.

It's possible to change the dial input to use dial2, but this will likely interfere with player 2 in the same way. So possibly dial3? But this seems a bit wonky.

**Comment by grant2258** [comment]
This is normal analog goes through a range of whats available it tried the original analog control first if nothings there it will use another. You could add mapping for lightguns mice and dials and remove the fallback to other devices and only used whats mapped.

**Comment by mahoneyt944** [comment]
I think the fallback is good in most cases, just not this particular one, maybe we could add a new input flag or something to disable fallback for specific situations like this?

**Comment by grant2258** [comment]
change it here https://github.com/libretro/mame2003-plus-libretro/blob/38fe93119e2606b478a16789ec22d4addef230ae/src/inptport.c#L813 if you want. Would make more sense to change the driver again its up to you if you want to updated the input code both ways work

**Comment by mahoneyt944** [comment]
I'm sure dial3 would work, just seems wonky.

**Comment by StormedBubbles** [comment]
RA does assign lightguns via the mouse indices. 

The RetroArch FBNeo port had this same issue before. That emulator now assigns the steering to controller 1's left stick (analog) as well as gun 1's D-pad (digital) when lightgun mode is activated. 

Since the MAME tab menu is supported in 2003-plus, you can bypass the limitations of RA's input menu and assign buttons and mouse movements to practically whatever you want. As of 1.9.6, RA has the ability to map multiple devices to the same port, but I am not sure of how that affects mice.

The controls for this game are so bizarre that there probably can't be a way to have it be plug and play for everyone 😆

**Comment by grant2258** [comment]
Yeap well you choose the device type pointer your device is lightgun, pointer or mouse ra doesnt do this abstract for you you need to specify it.
