### ISSUE TITLE
Invert mouse x-axis (Left<>Right) and y-axis (up<>down)

### ISSUE THREAD

**Issue by alchle** [libretro/mame2003-plus-libretro#1326]
Long story short - can you add a way to flip mouse axis directions?  Right goes left (and left goes right) as well as option for up to go down and down to go up?  Reason being is I am making an arcade and I want to use a laser mouse and a billiard ball as a trackball.  Mouse will be mounted on the underside of the button panel (with laser light facing up), then a billiard ball rolling on tops of that.  But when I rotate the ball left, obviously the mouse moves right.  I could not find an option in Windows RetroArch with this core to invert axis directions.  I don't want an operating system wide reversal (thus cannot use mouse drivers), just when using this core.  Thanks! Your work is awesome.

**Comment by mahoneyt944** [comment]
Thank you for inquiring on this issue. However, I don't think that we'd want to add these as options since they are very specific. The good news is there are already a few ways you can handle this.

1. Enter the mame menu, go to analog controls and reverse the axis.
![sbowling-220516-232206](https://user-images.githubusercontent.com/49591133/168721980-9c323617-d1cf-4622-879a-4a0c243cb495.png)

2. You could custom wire the mouse / use an encoder board to reverse the polarity. If you are wiring a custom panel this maybe the easiest route. Boards such as the ```ipac2``` are fairly popular

**Comment by mahoneyt944** [comment]
Would it be possible to rotate the laser mouse 180 degrees? I think that might have the same effect you're looking for.

**Comment by alchle** [comment]
mahoneyt944,

Thank you for the quick reply and good input. I totally forgot about mame’s menu. Worked perfectly. Follow up question: I did some testing and it seems that the “analog controls" are game/rom specific (which is what I want). It's just not under the "this game" settings so I wasn't sure. Can you confirm?

I saw your other note about rotating the mouse. This will work too if I don't need the y-Axis. The mame settings will work the best.

Thank you again for the help

-alchle
________________________________

**Comment by mahoneyt944** [comment]
Not all games have analog controls to list in the mame menu. Most of the games using a trackball will though so start there. If it doesn't you can reverse the mappings under (input this game), but you'll actually have to remap each one.
Left ---> right
Right ---> left
Up ---> down
Down ---> up
