### ISSUE TITLE
Sega System 32 Spiderman, Golden Axe - The Revenge of Death Adder - Segasonic the Hedgehog: imperfect graphics

### ISSUE THREAD

**Issue by BiobaTiry** [libretro/mame2003-plus-libretro#1328]
I would like to ask if it is possible to correct the graphic imperfections in the titles Spiderman, Golden Axe - The Revenge of Death Adder - Segasonic the Hedgehog, they are playable but not perfect. 
Is it possible to implement fixes for games on the SEGA System 32 platform?

**Comment by mahoneyt944** [comment]
I've looked at the system32 driver games before and the video code needs a pretty big overhaul to achieve this.....even then it may still have some imperfections. Even looking to mame2010 - mame2015 all these games are tagged imperfect still.

**Comment by BiobaTiry** [comment]
Thanks for the answer, I tested GA2 above all and I noticed that with ADVMame it has much less imperfections, maybe you could "use" that driver.
Could you use or import that driver?

**Comment by mahoneyt944** [comment]
It's not as simple as that unfortunately. The architecture of the driver changes throughout each release of mame. System32 in particular changed very significantly. Sometimes we get lucky and the changes required can easily be retrofitted....but in this case, it's a total rewrite of the video code. It's certainly possible, but it's a pretty intensive amount of work that no devs have self elected to take on yet.

**Comment by BiobaTiry** [comment]
I understand ... thanks for the feedback ... great job

**Comment by arcadez2003** [comment]
> I understand ... thanks for the feedback ... great job

If it could be done then it would have already, as @mahoneyt944 touched upon we need the newer video code
but in order to use that we also need the newer driver to match it, which unfortunately has an input handling method 
this core cannot support inputs setup by named tagging basically.

Plus on top of that there is memory address mirroring that again MAME78 cannot support, i've placed this on the
cannot be done list but as i always say someone might come along one day and prove me wrong which would be 
nice to see.
