### ISSUE TITLE
Dkong color hack - by capcob

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1494]
This solution was presented by capcob on the RetroPie forums. Essentially pulling the color palette from FBNEO. Details posted here. https://retropie.org.uk/forum/topic/33622/donkey-kong-color-palette-for-fbneo-hacked-into-mame2003-libretro
```
static int FBNeoPalette[256][4] =
{
    { 0, 0, 0, 0 },
    { 9145343, 139, 139, 255 },
    { 57855, 0, 225, 255 },
    { 14745600, 225, 0, 0 },
    { 0, 0, 0, 0 },
    { 14788352, 225, 167, 0 },
    { 14745600, 225, 0, 0 },
    { 14803455, 225, 225, 255 },
    { 0, 0, 0, 0 },
    { 14788490, 225, 167, 138 },
    { 14745600, 225, 0, 0 },
    { 218, 0, 0, 218 },
    { 0, 0, 0, 0 },
    { 255, 0, 0, 255 },
    { 14745600, 225, 0, 0 },
    { 57600, 0, 225, 0 },
    { 0, 0, 0, 0 },
    { 14771712, 225, 102, 0 },
    { 14788352, 225, 167, 0 },
    { 14745600, 225, 0, 0 },
    { 0, 0, 0, 0 },
    { 14803455, 225, 225, 255 },
    { 14745818, 225, 0, 218 },
    { 14803200, 225, 225, 0 },
    { 0, 0, 0, 0 },
    { 14745600, 225, 0, 0 },
    { 255, 0, 0, 255 },
    { 57855, 0, 225, 255 },
    { 0, 0, 0, 0 },
    { 10944512, 167, 0, 0 },
    { 14788490, 225, 167, 138 },
    { 14803455, 225, 225, 255 },
    { 0, 0, 0, 0 },
    { 10944512, 167, 0, 0 },
    { 14788490, 225, 167, 138 },
    { 14771712, 225, 102, 0 },
    { 0, 0, 0, 0 },
    { 14803455, 225, 225, 255 },
    { 14771712, 225, 102, 0 },
    { 14763994, 225, 71, 218 },
    { 0, 0, 0, 0 },
    { 218, 0, 0, 218 },
    { 14803455, 225, 225, 255 },
    { 14763994, 225, 71, 218 },
    { 0, 0, 0, 0 },
    { 255, 0, 0, 255 },
    { 14771712, 225, 102, 0 },
    { 14788490, 225, 167, 138 },
    { 0, 0, 0, 0 },
    { 14803455, 225, 225, 255 },
    { 57855, 0, 225, 255 },
    { 255, 0, 0, 255 },
    { 0, 0, 0, 0 },
    { 14745600, 225, 0, 0 },
    { 14788352, 225, 167, 0 },
    { 14771712, 225, 102, 0 },
    { 0, 0, 0, 0 },
    { 12946314, 197, 139, 138 },
    { 14788490, 225, 167, 138 },
    { 255, 0, 0, 255 },
    { 0, 0, 0, 0 },
    { 14788352, 225, 167, 0 },
    { 14745600, 225, 0, 0 },
    { 0, 0, 0, 0 },
    { 0, 0, 0, 0 },
    { 9145343, 139, 139, 255 },
    { 57855, 0, 225, 255 },
    { 14745600, 225, 0, 0 },
    { 0, 0, 0, 0 },
    { 14788352, 225, 167, 0 },
    { 14745600, 225, 0, 0 },
    { 14803455, 225, 225, 255 },
    { 0, 0, 0, 0 },
    { 14788490, 225, 167, 138 },
    { 14745600, 225, 0, 0 },
    { 218, 0, 0, 218 },
    { 0, 0, 0, 0 },
    { 14771712, 225, 102, 0 },
    { 14788490, 225, 167, 138 },
    { 14803455, 225, 225, 255 },
    { 0, 0, 0, 0 },
    { 14771712, 225, 102, 0 },
    { 14788490, 225, 167, 138 },
    { 14803455, 225, 225, 255 },
    { 0, 0, 0, 0 },
    { 14771712, 225, 102, 0 },
    { 14788490, 225, 167, 138 },
    { 14803455, 225, 225, 255 },
    { 0, 0, 0, 0 },
    { 14771712, 225, 102, 0 },
    { 14788490, 225, 167, 138 },
    { 14803455, 225, 225, 255 },
    { 0, 0, 0, 0 },
    { 10944512, 167, 0, 0 },
    { 14788490, 225, 167, 138 },
    { 14803455, 225, 225, 255 },
    { 0, 0, 0, 0 },
    { 10944512, 167, 0, 0 },
    { 14788490, 225, 167, 138 },
    { 14771712, 225, 102, 0 },
    { 0, 0, 0, 0 },
    { 14803455, 225, 225, 255 },
    { 14771712, 225, 102, 0 },
    { 14763994, 225, 71, 218 },
    { 0, 0, 0, 0 },
    { 218, 0, 0, 218 },
    { 14803455, 225, 225, 255 },
    { 14763994, 225, 71, 218 },
    { 0, 0, 0, 0 },
    { 255, 0, 0, 255 },
    { 14771712, 225, 102, 0 },
    { 14788490, 225, 167, 138 },
    { 0, 0, 0, 0 },
    { 14803455, 225, 225, 255 },
    { 57855, 0, 225, 255 },
    { 255, 0, 0, 255 },
    { 0, 0, 0, 0 },
    { 14745600, 225, 0, 0 },
    { 14788352, 225, 167, 0 },
    { 14771712, 225, 102, 0 },
    { 0, 0, 0, 0 },
    { 12946314, 197, 139, 138 },
    { 14788490, 225, 167, 138 },
    { 255, 0, 0, 255 },
    { 0, 0, 0, 0 },
    { 14788352, 225, 167, 0 },
    { 14745600, 225, 0, 0 },
    { 0, 0, 0, 0 },
    { 0, 0, 0, 0 },
    { 9145343, 139, 139, 255 },
    { 57855, 0, 225, 255 },
    { 14745600, 225, 0, 0 },
    { 0, 0, 0, 0 },
    { 14788352, 225, 167, 0 },
    { 14745600, 225, 0, 0 },
    { 14803455, 225, 225, 255 },
    { 0, 0, 0, 0 },
    { 14788490, 225, 167, 138 },
    { 14745600, 225, 0, 0 },
    { 218, 0, 0, 218 },
    { 0, 0, 0, 0 },
    { 14754954, 225, 36, 138 },
    { 9109504, 139, 0, 0 },
    { 57855, 0, 225, 255 },
    { 0, 0, 0, 0 },
    { 14754954, 225, 36, 138 },
    { 9109504, 139, 0, 0 },
    { 57855, 0, 225, 255 },
    { 0, 0, 0, 0 },
    { 14754954, 225, 36, 138 },
    { 9109504, 139, 0, 0 },
    { 57855, 0, 225, 255 },
    { 0, 0, 0, 0 },
    { 14754954, 225, 36, 138 },
    { 9109504, 139, 0, 0 },
    { 57855, 0, 225, 255 },
    { 0, 0, 0, 0 },
    { 10944512, 167, 0, 0 },
    { 14788490, 225, 167, 138 },
    { 14803455, 225, 225, 255 },
    { 0, 0, 0, 0 },
    { 10944512, 167, 0, 0 },
    { 14788490, 225, 167, 138 },
    { 14771712, 225, 102, 0 },
    { 0, 0, 0, 0 },
    { 14803455, 225, 225, 255 },
    { 14771712, 225, 102, 0 },
    { 14763994, 225, 71, 218 },
    { 0, 0, 0, 0 },
    { 218, 0, 0, 218 },
    { 14803455, 225, 225, 255 },
    { 14763994, 225, 71, 218 },
    { 0, 0, 0, 0 },
    { 255, 0, 0, 255 },
    { 14771712, 225, 102, 0 },
    { 14788490, 225, 167, 138 },
    { 0, 0, 0, 0 },
    { 14803455, 225, 225, 255 },
    { 57855, 0, 225, 255 },
    { 255, 0, 0, 255 },
    { 0, 0, 0, 0 },
    { 14745600, 225, 0, 0 },
    { 14788352, 225, 167, 0 },
    { 14771712, 225, 102, 0 },
    { 0, 0, 0, 0 },
    { 12946314, 197, 139, 138 },
    { 14788490, 225, 167, 138 },
    { 255, 0, 0, 255 },
    { 0, 0, 0, 0 },
    { 14788352, 225, 167, 0 },
    { 14745600, 225, 0, 0 },
    { 0, 0, 0, 0 },
    { 0, 0, 0, 0 },
    { 9145343, 139, 139, 255 },
    { 57855, 0, 225, 255 },
    { 14745600, 225, 0, 0 },
    { 0, 0, 0, 0 },
    { 14788352, 225, 167, 0 },
    { 14745600, 225, 0, 0 },
    { 14803455, 225, 225, 255 },
    { 0, 0, 0, 0 },
    { 14788490, 225, 167, 138 },
    { 14745600, 225, 0, 0 },
    { 218, 0, 0, 218 },
    { 0, 0, 0, 0 },
    { 255, 0, 0, 255 },
    { 57855, 0, 225, 255 },
    { 14788352, 225, 167, 0 },
    { 0, 0, 0, 0 },
    { 255, 0, 0, 255 },
    { 57855, 0, 225, 255 },
    { 14788352, 225, 167, 0 },
    { 0, 0, 0, 0 },
    { 255, 0, 0, 255 },
    { 57855, 0, 225, 255 },
    { 14788352, 225, 167, 0 },
    { 0, 0, 0, 0 },
    { 255, 0, 0, 255 },
    { 57855, 0, 225, 255 },
    { 14788352, 225, 167, 0 },
    { 0, 0, 0, 0 },
    { 10944512, 167, 0, 0 },
    { 14788490, 225, 167, 138 },
    { 14803455, 225, 225, 255 },
    { 0, 0, 0, 0 },
    { 10944512, 167, 0, 0 },
    { 14788490, 225, 167, 138 },
    { 14771712, 225, 102, 0 },
    { 0, 0, 0, 0 },
    { 14803455, 225, 225, 255 },
    { 14771712, 225, 102, 0 },
    { 14763994, 225, 71, 218 },
    { 0, 0, 0, 0 },
    { 218, 0, 0, 218 },
    { 14803455, 225, 225, 255 },
    { 14763994, 225, 71, 218 },
    { 0, 0, 0, 0 },
    { 255, 0, 0, 255 },
    { 14771712, 225, 102, 0 },
    { 14788490, 225, 167, 138 },
    { 0, 0, 0, 0 },
    { 14803455, 225, 225, 255 },
    { 57855, 0, 225, 255 },
    { 255, 0, 0, 255 },
    { 0, 0, 0, 0 },
    { 14745600, 225, 0, 0 },
    { 14788352, 225, 167, 0 },
    { 14771712, 225, 102, 0 },
    { 0, 0, 0, 0 },
    { 12946314, 197, 139, 138 },
    { 14788490, 225, 167, 138 },
    { 255, 0, 0, 255 },
    { 0, 0, 0, 0 },
    { 14788352, 225, 167, 0 },
    { 14745600, 225, 0, 0 },
    { 0, 0, 0, 0 }
};
```

**Comment by mahoneyt944** [comment]
@timcannel merged port from mame2003

**Comment by Wilstorm** [comment]
@mahoneyt944 - I won't add anything more as the conversation in the other thread covered it all pretty well and was locked but just for the record the 2003+ change log is fairly detailed with all the main changes correct? I know a change log was brought up but I was thinking there's a pretty detailed one available here at this [link](https://github.com/libretro/mame2003-plus-libretro/blob/master/CHANGELOG.md) that is current?

**Comment by Wilstorm** [comment]
@mahoneyt944 - Ah ok, I thought so, but wasn't sure on the details. I appreciate the information and I wish you and the 2003+ crew happy holidays. I'm pretty sure it comes quicker and quicker...every year! ;-P

**Comment by mahoneyt944** [comment]
Happy holidays

**Comment by arcadez2003** [comment]
Personally i'd like to have seen this done in a more cleaner way but needs must i suppose as let's be honest here no one
was gonna step up due to the workload required to update the resnet gfx then every driver and vidhrdw src file 
using it all so we could backporta fix for a rather IMO trivial issue with the colours in Donkey Kong.

But hey ho at least now i wont have to explain to a certain someone every two mins it seemed as to the reasons why less important things were not dropped on the spot so we could all work on this :)

Anyway two questions

Do other games share the same pallette code.?? and ifso do they play nice with this change.??

**Comment by mahoneyt944** [comment]
Anything using dkong_palette_init. Outside that idk.

**Comment by mahoneyt944** [comment]
@btw, the actual committed code is cleaner than the monster in the first post above

**Comment by arcadez2003** [comment]
> @arcadez2003 , the actual committed code is cleaner than the monster in the first post above

Well sure but i meant cleaner in the sense we did it without the need for a hack of this type eg via the resnet gfx
but since as i said earlier it's understandable due to the workload required no one wanted to touch that with a barge
pole then this is the next best thing well it's the only thing anyone has come forward with and it's good to see.

Im sorry if i dont sound very enthusiastic here as well i never really cared about about this issue other than a certain
someone liked to bang on about it all the time as if it was something to prove their point that ole cores like this should
be dumped and users should at once switch to using the latest FBNeo allbeit half the games they play would end up
running 90% slower in the process :)

**Comment by mahoneyt944** [comment]
That's what makes this fix pretty ironic 😂.

**Comment by mahoneyt944** [comment]
Though if we ever backported the resnet code, we could probably isolate it and only hook it up to games as needed.

**Comment by arcadez2003** [comment]
> That's what makes this fix pretty ironic 😂.

Aye but we've not achieved it in the "correct" way which will likely be the reason given to favour FBNeo going forward :)

**Comment by arcadez2003** [comment]
> @mahoneyt944 - Ah ok, I thought so, but wasn't sure on the details. I appreciate the information and I wish you and the 2003+ crew happy holidays. I'm pretty sure it comes quicker and quicker...every year! ;-P

Well being old skool and totally non pc i'll phrase it as we used to "have a merry xmas and a happy new year when it comes" :)

**Comment by arcadez2003** [comment]
> > I'm pretty sure it comes quicker and quicker...every year! ;-P
> 
> keep it clean hahah!
> 
> @mahoneyt944 nice to see it added here as well! It should be called Dkong pretty in pink color hack has a nice ring to it.

Well i think i might have added the Rainbow hack not sure.?? but if everyone had used that version then none of us would 
have been any the wiser around the colours having slightly the wrong hue.

**Comment by arcadez2003** [comment]
> Anything using dkong_palette_init. Outside that idk.

That's every game in the dkong driver then

**Comment by arcadez2003** [comment]
> ill check what games use the same color proms and sort it at the weekend if there is any issues. Might even look at fixing the res_net decode depends if my cars back by then as its getting fixed atm and i bet they make me wait till sat haha.

Your not workshy that's for sure :) 

All joking aside i took a quick look back when saw we didn't have the code where the fix was done and lost interest 
maybe it's possible to implement it with some minor modifications good luck.

**Comment by mahoneyt944** [comment]
Yeah I need them side by side to notice. And that's assuming the monitor colors aren't skewing them either
![dkong-221212-143341](https://user-images.githubusercontent.com/49591133/207474804-685232b2-23ad-4cef-b354-262d505e224b.png)
![dkong-221212-143249](https://user-images.githubusercontent.com/49591133/207474806-4ffa5409-6777-431d-a11f-00e50349afe2.png)

**Comment by arcadez2003** [comment]
Yip i gotta say i prefer the "wrong colours" so add me to that list of those with the unusual preferences :)

Anyway some non working games and some without sound in dkong.c maybe it;s worth fixing those up sometime.??

**Comment by arcadez2003** [comment]
Im not that fussed TBH do what ya's feel is best

**Comment by arcadez2003** [comment]
Resnet to fix the colours would likely be enough, as for the discrete sounds that is a whole other debate as many users
are still split over prefering the ole samples over the newer discrete setup, me i've only ever used samples so cant really
compare. the two.

**Comment by arcadez2003** [comment]
Good job

**Comment by Wilstorm** [comment]
> > I'm pretty sure it comes quicker and quicker...every year! ;-P
> 
> keep it clean hahah!
> 

@MistyDreams - Always! I'll take it anyway I can get it! ;) 

I finally had time to read the last post on RP forums. When I try to frame it in context (truly) and try to be unbiased I can't help but to think of cynicism, anger, or some combination. I really, really...don't get it. Possibly a struggle with English and comprehension of the written word. 

After he started attacking folks on a more personal level about their English (ironically or not) they locked him out there too! Shouldn't that tell you something! I guess he can't get enough baseless arguments. The use of caps and bold type just isn't effective to me unless it's a **WARNING: This may explode.** in a technical manual! ;-) So much anger I guess.

Anyway sorry off track, I appreciate all you guys have done. I would stick with this core whether the colors were implemented or not but it's kind of nice to see them corrected, plus the additional games you tweaked. I'll definitely use the update and it also has a great story to go with it now.

@mahoneyt944 - The screenshots nicely showcase the change! It helps to see the before and after of the subtle but distinct change.

Uuugh...Christmas holiday is over, it's back to work for a few days and then one more long weekend before the grind begins, but today is 30F (-1C) vs. -20F (about -29C).  It actually feels pretty decent outside after that deep cold snap!

I wish you guys and your families well in the coming year, it's time to ring out the old and ring in the new! :) See ya next year, OK. about 5 days or so! ;)

**Comment by Wilstorm** [comment]
@MistyDreams - I appreciate the advice and I'll do that. He's gunning hard now. In addition to bringing up old stuff, I think about Grant (or someone else possibly, who knows). I don't know but he seems to keep holding on to things that are really old and irrelevant to the fix. The thing is I can't tell because his last post on RP was a myriad of rantings and old post links that have absolutely nothing to do with the current decision of whether to implement the change into mame2003-plus. Attacking English speakers. Who does that? It's a medley of nonsense.

He says he was never against putting the change into mame2003-plus and everyone agrees with him! He just keeps insisting that "someone" is saying he was against it but when you ask for a post showing this type of information he won't link anything. He just goes on and on about sidebar stuff and scrambles all the information until nothing really makes sense. It's like the ramblings of a mad man and the question is simple.

Anyway the offer of the color fix was incredibly kind of Tim. I was just trying to be supportive but "that guy" is something else. Then when Libretro locked the thread he immediately carried it over to the RetroPie forums where Tim originally posted. Now he just can't stop himself and let it go! He just keeps pounding everyone every chance he gets that disagrees with him. He kind of gives Libretro a bad name or at least bad representation for the brand.

I only follow this core and the vanilla version so I am sure I miss many things on other cores and other websites and I'm ok with that. I saw Tim's original post and thought, "What a great idea!" and it was "Really nice of him". That just led down a rabbit hole of nonsense and ridiculous suggestions. The color change seems to really piss him off and I just don't understand why!

Now I understand Grant's point of view from many years ago when he had to defend the core. Anyway thanks again for giving me some leeway on this and I'll put it to bed now and hopefully be done with it. But I just have to say you guys are super hero's for all the petty shit you must put up with on a daily basis!
