### ISSUE TITLE
B.Rap Boys (World)

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/mame2003-plus-libretro#1533]
B.Rap Boys (World) has a popping sound playing when the music is playing. This games needs to say imperfect sound. Newer MAME this does not happen.

**Comment by mahoneyt944** [comment]
@arcadez2003 did a major update to this driver making many of these playable at all. Quite a bit of work by the looks of it. Of course there maybe something overlooked or a regression with a sound core update after the fact to check into...possibly an additional fix needed as well. Thanks for reporting this, we'll have to see what's going on.

**Comment by arcadez2003** [comment]
Actually it was IQ_132 and BritneysPAIRS that updated the Kaneko 16 driver my only input was to port it across to here 
not an insignificant contribution right enough as i fthen ixed some graphical and sound issues in some of the games and
added support for Pack n Bang Bang and Wing Force :)

Anyway less of memory lane and more to the question at hand......

0.190: Fixed a longstanding INP playback desync bug caused by a rand() call in the MAME core (emu\ioport.cpp), fixed playback lose sync in B.Rap Boys [Angelo Salese, hap]
0.135: David Haywood changed sound banking on B.Rap Boys to use an OKIM6295 address map and banks. Changed region samples to oki1.
0.134u1: Kitsune Sniper, hap, Haze and Guru fixed music samples looping incorrectly / ending too soon in B.Rap Boys and clone. Changed clock speeds of the 2x OKI6295 to 2MHz and VSync to 59.185400 Hz.

I think we have the fix from 134.u1 the other two not so much, maybe that is what we need maybe it's not im busy
just now with other things but i might come back to look at fixing not only the sound but the gfx niggles these games
have down the road...

But that would require the video changes @MistyDreams was keen to add some time back.

**Comment by arcadez2003** [comment]
Aye worth a try i suppose

**Comment by mahoneyt944** [comment]
Do the other games play nice with this change or would we need to split them.

**Comment by mahoneyt944** [comment]
Libretro does not support harassment or comments which endorse that kind of behavior. Your previous response was off topic and inappropriate.

**Comment by mahoneyt944** [comment]
@MistyDreams You just can't seem to get along with others, no matter what alias you're under. You throw tantrums anytime someone has a different view than you.

**Comment by mahoneyt944** [comment]
The rounding code isn't mine, I just happen to agree with it. Please refrain from posting in this project. If you're parting ways, please do so

**Comment by arcadez2003** [comment]
Well all this drama over a simple question as to if the above change for B-Rap Boys sound will have a negative affect
on the other games that share okim6295_intf_2x12kHz eg.......

Great Thousand Mile Rally
Great Thousand Mile Rally 2
Shogun Warriors

Personally i'd wanna know that so would have tested after making such a change hence why i didn't volunteer :)

**Comment by arcadez2003** [comment]
Sure it's easy but i cant be assed tweaking the sound clocks and then having to test all the games affected just at 
the moment..

B-Rap Boys  
Great Thousand Mile Rally
Great Thousand Mile Rally 2
Shogun Warriors

why dont you do it.??

**Comment by mahoneyt944** [comment]
That's just a temporary workaround until the proper fix is implemented. We'll close this once the code is pulled and tested.

**Comment by arcadez2003** [comment]
Im gonna do it now i guess since no one else wants to tackle it

**Comment by mahoneyt944** [comment]
![ok-then-i](https://user-images.githubusercontent.com/49591133/216634070-ff3dd608-1bd9-4fdc-81ce-e4a58e721c5c.jpg)

Lol joking aside. Thanks 👍

**Comment by arcadez2003** [comment]
There is more goin on here........

https://github.com/arcadez2003/mame/commits/master?after=08b773a665063a35365a4c93fb3c7e9e7be515d3+104&branch=master&path%5B%5D=src&path%5B%5D=mame&path%5B%5D=drivers&path%5B%5D=kaneko16.c&qualified_name=refs%2Fheads%2Fmaster

Outta those commits we have the fixes up until........
https://github.com/arcadez2003/mame/commit/ec2fc0a273109d17ab1f7bcc149098c64aac0ef7

A simple change to the FPS but notice the clock speed they're far higher than what we have........

	MDRV_SOUND_ADD("oki1", OKIM6295, 1980000)
	MDRV_SOUND_CONFIG(okim6295_interface_pin7low) // clock frequency & pin 7 not verified
	MDRV_SOUND_ROUTE(ALL_OUTPUTS, "mono", 1.0)

	MDRV_SOUND_ADD("oki2", OKIM6295, 1980000)
	MDRV_SOUND_CONFIG(okim6295_interface_pin7low) // clock frequency & pin 7 not verified
	MDRV_SOUND_ROUTE(ALL_OUTPUTS, "mono", 1.0)

Then the next fix
https://github.com/arcadez2003/mame/commit/fd753d02d63e0fcb3fbe87043fd8760bae5ef345

We have this change
	MDRV_FRAMES_PER_SECOND(59.1854)

But not the clocks which would be     { 16000000/8/165, 16000000/8/165 }, for this core

I've found with a quite a few drivers where IQ_132 and BritneysPAIRS were the original dev's during the update
they did miss some important changes and or fixes, anyhow im using the clocks above and the game sounds
alot better now.

**Comment by arcadez2003** [comment]
https://github.com/libretro/mame2003-plus-libretro/commit/62408bb3c494a087e1b50878d25623064a15e62a

**Comment by mahoneyt944** [comment]
@Cibomatto2002 can you confirm this fixes you issue? Update from source.

**Comment by Cibomatto2002** [comment]
I will try it later tonight if I update the core on retroarch will the fix be there?

**Comment by Cibomatto2002** [comment]
It is fixed now thanks to everyone that help get this fixed .
