### ISSUE TITLE
Nebulas Ray (nebulray) graphical error

### ISSUE THREAD

**Issue by wn2000** [libretro/mame2003-plus-libretro#1598]
As shown in the following screenshot:

![image](https://github.com/libretro/mame2003-plus-libretro/assets/64153870/e76550ed-ba58-4e86-90bd-b083929e01bf)

There are multiple fixes after 0.78, but I wonder if this one addresses the issue:

0.88u1: Phil Stroffolino added a kludge to fixed sprite clipping in Nebulas Ray (real behavior not understood).

The git history on mamedev only goes back to 0.121. Where can I find histories before that?

**Comment by mahoneyt944** [comment]
Historical mame GitHub
https://github.com/mamedev/historic-mame/

**Comment by arcadez2003** [comment]
Yeah the changes from MAME88.u1 will get Nebulas Ray looking far better but you'd need these fixes to totally sort it.........

0.234: Added Namco posirq kludge for Nebulas Ray to prevent a bad line on the right of the screen and some stars don't scroll correctly [David Haywood].
0.203: Correct sprite lags. Removed unnecessary defines. Added screen raw parameters (Nebulas Ray reference: https://youtu.be/mAB66HhZNIM) [cam900].
0.155: Improved interrupt handling, fixing raster-effects used by Nebulas Ray and Nebulas Ray test mode. This fixes game is missing a rotation effect in the first level [Phil Bennett]. Fixed missing starfield. Basically fixed by Phil's update, we no longer need to patch out parts of the gfx rom [David Haywood].

But even after the above you'd need to look at adding the CPU which drives the sound and music for this game and quite
a few other Namco titles.

**Comment by wn2000** [comment]
> Adding the CPU to MAME78 will not be easy but if your using a later post MAME79 core then it should be doable i have
all the code for this already via my Xbox project which is based off MAME84 you'd be welcome to it should it be of any use.

@arcadez2003 That sounds awesome. Can you link me to your repo?

**Comment by arcadez2003** [comment]
Actually after cheacking the code i remember now that i did the update to MAME88.u1 noticed a large performance drop
for some big name Namco titles on the xbox and reverted it however i did add sound to Nebulas Ray and some other
games that shared the same driver if that is any good to ya.??

**Comment by wn2000** [comment]
> Actually after cheacking the code i remember now that i did the update to MAME88.u1 noticed a large performance drop
> for some big name Namco titles on the xbox and reverted it however i did add sound to Nebulas Ray and some other
> games that shared the same driver if that is any good to ya.??

Yes absolutely. I'd like to see how it's supposed to be done even the performance may degrade, just for learning purpose. Thank you!

**Comment by arcadez2003** [comment]
Maybe i should have said i haven't uploaded MAMEoXtras to the git i physically mod the files on my pc then compile an
xbox xbe using VS-2003 so what im saying is although i did the Namco video update i wasn't happy with the outcome
so i deleted all the code and rolled back the src files to earlier versions.

What this means is i dont have the video code anymore although your welcome to the sound code.

However you can check this diff file from MAME88.u1 and you'll see all the changes you'd require to sort this gfx in this 
game
[088u1_diff.zip](https://github.com/libretro/mame2003-plus-libretro/files/11645357/088u1_diff.zip)

**Comment by arcadez2003** [comment]
It's alotta work to fix this issue but in doing so all the games affected will take a big hit in performance which is
a no no for this core, closing this down
