### ISSUE TITLE
UMK3 - Selec Character Screen bugged

### ISSUE THREAD

**Issue by ZacharyFoxx** [libretro/mame2003-plus-libretro#1605]
Used core version: 71766e8

The character selection screen is all buggy. All the portraits of the characters are like an old tv with an off-air channel. The doll of the character where you are is also the same way.

After choosing the character, the portrait and the character are normal.

In an old version of core, code f2018df, the problem does not exist and the game is normal.

**Comment by mahoneyt944** [comment]
Are you referring to the "color bomb" effect similar to this? This is actually a glitch on real hardware, which has to to with specific timings causing the color palette to wrap. Timing 
on real hardware is less than optimal which results in much fewer color wraps... Unfortunately Mames timings are more optimal which means more frequent color wrapping, it's even worse when you have the 3 hidden characters unlocked . This game being one of my personal favorites, I would recommend playing UMK3 Plus Beta 2. This modded version adds more graphics which by blind luck seems to reduce if not eliminate this issue. rom "umk3p"

![umk3-glitch03](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/da101b6b-a1c5-4afd-b7fc-dceaa8a3eb68)

**Comment by ZacharyFoxx** [comment]
> Are you referring to the "color bomb" effect similar to this? This is actually a glitch on real hardware, which has to to with specific timings causing the color palette to wrap. Timing on real hardware is less than optimal which results in much fewer color wraps... Unfortunately Mames timings are more optimal which means more frequent color wrapping, it's even worse when you have the 3 hidden characters unlocked . This game being one of my personal favorites, I would recommend playing UMK3 Plus Beta 2. This modded version adds more graphics which by blind luck seems to reduce if not eliminate this issue. rom "umk3p"
> 
> ![umk3-glitch03](https://user-images.githubusercontent.com/49591133/249007853-da101b6b-a1c5-4afd-b7fc-dceaa8a3eb68.png)

Yep, exactly this glitch. But as I said, the core in the f2018df version has no problem, it works normally.

**Comment by mahoneyt944** [comment]
Well it's certainly not a new issue but that's not the full picture......the core now by default unlocks ermac, meleena, and ninja subzero which aggravates this condition causing the the timing problem to occur more regularly...so it goofs up the palette more often than before... You can reduce, but not entirely eliminate, the issue by relocking these characters in the service menu. Or as I mention before, umk3 plus has seemingly fixed this issue indirectly by adding more graphics, which naturally delays this timing issue enough to not occur. I've personally tested full playthroughs on every tower maybe 2 or 3 dozen times without issue. l cant claim it can't happen with umk3p but it surely hasn't for me and I play it fairly regularly.

Other than that though, this glitch happens on actual hardware. So its not a bug we can fix. The best we can do, which is what we currently do, is deliberately delay the CPU when this loading occurs, which isn't full proof. Some notes in the code about this exact issue,
https://github.com/libretro/mame2003-plus-libretro/blob/71766e8f0cadb80eb6c735a76581a94b2c87769d/src/machine/midwunit_machine.c#L418-L441

**Comment by mahoneyt944** [comment]
That was a workaround for mk2 and mk to both work..... Mk requires 41 for the comic book offer text to work and mk2 requires 42 for the demo text to work correctly. Being that 42 was the original value, we only modify it for mk currently.

This issue here isn't a new issue it's well documented even in current mame. It just made worse with the characters unlocked.

**Comment by mahoneyt944** [comment]
![Screenshot_20230627-205509](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/29474f08-1b8f-41ed-adbe-e406df810a66)

**Comment by mahoneyt944** [comment]
There maybe a way to improve this condition by modifying the palette hack. Not sure its optimized for the conditions you just mentioned. There's also fair evidence that the differences in umk3p graphics loading seems to fix this issue so there maybe something there to exploit as well.

**Comment by mahoneyt944** [comment]
When I bootstrapped umk3, I used the cheat codes to unlock the characters which save in nvram. So I could remove those and redo the bootstrap if we think that's the way to go. Curious how umk3p works though, my suspicion is the extra graphics rom loading? But idk. Could maybe play with fake graphic regions?

**Comment by mahoneyt944** [comment]
Yeah it's not the most convenient way of it for sure, seems like most of the troublesome games are bootstrapped now though so I don't mind minor tweaks every now and then. But it's a valid point to consider. I guess if we had a high volume of games we needed to turn over the rom loads would be the ticket assuming the ones available are set in a way we'd want. Though we could make them downloadable from this repo but there maybe legal issues sharing those saves? Not sure.

I'll redo these ones when I get a chance though since it seems the unlocked characters cause more harm than good in this instance.

**Comment by mahoneyt944** [comment]
Here's both umk3 nv files to replace your existing ones. Just unzip and drop them in your save folder replacing the existing ones. I'll bootstrap these officially later, but you can test them out whenever.
`mame2003-plus/saves/nvram/`
[saves.zip](https://github.com/libretro/mame2003-plus-libretro/files/11897391/saves.zip)

**Comment by ZacharyFoxx** [comment]
> Here's both umk3 nv files to replace your existing ones. Just unzip and drop them in your save folder replacing the existing ones. I'll bootstrap these officially later, but you can test them out whenever. `mame2003-plus/saves/nvram/` [saves.zip](https://github.com/libretro/mame2003-plus-libretro/files/11897391/saves.zip)

My apologies.

I opened the issue without realizing that it is a glitch that affects the original hardware itself.

This solution worked, but it really is up to you to implement it, since the problem may appear.

I want to thank everyone for the effort and improvements that have been made to the core.

Thank you very much.

**Comment by barbudreadmon** [comment]
>This is actually a glitch on real hardware

@mahoneyt944 Do you have a pcb video showing this ? Or any other kind of material confirming it's happening on real hardware ?

I found 2 references to this glitch : 
* https://www.mksecrets.net/umk3/eng/umk3-glitches.php which says "Not for Arcade".
* https://mametesters.org/view.php?id=691 which says it's a MAME bug that was fixed in 0.122u5

Isn't it simply an issue inherent to the old MAME midway video code that was kept in MAME2003+ for performance reason ?

**Comment by mahoneyt944** [comment]
I don't have real hardware to confirm just the notes and documentation by those who have studied the code. Even in current mame they use the same hack that we do here to delay the CPU.... Which isn't full proof, but seems to work most of the time.

**Comment by mahoneyt944** [comment]
@barbudreadmon if you scroll up there's a more in-depth description that Aaron Giles wrote, which I copied here, in a blog or something years ago.

**Comment by arcadez2003** [comment]
Nothing is 100% when it comes to emulation but hey ho considering how big studios tend to release their games 
in a 25% working state nowadays we're likely still doin considerably better here :)

But as i always say if users are not happy they'll vote with their feet and choose another arcade core if unhappy with
how one of their faves works when using this one, as of yet many have decided to stick with us factoring in game performance vs bona fida emulation

**Comment by arcadez2003** [comment]
> > This is actually a glitch on real hardware
> 
> @mahoneyt944 Do you have a pcb video showing this ? Or any other kind of material confirming it's happening on real hardware ?
> 
> I found 2 references to this glitch :
> 
>     * https://www.mksecrets.net/umk3/eng/umk3-glitches.php which says "Not for Arcade".
> 
>     * https://mametesters.org/view.php?id=691 which says it's a MAME bug that was fixed in 0.122u5
> 
> 
> Isn't it simply an issue inherent to the old MAME midway video code that was kept in MAME2003+ for performance reason ?

I already backported the fix but from memory i was told it caused some other issues so we reverted it the usual rob
peter to pay paul scenario when lifting code from later versions of MAME you fix something but break something else :)
https://github.com/libretro/mame2003-plus-libretro/commit/bd649fd45b392228bb3fedea38542a1c6a397154

**Comment by barbudreadmon** [comment]
>if you scroll up there's a more in-depth description that Aaron Giles wrote

Thanks, that was a good read.
It seems to be indeed a bug within the game's code, with no incidence on real hardware due to tms34010’s cache.

It appears the fix introduced in https://github.com/mamedev/mame/commit/c846ce37d998dde405f6ccf9d6f1234326f3cbab was more of a workaround, and was later replaced by tms34010 cache emulation.

@arcadez2003 I agree it's better left as-is if it's gonna cause other issues and/or performance regression in MAME2003+. I just wanted to confirm whether it was supposed to happen or not since i couldn't reproduce it on FBNeo.

**Comment by mahoneyt944** [comment]
https://github.com/libretro/mame2003-plus-libretro/commit/e0f4c66ec4f11f21c1d1607a569e656d6f358137 fixes bootstrap to avoid this issue from being the default. proper cache emulation could further improve this, but good as we get for now.
