### ISSUE TITLE
Darkstalkers: The Night Warriors (USA 940818) character select screen glitches out a little. 

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/mame2003-plus-libretro#1612]
I have not played the game at this time past the character select screen i'm just downloading some games to play later this week and seen this bug.

![1](https://github.com/libretro/mame2003-plus-libretro/assets/21169038/58a6b42e-fec8-429c-8a3f-493aed756f26)

**Comment by arcadez2003** [comment]
Minor stuff isn't it

**Comment by Cibomatto2002** [comment]
it is Minor just pointed it out because that was the only thing that I seen that was wrong. Do. Do I need to close this then?

**Comment by arcadez2003** [comment]
Sure we appreciate the heads up i did check the MAME WIP for this game looking for a fix which mentioned this issue
directly but alas there are none, and since there have been many changes to the CPS2 video code over the years pinning
down which of said changes fixes the issue you mentioned it would be kinda like looking for a needle in a 100 haystacks.

But certainly feel free to leave this open for now even if it's closed it will remain on record should someone feel like 
looking into this again sometime down the road.

**Comment by mahoneyt944** [comment]
I don't think so.

**Comment by mahoneyt944** [comment]
I'm not very diverse on these, I was under the impression libretro-super was being phased out? Core options were also wrongly set, but didn't seem to hurt. What do you think it should be?

**Comment by mahoneyt944** [comment]
What about using serialized vs basic?

**Comment by mahoneyt944** [comment]
I'll look into it. Im assuming these features are more so hidden when set to a lower level but possibly still accessible through the menu still if you know where to look. I'll reach out and see what they suggest for us here.

**Comment by arcadez2003** [comment]
> what is the issues with varth?

0.124u4: Fixed layer enable at the end of stage 4 in Varth.

Now this comes as part of a huge change after earlier big changes, i've never got as far as level 4 so i cannot
confirm whether there is a problem with Varth in our core or it was confined to later builds before being fixed.

I remember the Coinops dev mentioning he'd backported the fix so i assume we'd need it but due to xbox scene
drama he sometimes tried to send me down the wrong road codewise by claiming he'd fixed this that or the other
hoping i'd try to do likewise so might be one of those type deals i'll have to play the game up till the end of level 4 
to find out either way :)

**Comment by Cibomatto2002** [comment]
Thank you !!

**Comment by arcadez2003** [comment]
> its not the easiest of games if cheats are available ill try play it up to level 4. I get the feeling the cpu might be enough to fix it could be wrong though. Its a pretty big update for one game.
> 
> edit played it through with the cheats (in the metadata folder) seems fine to me comparing it you a you tube video. Just the cpu speed needs upped. Must have been the newer code that needed a tweek.

Yeah some titles will need switched as per their boardtypes i meant to do this some years back but obviously i slacked off :)

**Comment by arcadez2003** [comment]
Ok as per the latest MAME CPS1 driver im updating ours to reflect the later findings regarding the correct clock speeds for certain games i'll plod way at this over the next day or so, what's slowing me down is set name changes and or newer dumps
which means i have to double check the main cpu roms to know what versions we have.

**Comment by arcadez2003** [comment]
What were the objections again i cant remember.?? maybe it was romsets as you'd be removing XOR's right.??

**Comment by arcadez2003** [comment]
Hmm well sure 100's of romsets will need to change but we've never shied away from updating romsets to better 
improve the emulation before have we.??  hell users have come to expect that when it comes to this core. maybe timeto start a thread on this with the pros and cons ya know.

**Comment by Cibomatto2002** [comment]
Just wondered if cps3 will ever be added ? Would like to play Street Fighter III if not it's ok.

**Comment by Cibomatto2002** [comment]
I thought it would be to much to ask all this talk about CPS got me thinking about that game. Thanks for your time.

**Comment by arcadez2003** [comment]
> I think we would need to so a soundcore for that. Its a lot of work for this core even cpu cores are a nightmare to do. Things like that would be more suited to a higher core that also has address spaces. Its a pitty we are not at 079 at lease so much more would be doable. Maybe someone else would be willing though. I can only speak for myself though.

Well apart from the workload we have to factor in the performance using the Xbox as a benchmark which tends to be in
the same ballpark as many of the devices this core is aimed at the CPS3 games preform terribly so even if we did the graft
not many would see the benefits as these games would be too slow to be enjoyable.

Now there was a standalone CPS3 emulator chock full of speedups available for the Xbox and the games played lovely
using it but alas there was no source code ever released for it otherwise it would likely have found it's way onto the 
libretro platform already solving the problem of how to play CPS3 games on lower spec hardware

**Comment by Cibomatto2002** [comment]
I don't have a Xbox just wondering how good does Final Burn Alpha 2012 run on it? I see it has cps3

**Comment by arcadez2003** [comment]
> I don't have a Xbox just wondering how good does Final Burn Alpha 2012 run on it? I see it has cps3

Well the standard xbox only has 64mb of memory so the console cannot boot CPS3 games using FBA however some 
users choose to upgrade the capacity to 128mb for reasons which escape me but as a result their consoles could boot
the games but folks said they played too slow as the console simply didn't have the power under the hood to run em.

Sidenote iq_132 once had those games running using FBA on a standard xbox with speedups and the games were more 
or less there barring when the special moves were used then they'd slow down again he planned to tweak the code to 
sort that when he found the time but alas he lost the source code and it wasn't to be.

There ya go all the history of CPS3 emulation on the xbox whether you wanted to know about it or not :)

**Comment by Cibomatto2002** [comment]
Thanks interresting read.

**Comment by arcadez2003** [comment]
Aye as Roy Castle once said "dedication is what ya need" good job
