### ISSUE TITLE
fbneo dev hinting on licence violation

### ISSUE THREAD

**Issue by grant2258** [libretro/mame2003-plus-libretro#1654]
@mahoneyt944 there is a subject here https://github.com/finalburnneo/FBNeo/issues/1513 mentioning issues with flac being gpl and we are using it. As you know the core had a full audit after the kungfu master 2 fiasco.

I cant help but feel this dev is constantly digging at this core at every opportunity. Stallman himself has clarified that  simple headers dont make a derivative work. Have a look into this and let me know if its an issue we can just remove the flac support without the drama. I didnt see any violation going through the files at the time and neither did the libretro after the  kung fu 2 issue. It not something I feel strongly about and the wav support will always be there anyway. So ill leave it in your hands and remove if necessary just let me know not too fussed either way. 

here is  stallmans reference https://lkml.iu.edu/hypermail/linux/kernel/0301.1/0362.html. 

https://github.com/libretro/mame2003-plus-libretro/blob/master/src/libretro-deps/libFLAC/include/FLAC/all.h
is the only head we are using so we arent touch anything outwith the mit licensed part of the library. 

@KMFDManic just updating you on this as well in case you have any issues due to this kind of narrative.

**Comment by mahoneyt944** [comment]
I don't personally see a violation in the licensing so I don't think we'll take any action at this time. Of course if the original licensing owner feels otherwise we would surely reconsider and work with them to rectify the situation.

**Comment by grant2258** [comment]
@mahoneyt944 the site mentions the library is released as mit and can be used commercially only some parts are gpl. We dont use or compile any parts of the code.

```
The reference implementation libraries are licensed under the New [BSD License](https://github.com/xiph/flac/blob/master/COPYING.Xiph). In simple terms, these libraries may be used by any application, Open or proprietary, linked or incorporated in whole, so long as acknowledgement is made to Xiph.org Foundation when using the source code in whole or in derived works. The Xiph License is free enough that the libraries have been used in commercial products to implement FLAC, including in the firmware of hardware devices where other Open Source licenses can be problematic. In the source code these libraries are called libFLAC and libFLAC++.

The rest of the software that the FLAC project provides is licensed under the [GNU General Public License](http://www.gnu.org/licenses/licenses.html#GPL) (GPL). This software includes various utilities for converting files to and from FLAC format, plugins for audio players, et cetera. In general, the GPL allows redistribution as long as derived works are also made available in source code form according to compatible terms.
```

We are not using any of the utilities

**Comment by LibretroAdmin** [comment]
@grant2258 I have received many complaints over the past few months regarding back and forth behavior between you and HaploCalypse. Personally I feel this arguing is completely pointless and not only are there no real license violations, this is just arguing how many angels can stand on the head of a pin. Instead, what seems to be going on is some kind of personal slight and arguments and theories being weaponized to try to 'get back' at them. This personal antagonism against Haplocalypse and other fbneo devs has got to stop. Please don't do this anymore, none of this drama and these personal slights and beefs helps the emulation scene in any way.

Let us just get back to doing retro emulation coding instead of arguing over pointless things like this. Personal arguments should not further devolve into pointless arguments where we try to 'own' someone with some slight technicality that doesn't even matter.
