### ISSUE TITLE
Question: San Francisco Rush: The Rock

### ISSUE THREAD

**Issue by PeteHaughie** [libretro/mame2003-plus-libretro#1667]
I'm wondering if there's a known way of getting San Francisco Rush working with Mame 2003 Plus?

I can see it in `/src/drivers/seattle.c` and it does have a method:

```c
static DRIVER_INIT( sfrush )
{
	cage_init(REGION_USER2, 0x5236);
	init_common(MIDWAY_IOASIC_STANDARD, 315/* no alternates */, 100);

	/* set up the analog inputs */
	install_mem_read32_handler(0, 0xb4000000, 0xb4000003, analog_port_r);
	install_mem_write32_handler(0, 0xb4000000, 0xb4000003, analog_port_w);

	/* speedups */
	install_mem_read32_handler(0, 0x8012498c, 0x8012498f, generic_speedup_r);
	generic_speedup = &rambase[0x12498c/4];
	install_mem_read32_handler(0, 0x80120000, 0x80120003, generic_speedup2_r);
	generic_speedup2 = &rambase[0x120000/4];
}
```

But it's marked as `GAME_NOT_WORKING`:

```c
GAMEX( 1996, sfrush,   0,        flagstaff,  sfrush,   sfrush,   ROT0, "Atari Games",  "San Francisco Rush", GAME_NOT_WORKING )
```

Which is the same as the historic mame repo.

Is this due to some weirdness in the hardware or just that nobody has gotten round to looking at it?

**Comment by arcadez2003** [comment]
From the MAME WIP........

14th May 2004: Aaron Giles - The ethernet controller was the missing link in San Francisco Rush, which is now playable (if you have a 20 GHz computer, of course). Unfortunately, there still seems to be something wrong with San Francisco Rush: The Rock, but hopefully I'll have it figured out. On the plus side, it turns out that a missing ethernet controller was also the cause of Vapor TRX not working as well, so now that is playable. By the way, a number of people were wondering why the Vapor TRX CHD is so big. Well, it turns out that the entire attract mode is pre-rendered movies, which explains a lot!

11th May 2004: Aaron Giles - Decided to take a breather from core work and got San Francisco Rush: The Rock up and running. It has the same problems as the original San Francisco Rush in that it hangs at the start of the game, but now I finally have a theory for why. The Rush games included an Ethernet controller onboard, and I'm currently suspicious that they want it to work. I've got some rudimentary basics up and running, and they are detecting that there is no cable connected, and then putting the Ethernet controller into loopback mode. Which tends to reinforce my suspicion that their networking model relies on even local data being sent/received in loopback mode. We'll see once I get everything wired up!
8th May 2004: Aaron Giles - A San Francisco Rush: The Rock hard drive showed up and I've got it limping along a bit, but there are still some serious issues to solve before it's ready.

When it comes to MAME2003+ There would be some graft required to backport the changes above, at the end of
the day it'll all come down to whether anyone is interested in taking this on.

**Comment by mahoneyt944** [comment]
I think the Ethernet hookup would be quite difficult to hookup here....But I've only looked at it briefly. If I had the commit diff to compare that might help determine the actual workload.

**Comment by grant2258** [comment]
https://github.com/mamedev/historic-mame/commit/683b199d73bf3f692d7fddf24ab6d45ba51544bf#diff-967cf7678c84ae9988dac21e20abcdc454052c2909d5603c3742e08c092c6485 (mame083) Not a large workload but thats for San Francisco Rush though would need to look more into when San Francisco Rush:The rock is fixed.

**Comment by arcadez2003** [comment]
it's still listed as not working in current MAME but i dunno if it's bootable and playable to an extent.??

**Comment by arcadez2003** [comment]
Alright gonna take a run at this
