### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by arcadez2003** [libretro/mame2003-plus-libretro#1680]
I was tagged as per this commit so is it worth adding this or not..??
https://github.com/libretro/FBNeo/commit/e38f02fd78fc5081a92597598ebbd8d3686f2179#commitcomment-138315803

**Comment by grant2258** [comment]
I searched the text of the document. I dint see any reference to the word derivative in a search of the text unless im looking at the wrong document https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32009L0024 . I would point to the place(s) to the article number and index  that supports the claim that below rather than just the document itself. If you agree with his assessment of the article its up to you. 

```
Linking two programs or linking an existing software with your own work does not produce a derivative or extend the coverage of the linked software licence to your own work
```
If you feel you want to stand up for there corner libretro and they are ok with the wording of if. I would say go for it. 

Me personally I commit to the repo cause its here and don't have any reason make a stand for libretro reasons to distribute, mix software licensing, or consolidate it all or as im not a lawyer.  If the core got taken away I would port it to sdl for low end users at the end of the day anyway to me retroarch convenient no essential to the existence of the core. If its not longer convenient time to move along in another form that doesn't rub the wrong way it just not worth the hassle.

**Comment by mahoneyt944** [comment]
I don't see much point in adding that here, currently anyway.

**Comment by arcadez2003** [comment]
Alright then let's close this down then.
