### ISSUE TITLE
Centipede and Millipede seem to have stopped working

### ISSUE THREAD

**Issue by retrogamedesigner** [libretro/mame2003-plus-libretro#1822]
I have checked the current xml for the core, and the files and their hashes all match. I'm specifically using centiped.zip and milliped.zip, which have previously worked (though it's been a while since I've played either).

**Comment by mahoneyt944** [comment]
Both work for me, what platform are you using? Have you tried to delete your cfg files and retest?

**Comment by retrogamedesigner** [comment]
I've tried a Windows 11 PC and another PC running Linux Mint. I'll try deleting the cfg files retesting.

**Comment by retrogamedesigner** [comment]
No luck on either.

**Comment by retrogamedesigner** [comment]
Oddly, both are working just fine on my Android-based Odin 2.

**Comment by mahoneyt944** [comment]
Is it the same malloc line or somewhere else in the code?

**Comment by mahoneyt944** [comment]
@zorro2055 seems there may be another issue with x-way changes.

**Comment by zorro2055** [comment]
Ah, I'll take a look.  I won't be back at my place though until tomorrow, so I'll look at it then or more likely Friday.

**Comment by zorro2055** [comment]
Sigh, I verified that Centipede and Millipede worked just before my PR, https://github.com/libretro/mame2003-plus-libretro/pull/1652, was merged.  I'll look closely at the code to make sure the right amount of memory (due to Dial ports using more memory) is being malloc'd for the ports, and fix it.

**Comment by mahoneyt944** [comment]
Check around ipt_extension. Just a guess

**Comment by grant2258** [comment]
@zorro2055 it not necessarily the malloc after your fix.  The loops that reads inputs rely on normal input or analog input and that could be throwing the loops regarding the inputs padded a specific way. I havent really looked into it a lot just traced where its happening. These are minor things that updates do anyway something small turns into a rabbit hole.

**Comment by zorro2055** [comment]
Thanks for that info y'all.

I just submitted a draft PR which runs Centipede, Millipede and Pole Position 1 and 2.  I want to check in areas where IPT_EXTENSION is to see if I need to handle IPT_EXTENSION_II (which was my added third line from before) at those locations.

Here is an explanation of what I found in a nutshell.  Due to the more compact nature of defining PORT_ANALOG and PORT_ANALOGX, all analog ports have 3 "lines" even though the last line is only used by IPT_DIAL and IPT_DIAL_V.  So I just had to set all analog ports to allocate 3 "lines".

More detailed explanation:
First, an input port can consist of 1 to 3 struct InputPort variables or what I'll refer to as "lines".
InputPort for reference:
https://github.com/libretro/mame2003-plus-libretro/blob/8ed99f0665e8b14ed0f804fe4ed50d27dcb2fe5b/src/inptport.h#L28-L36
A non analog port has 1 "line" and its type is some non analog type, etc, etc.
A analog port before my PR from before has 2 "lines".  Line 1 type is IPT_DIAL, etc, etc.  Line 2 type is IPT_EXTENSION meaning an extension of the 1st port line.
My PR from before gives analog ports 3 "lines".  Line 1 type is IPT_DIAL, etc, etc.  Line 2 type is IPT_EXTENSION, and Line 3 type is IPT_EXTENSION_II (Just changed to this in PR shown above, was NULL).

You can see from definition of PORT_ANALOG and PORT_ANALOGX, both now have the 3 lines defined.  It was this way since my first PR to avoid having to add new definitions.  Of course, only the analog port types IPT_DIAL and IPT_DIAL_V actually use the 3 "line".  So still the same behavior where the X-Way option only comes up for IPT_DIAL and IPT_DIAL_V types, and is only checked for in the game logic for IPT_DIAL and IPT_DIAL_V types.

PORT_ANALOG for reference:
https://github.com/libretro/mame2003-plus-libretro/blob/8ed99f0665e8b14ed0f804fe4ed50d27dcb2fe5b/src/inptport.h#L221-L225
second line defines the first "line" (struct InputPort variable)
third line defines the second "line"
fourth line defines the third "line"

PORT_ANALOGX for reference:
https://github.com/libretro/mame2003-plus-libretro/blob/8ed99f0665e8b14ed0f804fe4ed50d27dcb2fe5b/src/inptport.h#L228-L234
third line defines the first "line" (struct InputPort variable)
fourth line defines the second "line"
fifth line defines the third "line"

Hopefully, that makes sense.  Let me know if there are comments or questions.  Like I said, I'm going to look at where IPT_EXTENSION is used in logic to see if I need to handle IPT_EXTENSION_II there as well to try to avoid any bugs that might still be lurking.  I'll update the PR when I get that done.

**Comment by mahoneyt944** [comment]
This should fix it for now https://github.com/libretro/mame2003-plus-libretro/commit/cbfdd3cfacb2de7c71fe651e79851d024d92001e

**Comment by mahoneyt944** [comment]
@retrogamedesigner please retry with the latest build

**Comment by retrogamedesigner** [comment]
Confirmed, Millipede and Centipede are both working for me now on all my systems.

**Comment by grant2258** [comment]
thunder blade has issue now.  The offsets must be thrown off.  tested on commit 555c824944cb5187f4dd5a53a33041e9cec0ae91 and cleared the inputs.


![image](https://github.com/user-attachments/assets/bea72035-8ccb-4471-abd0-9d070823e993)

**Comment by mahoneyt944** [comment]
Retest with the current master. We changed stuff around again. Hopefully fixing everything. Might need to clear cfgs though.

**Comment by grant2258** [comment]
I look through the commits the header update didnt trigger the inptport.c to recompile is fine now its recompiled.

**Comment by mahoneyt944** [comment]
Thank goodness, 😂
