### ISSUE TITLE
mame2010 gunsights possible in 2003 ?

### ISSUE THREAD

**Issue by ghost** [libretro/mame2003-plus-libretro#256]
At the moment for gun games etc. we have 2 white plus signs and player 2's sight always stays on the screen even when playing 1 player and cannot differentiate who's who. I know you can manually move it off the screen. In Mame2010 there are 2 different coloured sights and if you don't move it for a few seconds it disappears. This is good if you're playing 1 player as player 2's sight will disappear.

**Comment by markwkidd** [comment]
There are some vaguely hacky ways I can imagine approaching this via the libreto frontend which would require toggling a setting in the Controls menu for which players have lightgun sights on and off, rather than all on or all off right now.

If it isn't practical to implement this any other way than via the core options and controls I'll be willing to look into doing it that way.

Hopefully one of the other folks here has experience with the lighgun sight code and may have a "cleaner" idea.

**Comment by grant2258** [comment]
never used lightgun in mame mainly because i dont have one!

**Comment by SaucySarah** [comment]
Gun games are great when using a mouse ! Even games that use a spinner (like Midnight Resistance) you can use a mouse to rotate the gun and use the joypad to control the player, like a hybrid type of wiimote !

**Comment by grant2258** [comment]
I really like  how the amiga done midnight resistance controls. I also loved the music in the game too! Was one of my favs back in the day only played it on the amiga originally though

**Comment by arcadez** [comment]
I dont have a light gun so i always prefered Final Burn Alpha for these games, although the supported games for this genre are less in FBA IMO the crosshair layout is better plus they do disappear from view when not used.

But i suppose in theory it would be possible to backport the newer style gunsights from later
MAME it'll all depend apon if the code for this is compatable with this older core.

**Comment by mahoneyt944** [comment]
#1225 handling this issue now.
