### ISSUE TITLE
Chatroom for MAME2003-plus

### ISSUE THREAD

**Issue by arcadez** [libretro/mame2003-plus-libretro#267]
Should we setup a chatroom..?? and that way dev's and users can talk easier in realtime
which will help to stop this git and forum threads getting clogged up with so many posts

maybe IRCNET #mame2003-plus or create a discord channel

**Comment by grant2258** [comment]
well we need input from users on the forums for the control issues. 

I dont check all the threads on the forums unless someone sends a notice with my name I do check issues in here. I you dont want people to talk about issues on here fair enough we will encourage them to talk in the forums instead of here thats not really a problem

**Comment by arcadez** [comment]
TBH it was just a thought as some folks were stating a chatroom would be easier for comms
anyway feel free to do what ya's want.

**Comment by Wilstorm** [comment]
I am would be ok with whatever you guys decide if it helps with the flow a bit better. To be completely honest Dan and I don't really see eye to eye and after our last "skirmish" I have a feeling we never will based on some of his comments so I am more comfortable here. That's why I spend any free time I have here mostly but I am most definitely open to whatever ideas might work better.
