### ISSUE TITLE
TODO: Re-implement and improve "Dual Joysticks"

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#278]
Bear in mind that the entire "Dual Joystick" feature is a workaround because the RetroArch frontend does not yet provide a way to map two real input devices to one RetroPad.

There is at least one improvement to what we have now which is straightforward to implement, which is only displaying the existing "Dual Joysticks" option -- and only apply it -- to games which had those controls.

If it doesn't seem like RetroArch is going to implement this into its remapper anytime soon, it Dual Joysticks should probably be re-implemented as a RetroPad subtype. But even if it stays a core option long term, it should be reimplemented "on the libretro side" of the input system. In other words Dual Joysticks should rewrite the input from two RetroPads to be one RetroPad before the input is sent to the MAME input system.

My current very clever approach remaps it automatically within MAME but that is no good for netplay consistency.

**Comment by markwkidd** [comment]
> There is at least one improvement to what we have now which is straightforward to implement, which is only displaying the existing "Dual Joysticks" option -- and only apply it -- to games which had those controls.

This objective is accomplished with https://github.com/libretro/mame2003-plus-libretro/pull/293

**Comment by Loggahead** [comment]
I noticed that the Dual Joysticks option only shows up in the quick menu for games that use 2 joysticks but I noticed that when I enable that setting for a game like Robotron it appears to be applying it to all games even if they don't utilize 2 sticks for player one.  For example, if I have this turned on in the menu for Robotron and quit our and launch TMNT, player 2's joystick doesn't work for player 2.  If I go back to Robotron, disable that feature, and then go back to TMNT, all works as normal again.

**Comment by grant2258** [comment]
that happened to me a while back with sf2 not checked on the latest source though.

I think the code is just showing the option for games it should be maybe and thats the correct behavior.   

The problem with a system like this is that these options should be disabled if the flags dont match as well im sure mark will fix this. I think there should also be some checking on the OPT_RSTICK_BTNS and dual joysticks so both cant be on.

I dont use retroarch or retropie much anymore since changing my setup for my barcade but will try help with any code that thats none input related.

**Comment by markwkidd** [comment]
I tried to make the settings only apply when they're relevant, in addition
to only being visible when enabled, but I must have a bug

**Comment by grant2258** [comment]
I'll double check it I'll need to slip the pi in in the barcade though will try after work.
