### ISSUE TITLE
Unable to access TAB input controls with mame_keyboard or simultaneous selected

### ISSUE THREAD

**Issue by Wilstorm** [libretro/mame2003-plus-libretro#291]
I thought I saw this in another open issue but I couldn't find it. I updated from source this morning and when I have ```mame_keyboard``` or ```simultaneous``` selected I can't access the controls for ```Input (General)``` or ```Input (this game)``` in the TAB menu. The TAB menu does come up fine but the menu options are not available.

So basically whatever input configuration was in the file before works fine but I can't make any additional new changes.

**Comment by robertvb83** [comment]
@Wilstorm the input options in the mame menu are deactivated because @markwkidd implemented the new control system where everything can now be done via retroarch RGUI --> quick menu --> controls
However there is a core option to toggle the mame tab menu controls back on. Look in RGUI --> quick menu --> options at the very bottom

**Comment by Wilstorm** [comment]
@robertvb83 - Thank you, I did find it down there, missed it the first few times. :)
