### ISSUE TITLE
just tried afterburner and outrun the analog controls arent working

### ISSUE THREAD

**Issue by grant2258** [libretro/mame2003-plus-libretro#314]
something is a miss with the xbox360 pad analogue stick controls arent working at all only the digital pad. Is this something to do with the retropad definitions ?

**Comment by Wilstorm** [comment]
@grant2258 - I just tested both games on a Pi 3 with a XBOX 360 controller with a wireless dongle and they seem to work good here.

**Comment by grant2258** [comment]
tries on windows and retropie with a abox one and xbox 360 no go. The only way to get it to work is   to pick set user1  analogue to digital type to left and that doesnt give you analog. It works fine in mame2003

![controls](https://user-images.githubusercontent.com/6128601/43170590-cc58b81a-8f9d-11e8-979c-5d17059e1332.png)

**Comment by Wilstorm** [comment]
@grant2258 - Ah ok, I am using an older version of Retroarch (1.7.1) is probably why it works fine here. 

Something kind of strange is the controls are more responsive in 2003 vs. Plus, also I can do an easy barrel roll in 2003 but I can't do that in Plus. It works fine otherwise and I can fly up/down and sharp turn left/right to avoid incoming missiles but no barrel rolling. Not enough G's. ;)

**Comment by grant2258** [comment]
1.7,1 will have the left analog option if its on you wont be getting analog anyway it will just be treating your analog as digital

**Comment by Wilstorm** [comment]
@grant2258 - I didn't feel like it was to "jerky" driving in Outrun. I drove it to the first check point using the left analog stick and it felt ok. When I play the port created in Retropie that has analog support it feels similar with sensitivity settings 1 through 10 via joystick not to much "drift" as some driving games seem. Is there a way to know for sure if it is the left analog stick working as digital or analog then I can give you a confirmed answer? Right now you have no joystick support in Plus running the latest Retroarch?

**Comment by grant2258** [comment]
@Wilstorm the only way mame2003+ works with analog the analog stick is for me to set the option 

user1 analogue to digital type to left

this basically treats the analog stick so it reads like a digital.

it should be clear if your analog is working properly moving the analog slightly should turn the turn slightly. its not an off off like  a button

**Comment by grant2258** [comment]
nm found the problem a pull req is in for the fix

**Comment by Wilstorm** [comment]
@grant2258 - Thanks for the F2 tip! I never knew of a good way to confirm analog so this is great! Using an actual arcade joystick (on my panel) with Outrun is just unplayable but the left analog stick on a joystick just feels a bit more playable to me. I am not sure why. I can actually get to checkpoints without much issue on a joystick. That's just not possible with a real arcade stick because of the digital input you're over-driving to compensate. Does the F2 tip work in After Burner too by chance?

**Comment by grant2258** [comment]
never  checked after burner its should have a service mode too ill let you know. Right now the code is broke on 2003+ until the fix is pulled in its probably best to use mame2003 if you want to play analog games
