### ISSUE TITLE
[CPS2+others] games not working

### ISSUE THREAD

**Issue by nemo93** [libretro/mame2003-plus-libretro#345]
I'm using a Pi3b+ along with Retropie 4.4.2 with a fresh mame2003+ compiled in. I'm using romset generated from this very same mame2003+ version.

I got several games that don't launch or with issues (gfx/sound). Most are CPS2. 

1. alexkidd.zip. Does launch however goes to black screen, you can hear a voice over and that's all. I don't see any clone that can be used. Please keep me honest. Works fine on .139
2. 19xx/1944 both don't launch. They do with a standard 0.78 or .139. I do see some missing roms in the .78+ romset. Eg. for 19xx.zip the roms 19xux.03 > .06 are not there. They are with 0.78.
3. Alien vs Predator (avsp.zip). Same as #2.
4. Armored Warrior (armwar.zip). Same as #2.
5. Commando (commando.zip). Launching but if you press any button during the disclaimer it will go I guess in an upside down service menu and you're stuck there. works fine on .139.
6. progear.zip. Same as #2. I just can't get this one to work even with .139.
7. Killing Blade (killbld.zip). Doesn't launch either with a rom from 0.78 or .78+.

I'll update the list. If I do anything wrong tell me. Same if you need better/further details about my setup. Thank you.

**Comment by arcadez** [comment]
Alotta your problems are using an incorrect rom or trying to boot a version of game which 
is not playable in this core eg Alex Kidd fir example....

GAMEX(1986, alexkidd, 0,        alexkidd, alexkidd, alexkidd, ROT0,   "Sega",    "Alex Kidd: The Lost Stars (set 1)", GAME_NOT_WORKING )
GAME( 1986, alexkida, alexkidd, alexkidd, alexkidd, alexkidd, ROT0,   "Sega",    "Alex Kidd: The Lost Stars (set 2)" )

Go into the CPS2 driver in this Source check the bottom of it to see what versions are actually
playable in MAME78 not all of them are due to not being decrypted and forget MAME139 roms
for the CPS2 games they will not be compatable.

As for commando known issue in older MAME and in FBA funny enough you dont dont press
any buttons before you see the title screen and it'll work fine.

**Comment by nemo93** [comment]
Ok makes sense. Thanks for the great details as well, much appreciated. I'm closing that one now after renaming it.
