### ISSUE TITLE
[Umk3] weird colour at difficulty selection screen

### ISSUE THREAD

**Issue by nemo93** [libretro/mame2003-plus-libretro#358]
umk3.zip // romset from .78 // .78+ and .139.

After picking up a character you go to the difficulty select screen where you have different "towers". Actually those towers are rendered with weird colours. I tested the game on mame-2010 on the pi and colours are fine however game is runnning too slow. 

It's definintely not a game breaking bug so I would understand if you decide to not give it a look. It's just a feedback. I didn't test long so I can't say if there are other gfx issues later in the game.

Thank you.

**Comment by markwkidd** [comment]
Just for informational purposes, the fix appears to be made in MAME 0.122u5

>0.122u5: Aaron Giles fixed character selection screen in clone Ultimate Mortal Kombat 3.

**Comment by voodoo84** [comment]
Here are the technical details of the fix:

https://testyourmight.com/threads/mame-dev-aaron-giles-on-umk3-palette-bug.19837/

The bug appears more often when you unlock all three hidden characters.

I don't know if this is also related to the flickering/disappearing shadows bug in MK2/MK3, but that's also fixed at some point before MAME 2010 (0.139). It would be great if MK games finally get to work for good without obvious graphical glitches in MAME 2003 Plus.

**Comment by arcadez2003** [comment]
@voodoo84 @markwkidd Just noticed this now as far as im aware the shadows in MK2 and MK3 were fixed in 2002.....

31st March 2002: Aaron Giles fixed the shadows in Mortal Kombat 2 and 3.

There are no other fixes related to the shadows that i can see in the MAME WIP after the above, as for the pallette bug
i've backported the fix for this from MAME122.u5 however some testing will be required for UMKIII to make sure there
is no performance hit.

**Comment by arcadez2003** [comment]
https://github.com/libretro/mame2003-plus-libretro/commit/bd649fd45b392228bb3fedea38542a1c6a397154
