### ISSUE TITLE
fix menu ui button on retropad

### ISSUE THREAD

**Issue by grant2258** [libretro/mame2003-plus-libretro#437]
@markwkidd  This one needs addressed im not sure what your expected behavior here is but the only buttons that make any sense are L3 and R3 for consistency(people often forget about these button under the analog controllers. 

Button 8 works for all controllers properly accept RETRO_DEVICE_JOYPAD this uses button R2 as button 6 so you cant use this(sf2 uses button6)  . L2 changes as well so thats a no go. 

you could argue some controllers dont have a l3 and r3 bit some controllers dont have a l2 ad r2.  

thoughts?

**Comment by markwkidd** [comment]
I have a more wild idea -- let there not be a default mapping for the retropad.

If someone wants to assign it to a button they can do so on a permanent or temporary basis via the frontend, but for casual users the MAME menu is already available via a core option so it doesn't even need to be mapped for someone to tweak an occasional Dip Switch.

Too radical?

**Comment by grant2258** [comment]
youll null the work you done on making the controllers work and mame buttons changing in remaps might bring the tab menu up ect. You basically go back to mame2003 and loose you button mapping name for games unless im miss understanding you which is a good possibility

**Comment by markwkidd** [comment]
It sounds like the two immediate alternatives are:
* come up with a best guess mapping for each of the layouts, knowing that it might move around
* not have a default mapping, and let the users set one of their preference in the frontend 

What I would really like to do is go farther with the MAME menu core option to make needing a button mapped obsolete. My dream:
* Get into the MAME Menu by turning on the core option
* Exit the MAME Menu via the MAME menu itself instead of having to go back and turn off the core option

I was close to having that functionality finished back in June with the core option overhaul. I probably just need a few hours to make that a reality, even if just for my own satisfaction...

**Comment by markwkidd** [comment]
As someone who uses a SNES controller with this core when I do play it, maybe I just don't relate to wanting to get in and out of that menu very often hehe

**Comment by grant2258** [comment]
to be honest mark no one uses the l3 buttons if it becomes an issue we can deal with it. I dont see many people reaching for it now with layouts that will work for most

**Comment by markwkidd** [comment]
OK, I'm agreed on L3. Can you send a PR?

**Comment by grant2258** [comment]
its already done

**Comment by grant2258** [comment]
https://github.com/libretro/mame2003-plus-libretro/pull/450

**Comment by markwkidd** [comment]
lol. well, I am getting caught up after all. can this issue be closed?
