### ISSUE TITLE
Request: Asteroids sounds implementation

### ISSUE THREAD

**Issue by UDb23** [libretro/mame2003-plus-libretro#453]
Asteroids discrete sounds were significantly improved in version 125 and 141 of Mame. Info [here.](http://www.progettoemma.net/?gioco=Asteroid)
Is mame2003-plus already integrating those enhancements ? If not would it be possible ?

**Comment by arcadez** [comment]
Might be doable it might not be depending on the code, the discrete soundcore has had many
rewrites over the years, our one is very old i'll take a look sometime.

There are a few changes directly linked to Asteroids as far as i can tell...........

0.141u2: Derrick Renaud fixed broken discrete sound in Asteroids.

^^ might be related to change below.??

0.140u1: Derrick Renaud optimized speed of DISCRETE_DAC_R1.

0.125u4: Discrete sound update [Couriersud]: Added NODE_RELATIVE(NODE, offset) macro to discrete.h. Fixed driver to use this macro instead of adding directly to the node. This fixes abnormal discrete sounds.

0.102: Hans Andersson and Derrick Renaud updated the discrete thump sound in Asteroids to use component values instead of derived equations.

**Comment by arcadez** [comment]
Ok after a quick check the code will not be compatable unless the discrete soundcore is updated
and if so every driver using it would need updated as well safe to say im not prepaired to undertake
a task so large.

**Comment by UDb23** [comment]
Understood. Thanks for checking.
