### ISSUE TITLE
todo: test to see if hiscore support works in brapboys

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#469]
there is a note in hiscore.dat indicating hiscore support doesn't work but there are also two question marks afterward

**Comment by Wilstorm** [comment]
@markwkidd - B.Rap Boys (World) crashes in Plus but B.Rap Boys Special (Japan) works fine. 

B.Rap Boys (World) on 2003 boots partially but sits on a "calc check" running what looks like hex numbers very rapidly around pass 4.

I tried getting a high score but I was using load/save states. After I hit the bottom of the high scores I let my peep die. After he died it counted down from 9 to 0 and then the screen went black and does nothing. If I don't use save/load states it seems to end the game fine. I never made the high score chart. Good game to test but wasn't sure if the Japan Special Edition was in the hiscore.dat

**Comment by grant2258** [comment]
using states could be causing this game to crash. I think this is one of the games that suffered from rewind both a running on windows 64 bit fine. Will test on the pi when i get time. I need to phone the one that must be obeyed lol.

**Comment by grant2258** [comment]
just tried this on the pi both games are working fine on the pi. please clear the following mame data for both braps (change your path accordingly). 

 rm ~/RetroPie/roms/mame-libretro/mame2003-plus/nvram/brapboysj.nv
 rm ~/RetroPie/roms/mame-libretro/mame2003-plus/nvram/brapboys.nv
 rm ~/RetroPie/roms/mame-libretro/mame2003-plus/cfg/brapboysj.cfg
 rm ~/RetroPie/roms/mame-libretro/mame2003-plus/cfg/brapboys.cfg

There is something funky going on with  your pi  setup either software related or overclocking

**Comment by Wilstorm** [comment]
brapboys.zip works on the Pi for you on the current commit?

**Comment by Wilstorm** [comment]
It was a new run so no configs and since your overclocking acumen is limited I disabled it a few days ago to put your mind at ease. Do you use a Mac or something, never built a PC from scratch?

**Comment by grant2258** [comment]
would you expanding "overclocking acumen is limited" i find that entertaining.

The pi is  know to be unstable for some and not for others with over clocking. All you simply need to say is its not overclocked anymore.
 Comparing over clocking a pi to building a pc has no relevance to any of this. Are you trying to say something specifically or just making assumptions ive never built a pc? it hard to find any relevance in tis comment. IAnyway hope you get it working

**Comment by grant2258** [comment]
As far as retropie goes 4.4 wasnt very stable for me. I had to do a binary and update the system files on a fresh install. Im sure you have done that already when you installed it. I dont know what else to tell you on this maybe other people can confirm this issue to a certain model of pi ect. im testing on a 3b+ i have a pie 2 about as well. Can test on that at some point if you get no joy and ill let you know if these 2 games work on that as well.

**Comment by Wilstorm** [comment]
There is plenty of relevance and correlation between the Pi and PC. What exactly do you think is happening when a 3rd party takes a manufacturer's reference hardware, bumps the clock by 20% and brands it with an OC or Ti or whatever. This isn't rocket science. 

So they take a percentage point or two off the bell curve to pad the hardware. That's the way hardware is designed and sold. They sell it at a minimum guaranteed speed, it's a reference clock well below it's capabilities, most of the time. That's why they advertise a specific clock speed.

They just need to hit a percentage of success within the manufactering variance process and leave the wiggle room to the user. Though I've yet to hit the top of the bell curve in the Pi lottery using proper OC techniques. Many Pi OC's are unstable with little to no testing. 

Look at Intel's black line. They unlock the multiplier and let you melt the silicone. They sell them at a higher price point because folks like you melt them or have a bad experi nice due to inexperience and claim nothing is stable overclocked. There's no hard line here, each Pi has a material and quality build variance.

It's clear you don't understand how it works or build PC's or we wouldn't need to address OC'ing on every issue I open. This would be standard knowledge for you. That OC'ing is safe when done properly.

You had a bad experience and think everybody's Pi is like mine. No one could possibly do better than me. Well shit guy maybe it's not and maybe we can! Maybe you received stock from a bad batch, manufacturing fell out spec, the silicone sucks, your OC'ing technique needs improvement or whatever. 

I have I think 8 or 9 Pi's total which includes a few of each version, two Zero's and one 3+ still in the box new on the desk. I've yet to find one that can't get me at least a 5 to 15 percent performance boost.

Now that we wasted all our time on OC discussion. I'll start rebuilding my image from scratch since we know B.Rap Boys (World) works on the Pi. Heh, that's all you had to say too. You're no better at being diplomatic than me and neither of us obviously like to take shit but you go at further than I ever did. You have fun like 1% of the time and over the top the other 99%. Loosen up a bit: I moved out when I was 17 to avoid it with nothing but what I could fit in my car and did alright. I'll do my best to not follow what you're doing so we don't lock horns and have a full blown debate on every issue. Why does every issue have to be debate. I was there for the RA discussion when they had to close the thread. I know how far you will take it to not be wrong. I never met anyone so eager to prove they were so right as much as you do. You're still dogging on Dank but he's not taking you on. That's why I addressed Mark so I didn't have to listen to you bitch at me like a fish wife about everything I'm doing wrong. Maybe my card is corrupt or went bad, I don't know at this point yet, if B.Rap does work. I was just trying to help with the high score testing. Anyway I'm just rattlin' and out guy, thanks for everything and good luck with the core AND STAY AWAY FROM OVERCLOCKING, for goodness sake!

**Comment by grant2258** [comment]
LOL unbelievable you some man get a grip :) hope you get it working.  Another post full of guff and bitching accusing me of it got to love it.I do hope you get it working ill let you have the next post haha.

**Comment by grant2258** [comment]
just to fill in your assumptions ive build my own pcs since the 486 came out :).

**Comment by arcadez** [comment]
Fuck sake just play the Japan version :) it's better anyhow having extra content

**Comment by grant2258** [comment]
amen both do work I cant seem to get a high score with one credit i suck bad at this game ill try it tin the barcade lol!

**Comment by arcadez** [comment]
Hmm.............

@markwkidd - B.Rap Boys (World) crashes in Plus but B.Rap Boys Special (Japan) works fine.

B.Rap Boys (World) on 2003 boots partially but sits on a "calc check" running what looks like hex numbers very rapidly around pass 4.

Actually the behavior you describe above with regards to the World version of B Rap Boys
is what would happen when trying to boot the game in MAME versions before the calc3 
protection was cracked around MAME130 or so

Funny why it should be doing this when we have the calc3 code present in this core now, also
even stranger is why only one version is affected.?? you'd think both would be if there is infact
a problem with the calc3 decryption in the kaneko16 driver.

As there always been a conflict around these games actually working in this core some say
they do some say they dont i feel like it's worth investigating the code again sometime,
anyway both B Rap Boys versions required new romsets after the calc3 was cracked maybe
the World version is the wrong one vs the jap version which might explain why one works
and the other doesn't.

**Comment by grant2258** [comment]
i tried loading the original mame2003 brapboys got this.

[libretro INFO] [MAME 2003+] Opening ROM file: rb-030.u61
[libretro ERROR] [MAME 2003+] rb-030.u61   NOT FOUND
[libretro INFO] [MAME 2003+] read_rom_data: All done
[libretro INFO] [MAME 2003+] Opening ROM file: rb-031.u62
[libretro ERROR] [MAME 2003+] rb-031.u62   NOT FOUND
[libretro INFO] [MAME 2003+] read_rom_data: All done
[libretro INFO] [MAME 2003+] Opening ROM file: rb-040.u33
[libretro ERROR] [MAME 2003+] rb-040.u33   NOT FOUND
[libretro INFO] [MAME 2003+] Opening ROM file: rb-020.c2
[libretro ERROR] [MAME 2003+] rb-020.c2    NOT FOUND
[libretro INFO] [MAME 2003+] Opening ROM file: rb-021.u76
[libretro ERROR] [MAME 2003+] rb-021.u76   WRONG LENGTH (expected: 00100000 foun                                                                                                                d: 00080000)
[libretro ERROR] [MAME 2003+] rb-021.u76   WRONG CHECKSUMS:
[libretro ERROR] [MAME 2003+]     EXPECTED: CRC(74001407) SHA1(90002056ceb4e0401                                                                                                                246950b8c3f996af0a2463c)
[libretro ERROR] [MAME 2003+]        FOUND: CRC(b7e2d362) SHA1(7e98e5b3d1ee972fc                                                                                                                4cf9bebd33a3ca96a77357c)
[libretro INFO] [MAME 2003+] Opening ROM file: rb-022.u77
[libretro ERROR] [MAME 2003+] rb-022.u77   WRONG LENGTH (expected: 00100000 foun                                                                                                                d: 00080000)
[libretro ERROR] [MAME 2003+] rb-022.u77   WRONG CHECKSUMS:
[libretro ERROR] [MAME 2003+]     EXPECTED: CRC(cb3f42dc) SHA1(5415f15621924dd26                                                                                                                3b8fe7daaf3dc25d470b814)
[libretro ERROR] [MAME 2003+]        FOUND: CRC(8d40c97a) SHA1(353b0a4a508f2fff8                                                                                                                eeed680b1f685c7fdc29a7d)
[libretro INFO] [MAME 2003+] Opening ROM file: rb-023.u78
[libretro ERROR] [MAME 2003+] rb-023.u78   WRONG LENGTH (expected: 00100000 foun                                                                                                                d: 00080000)
[libretro ERROR] [MAME 2003+] rb-023.u78   WRONG CHECKSUMS:
[libretro ERROR] [MAME 2003+]     EXPECTED: CRC(0e6530c5) SHA1(72bff46f0672927e5                                                                                                                40f4f3546ae533dd0a231e0)
[libretro ERROR] [MAME 2003+]        FOUND: CRC(dcf11c8d) SHA1(eed801f7cca3d3a94                                                                                                                1b1a4e4815cac9d20d970f7)
[libretro INFO] [MAME 2003+] Opening ROM file: rb-024.u79
[libretro INFO] [MAME 2003+] Opening ROM file: rb-025.u80
[libretro ERROR] [MAME 2003+] rb-025.u80   NOT FOUND
[libretro INFO] [MAME 2003+] Opening ROM file: rb-010.u65
[libretro INFO] [MAME 2003+] Opening ROM file: rb-011.u66
[libretro INFO] [MAME 2003+] Opening ROM file: rb-012.u67
[libretro INFO] [MAME 2003+] Opening ROM file: rb-013.u68
[libretro INFO] [MAME 2003+] Opening ROM file: rb-000.u43
[libretro ERROR] [MAME 2003+] rb-000.u43   WRONG LENGTH (expected: 00080000 foun                                                                                                                d: 00040000)
[libretro ERROR] [MAME 2003+] rb-000.u43   WRONG CHECKSUMS:
[libretro ERROR] [MAME 2003+]     EXPECTED: CRC(58ad1a62) SHA1(1d2643b5f6eac2268                                                                                                                2972a88d284e00de3e3b223)
[libretro ERROR] [MAME 2003+]        FOUND: CRC(c7c848ac) SHA1(77754efd6efeac50a                                                                                                                40dcd530de504090257d8b3)
[libretro INFO] [MAME 2003+] Opening ROM file: rb-003.101
[libretro INFO] [MAME 2003+] Opening ROM file: rb-001.u44
[libretro ERROR] [MAME 2003+] rb-001.u44   WRONG LENGTH (expected: 00100000 foun                                                                                                                d: 00080000)
[libretro ERROR] [MAME 2003+] rb-001.u44   WRONG CHECKSUMS:
[libretro ERROR] [MAME 2003+]     EXPECTED: CRC(7cf774b3) SHA1(3fb0a5096ce9480f9                                                                                                                7e311439042eb8cbc26efb4)
[libretro ERROR] [MAME 2003+]        FOUND: CRC(09c779e3) SHA1(c9c9bf939d58d329b                                                                                                                87e0aa08ec3d35f7440d3c7)
[libretro INFO] [MAME 2003+] Opening ROM file: rb-002.u45
[libretro ERROR] [MAME 2003+] rb-002.u45   WRONG LENGTH (expected: 00100000 foun                                                                                                                d: 00080000)
[libretro ERROR] [MAME 2003+] rb-002.u45   WRONG CHECKSUMS:
[libretro ERROR] [MAME 2003+]     EXPECTED: CRC(e4b30444) SHA1(be6756dce3721226e                                                                                                                0b7f5d4d168008c31aeea8e)
[libretro ERROR] [MAME 2003+]        FOUND: CRC(55de7003) SHA1(cc349fd8671926caf                                                                                                                ed4d86d1a5cb671e591c408)
[libretro ERROR] [MAME 2003+] Required files are missing, the game cannot be run   

the thing is if someone messed with the roms and just added the missing files mame would still try to go with the bad crc and lengths it would just let you know like above when you looked at the log. 

Its entirely possible to make a bad hybrid set if your trying to keep one set for mame2003 and 2003+ as mame didnt have brapboysj you theory make sense.   Ill try adding the missing files and leave the bad ones in and see what happens when i get a chance.

**Comment by grant2258** [comment]
well i added the missing roms the gfx and sound is messed up this way but it still boots fine this way. It works on windows/linux/retropie for me though no issues at all.

**Comment by arcadez** [comment]
Right then putting this bug report down to having an incorrect brapboys rom
