### ISSUE TITLE
correct source for `glass` roms

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-plus-libretro#482]
Hi @arcadez -- I'm trying to rebuilt my sets for the latest DAT but I am having trouble with the latest updates to the `glass` parent romset with this commit: https://github.com/libretro/mame2003-plus-libretro/commit/4011b966dc977cffda79e8d71e955e9a0dbf2b58

I've tried rebuilding from MAME 0.193 and the MAME 0.193 Rollback set. Do you have any other suggestions for a source?

```
Glass [folder: glass - size: 7mb]
wrong size: c22.bin [wrong: 262144] [right: 524288] [CRC32: ab17c992] [not fixed]
wrong size: c23.bin [wrong: 262144] [right: 524288] [CRC32: 688cdf33] [not fixed]
```

**Comment by iosadosd-quarto** [comment]
Me too, I can't seem to find a source with the right size.

**Comment by arcadez** [comment]
The parent doesn't work although you'd need it to build the clone, i see the mistake i made
i'll sort it now

**Comment by arcadez** [comment]
Hmm right the original parent rom for glass in mame78 has since been renamed to glass10 and
demoted to a clone, this could cause some troubles for people not versed in romset creation as
you'd need 3 from the newest sets to make a working a clone.

What i will do is update our parent to latest MAME it still wont work as we'd need a new CPU to
handle the dsp5002 decryption but it will at least make finding the correct rom for the working 
version we support that bit easier.
