### ISSUE TITLE
About (firebarr.zip), picture mapping problem?

### ISSUE THREAD

**Issue by ji125443** [libretro/mame2003-plus-libretro#556]
As shown in the figure......
![firebarr-181220-115412](https://user-images.githubusercontent.com/25021120/50285257-a3218800-0496-11e9-82b2-9fe3471afab4.png)
comparison
![firebarr-181220-115902](https://user-images.githubusercontent.com/25021120/50285310-ccdaaf00-0496-11e9-9f23-faab0fa8a3c9.png)

![firebarr-181220-115613](https://user-images.githubusercontent.com/25021120/50285322-d5cb8080-0496-11e9-9e0c-0c54daf630ae.png)
comparison
![firebarr-181220-120131](https://user-images.githubusercontent.com/25021120/50285332-e0861580-0496-11e9-850c-3159767dd5da.png)

![firebarr-181220-120232](https://user-images.githubusercontent.com/25021120/50285341-eb40aa80-0496-11e9-8248-31940a6f2e37.png)
comparison
![firebarr-181220-120159](https://user-images.githubusercontent.com/25021120/50285382-07dce280-0497-11e9-936d-e927aa3c7bd7.png)

**Comment by grant2258** [comment]
damn you good at finding broke games !

**Comment by arcadez** [comment]
Yeah i know about this one basically a tile layer was disabled by BritneysPAIRS for a quick and
dirty fix hence the boats and the stage start screen, we would have to update the m107 video code
to fix this plus the missing rowscroll zooming effects hence the runway on level one.

Last i looked the m107 video code from later MAME was not compatable with older cores like this one
i might look again sometime but if you wanna see how this game looked and played before i backported
BP's video improvements and hooked up the sound try mame2003.

**Comment by grant2258** [comment]
@arcadez arcade do you know a site with mame change log lookups ?

**Comment by arcadez** [comment]
click info and driver

http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=firebarr&arcade_only=0&autosearch=1

**Comment by arcadez** [comment]
All the changes are here right enough.........

https://github.com/dinkc64/mame/commits/master?after=08b773a665063a35365a4c93fb3c7e9e7be515d3+34&path%5B%5D=src&path%5B%5D=mame&path%5B%5D=video&path%5B%5D=m107.c

**Comment by grant2258** [comment]
appreciated mate was just looking for a general lookup thing saves time

**Comment by arcadez** [comment]
m107 video was updated in MAME119 to use alotta video handlers we dont support in this older core
however it might still be possible to take those video changes from mame 140 or so and roll em into
the older code i didn't think it was easily doable hence i just left it be

**Comment by grant2258** [comment]
i actually looking to fix the sound in xevous3d the games pretty sweet just been looking at some namco stuff

**Comment by arcadez** [comment]
You'll need this CPU i think.........

0.99u9: Added sndhrdw\namcoc7x.c/h. Major Namco sound improvements [R. Belmont]: Added emulated sound and music to all NB-1, NB-2 and System 11 games, using Prop Cycle's MCU BIOS (pr1data.8k) as a substitute until the original can be trojaned or otherwise obtained. Hooked it up for plain System 22 games as well, but they're not interested in passing down proper commands for some reason. Speed-cheated all instances of the M37710/C352 sound system so CPU requirements don't go up much. This also helped back off the requirements a hair for Prop Cycle and Time Crisis. C352 now sets output pitch correctly by input clock. Added M37710 (16384000 Hz) CPU2 and C352 (16384000 Hz) stereo sound.

**Comment by arcadez** [comment]
Anyway i'll close this one down as Fire Barrel is as good as it's gonna ever be in this core
it's playable with some gfx niggles plus we have the full on sound vs how it originally was
in mame2003.

BTW IMO this game surely has the best music of any shmup ever.??

**Comment by arcadez** [comment]
Flying Shark eh one of my ole faves that one, handy hint Sky Shark doesn't have the slowdown
on the last level when you come up against all the tanks around the cave section.

**Comment by ji125443** [comment]
Got two more.

(heatbrl.zip)
![heatbrl-181222-095631](https://user-images.githubusercontent.com/25021120/50373115-d68a2100-0614-11e9-8f42-1d4e2edb0e9a.png)
![heatbrl-181222-095653](https://user-images.githubusercontent.com/25021120/50373116-d68a2100-0614-11e9-91e2-3a96e44578cd.png)

（legionna.zip）
![legionna-181222-095534](https://user-images.githubusercontent.com/25021120/50373122-f28dc280-0614-11e9-8008-8cda17cff54f.png)
![legionna-181222-095553](https://user-images.githubusercontent.com/25021120/50373123-f7eb0d00-0614-11e9-932e-eca2a69b04e8.png)

**Comment by arcadez** [comment]
Thanks for reporting!! although i know about about these ones as well, same Seibu hardware more or less as Raiden 2 and Zero Team i tried to backport the changes from later MAME to fix these ones a while
back but no joy i can get legionnaire to boot but as soon as  level one starts the game crashes :(

Dev talk follows no need to read on if easily bored :)

Long story short these games use quite complex math / calc angles for the hitboxes / sprite collisions plus the gfx are encrypted with a nasty protection scheme, from around MAME140 Heated Barrel
and SD Gundam Rainbow Tarakei are more or less playable legionnare, raiden II plus Zero Team not so much you need code from later MAME builds to fix those ones up which would be doable i think barring Raiden II and Zero Team which would require a CPU we dont support plus ZT is not playable in latest
MAME at the moment.

Of all the games in legionna.c and raiden2.c only Denjin Makai works in this core as unlike all the
rest this game gets it's hitbox and sprite collisions via the M68k CPU some others do also more about
those later, i just split it off from legionna.c for ease of porting creating a new driver for it called denjinmk.c, if you haven't already you should give it a whirl sometime it's a nice wee beat em up.

Raiden II /  Raiden DX New, New Zero Team / Zero Team 2000 like Denjin Makai use the main CPU a 
V33 to again handle the graphical encryption plus the hitbox and mathamatical sprite collisions
meaning this is the only version of ZT which is fully playable and these games could in theory be
dropped into our denjinmk.c driver if we only had the V33 CPU they require, however both of these
Raiden II versions have cheap ass sound system far worse than the original Raiden II versions so
you'd only really play em if they were the only versions that worked know what i mean.

Still Awake..?? :)

When it comes to Heated Barrel, Legionnaire, Godzilla and SD Gundam Rainbow Tareki the plan was to update in stages starting at MAME140 or so gathering up all the fixes to hopefully end up with them in a fully working state and with the code i have in another project they should be in theory fully playable
however i ran into some difficulty with the hitbox and math angle code getting it to compile in the older core brief explaination follows...............

void seibu_cop_legacy_device::cop_take_hit_box_params(UINT8 offs)
{
	INT16 start_x,start_y,height,width;

	{
		height = UINT8(m_cop_collision_info[offs].hitbox_y >> 8);
		start_y = INT8(m_cop_collision_info[offs].hitbox_y);
		width = UINT8(m_cop_collision_info[offs].hitbox_x >> 8);
		start_x = INT8(m_cop_collision_info[offs].hitbox_x);
	}

	m_cop_collision_info[offs].min_x = (m_cop_collision_info[offs].x >> 16) + start_x;
	m_cop_collision_info[offs].max_x = m_cop_collision_info[offs].min_x + width;
	m_cop_collision_info[offs].min_y = (m_cop_collision_info[offs].y >> 16) + start_y;
	m_cop_collision_info[offs].max_y = m_cop_collision_info[offs].min_y + height;
}

I got compile errors with this around UINT8 and INT8 i assume it was due to my VS version
anyway i had to make it this which i assume might have changed the how the emulator
interprets the meaning of the code.?? which might explain why legionnare borks as soon
as level one starts when the hitbox sim code would kick in.??

void seibu_cop_legacy_device::cop_take_hit_box_params(UINT8 offs)
{
	INT16 start_x,start_y,height,width;

	{
		height =( UINT8)(m_cop_collision_info[offs].hitbox_y >> 8);
		start_y = (INT8)(m_cop_collision_info[offs].hitbox_y);
		width =( UINT8)(m_cop_collision_info[offs].hitbox_x >> 8);
		start_x = (INT8)(m_cop_collision_info[offs].hitbox_x);
	}


Then we get to cos and sin maths which handle character movements and collisions.......

			/* SINE math - 0x8100 */
			/*
			     00000-0ffff:
			       amp = x/256
			       ang = x & 255
			       s = sin(ang*2*pi/256)
			       val = trunc(s*amp)
			       if(s<0)
			         val--
			       if(s == 192)
			         val = -2*amp
			*/
			if(COP_CMD(0xb9a,0xb88,0x888,0x000,0x000,0x000,0x000,0x000,7,0xfdfb))
			{
				int raw_angle = (space.read_word(m_cop_register[0]+(0x34^2)) & 0xff);
				double angle = raw_angle * M_PI / 128;
				double amp = (65536 >> 5)*(space.read_word(m_cop_register[0]+(0x36^2)) & 0xff);
				int res;

				/* TODO: up direction, why? */
				if(raw_angle == 0xc0)
					amp*=2;

				res = int(amp*sin(angle)) << m_cop_scale;

				space.write_dword(m_cop_register[0] + 0x10, res);
				return;
			}

			/* COSINE math - 0x8900 */
			/*
			 10000-1ffff:
			   amp = x/256
			   ang = x & 255
			   s = cos(ang*2*pi/256)
			   val = trunc(s*amp)
			   if(s<0)
			     val--
			   if(s == 128)
			     val = -2*amp
			*/
			if(COP_CMD(0xb9a,0xb8a,0x88a,0x000,0x000,0x000,0x000,0x000,7,0xfdfb))
			{
				int raw_angle = (space.read_word(m_cop_register[0]+(0x34^2)) & 0xff);
				double angle = raw_angle * M_PI / 128;
				double amp = (65536 >> 5)*(space.read_word(m_cop_register[0]+(0x36^2)) & 0xff);
				int res;

				/* TODO: left direction, why? */
				if(raw_angle == 0x80)
					amp*=2;

				res = int(amp*cos(angle)) << m_cop_scale;

				space.write_dword(m_cop_register[0] + 20, res);
				return;
}

	/* Pythagorean theorem, hypotenuse direction - 130e / 138e */
			//(heatbrl)  | 5 | bf7f | 138e | 984 aa4 d82 aa2 39b b9a b9a b9a
			if(COP_CMD(0x984,0xaa4,0xd82,0xaa2,0x39b,0xb9a,0xb9a,0xb9a,5,0xbf7f))
			{
				int dy = space.read_dword(m_cop_register[1]+4) - space.read_dword(m_cop_register[0]+4);
				int dx = space.read_dword(m_cop_register[1]+8) - space.read_dword(m_cop_register[0]+8);

				m_cop_status = 7;
				if(!dx) {
					m_cop_status |= 0x8000;
					m_cop_angle = 0;
				} else {
					m_cop_angle = atan(double(dy)/double(dx)) * 128.0 / M_PI;
					if(dx<0)
						m_cop_angle += 0x80;
				}

				m_r0 = dy;
				m_r1 = dx;

				if(m_cop_mcu_ram[offset] & 0x80)
					space.write_word(m_cop_register[0]+(0x34^2), m_cop_angle);
				return;
}

i would get errors on these lines again adding extra () sorted it.........

			res = (int)(amp*cos(angle)) << m_cop_scale;
			m_cop_angle = atan(double)(dy)/(double)(dx)) * 128.0 / M_PI;

Again though im not sure if adding these extra () actually changes how the code would be
interpretated when the emulator is running the games however i spoke to Kale awhile back
who actually worked on alotta this code and he told it he wasn't sure of the changes i made
would break the games however he aired on the side of that they wouldn't.

Whatya think yourselfs.??

**Comment by grant2258** [comment]
can you post t he error you got before changing arcadez?

**Comment by grant2258** [comment]
and this compiles fine elsewhere this way ?

**Comment by grant2258** [comment]
yea c++ allows you to do this the only way  test this if this is the case is compile seiccop as cpp

**Comment by grant2258** [comment]
@arcadez i tied to print the values we have this function doesnt even appear to be called at all

**Comment by arcadez** [comment]
Ah so it was an issue with trying to use in the code in older c files rather than my ole compiler per say
generic_cop_w is called on a per game basis from for example denjin_mcu_r and denjin_mcu_w

**Comment by grant2258** [comment]
[seicop.zip](https://github.com/libretro/mame2003-plus-libretro/files/2705657/seicop.zip)

**Comment by arcadez** [comment]
I added your hitbox and math calc changes although i kept em in the c standard plus removed a
few static calls like you had in seicop.c same deal with legionnaire unfortunately,

So that we are on the same page here are all the src files although you wont be able to compile em 
unless i roll back some mem and input code maybe you'll spot a mistake or two i might have made
essentially it's the same code i used for denjinmk.c in this core

Oh and i can only find cop_mcu_ram no mention of mcu_ram in either legionna.c or seicop.c

Full code
https://www.sendspace.com/file/i9lp8o

**Comment by grant2258** [comment]
only other syntax is try this

**Comment by grant2258** [comment]
the drivers need a fair bit of work to get into our core will look a little more when i get more time look into it

**Comment by grant2258** [comment]
ok ive updated the driver and videohardware i used the first machine file you sent though. I havent done the inputs for legionna yet just getting a black screen. you can hear the sound when you put a a
credit in though.  Ill have a look later n check if i can see anything amiss.

**Comment by grant2258** [comment]
nm need to update the machine 


[libretro INFO] [MAME 2003+] 000b00: COPX unhandled read returning 0000 from offset 0340
--
