### ISSUE TITLE
Lightgun games - limited range when using controller

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#647]
Some games have limits on where you can shoot, like most Exidy lightgun games that only have a range of a diamond shape, or in the case of jpark, in a weird star shape. All while using a controller.

**Comment by grant2258** [comment]
you need to use the mouse for lightgun for these games.  

Different analog devices read in different ways like dials  and lightguns and trackballs ect. 

They dont all translate well to each other.you need to use the right type of analog device in this case a mouse because there is no lightgun support

**Comment by grant2258** [comment]
also there was another big update to the inputs yesterdays it was mentioned in the pull request you need to clear your cfg dir
