### ISSUE TITLE
Shrike Avenger

### ISSUE THREAD

**Issue by arcadez** [libretro/mame2003-plus-libretro#686]
Just got this one working im not sure how it was played in the arcades, i assume there were two seats and player 1 moved the ship while player 2 fired although you can still fire via player 1 if you pardon 
the pun fly solo.

This made we wonder why you had to press both seat buttons to start the game seat = player start 
you have to press both seats everytime you wanna start a game which doesn't make sense if your just playing as a single player i guess the buttons must have been close together :)

Anyway for ease of use on the xbox i just mapped player 1 and player 2 start to use the same button 
via the driver inputs so i dont require two gamepads to start a game lemmie know if this works and you can start the game ok in this core i assume you will be able too.??

Shrike Avenger

![shrike](https://user-images.githubusercontent.com/35177309/55121117-deb09b80-50f0-11e9-9f01-aecdf2147fa1.png)

![shrikem](https://user-images.githubusercontent.com/35177309/55121127-e53f1300-50f0-11e9-8213-164a6ef89c44.jpg)

**Comment by arcadez** [comment]
Ok im sure this game will work in this core as it did in my xbox 72 build so i'll close this down

**Comment by grant2258** [comment]
ill test it tomorrow for you only have the plus roms on my i7 laptop can only hold one set have ame095 on it but will let you know if its working or not guv

**Comment by arcadez** [comment]
Och dont bother your busy with other stuff just now i suspect the game will be 100% just wasn't sure if
the input hack i added would be good for this core i dont see any reason it'll not be but ya never
know

BTW nice job ya did with the Namco System 11 sound

**Comment by grant2258** [comment]
it working fine my good man is an usual game never seen this one before.

**Comment by arcadez** [comment]
Yeah a little too unusual as it never got a wide release due to negative reviews on location test
it's not a bad game right enough hence my interest it getting it to work for this core thanks
again for testing.

**Comment by robertvb83** [comment]
@arcadez I just researched this game and found a german manual at arcade-museum.com https://www.arcade-museum.com/S/Shrike_Avenger.html
it is mentioned that the seat has 2 buttons that need to be pressed simultaneously for starting the game. if one button is pressed during game it will be paused automatically until both buttons are pressed simultaneous again.
reason is: due to heavy motors moving the seat on joystick movement this was considered a safety measure. the seat is engaged only if the player is ready. Interesting is also that the complete unit was put on a base plate equipped with sensors to detect another person coming near. if so the seat movement was immediately stopped for safety.

**Comment by arcadez** [comment]
Thanks for the heads up, so there ya go then 2 buttons to start was a safety feature, mapping both
inputs to player 1 start seems to work fine.
