### ISSUE TITLE
Dip Switch Menu Issue

### ISSUE THREAD

**Issue by zanac** [libretro/mame2003-plus-libretro#744]
If i select an option on dip switch menu with multiple choice (for example an option that has value "easy, normal, hard" i cannot switch using joystick in all option. The issue appare using a stick of a joystick. Option that has just on/off work as exptected.

**Comment by arcadez2003** [comment]
There have been alot of input changes in this core, it might be you need to change some settings
so that the dip selection options are fully mapped, try raising this here...........

https://retropie.org.uk/forum/topic/17766/mame2003-plus-hundreds-of-new-games-improved-input-features-new-bugs-now-with-runahead-support

**Comment by Wilstorm** [comment]
@zanac - Sticking with the Ghost's N Goblins theme. :) I tested this on a Raspberry Pi 3 with m3plus build aa8e74a and 2003 build aa607d0 using Retroarch 1.7.6 and both allowed me to change the difficulty (Easy, Normal, Difficult & Very Difficult) in the TAB menu with a keyboard or joystick.

If you post on the forum link @arcadez2003 suggested above their is a guy that is very good with inputs and should be able to get your issue sorted. It sounds more of a settings issue only but you didn't list the game or the platform your running. I think the defaults are digital inputs and not analog depending on your controller.
