### ISSUE TITLE
CAn you please add CPS 3 support? 

### ISSUE THREAD

**Issue by ghost** [libretro/mame2003-plus-libretro#756]
hello how are you? can you please add support for games of the cps3 like street fighter 3?
I love those things so much !

**Comment by Darknior** [comment]
Yes me too and i really prefer use MAMEP than FBA on my pi, so bad we don't have these cool CPS3 games on MAMEP too :p

**Comment by edneyhelene** [comment]
YEah in my case i'm using android version with retroarch, i really want cps3 roms on mame 2003-plus

**Comment by Darknior** [comment]
Yeah and if possible with support of ROM Hack, impossible to load them on FBNeo. I have them from the CPX emu on xbox, roms that unlock final all boss as playable charater :)

**Comment by arcadez2003** [comment]
The problem is the CPS3 driver and the CPS3 custom sound cores we'd need to get these games
up and running in this core would need to be taken from MAME117 and they contain a bucketload
of code which is not compatible with this core.

I've looked at the code and i cant see anyway it could backported otherwise it would have
been done by now, it'll take someone with more skill than me to pull this one off.

So for now at least the CPS3 games are a non starter.

**Comment by Darknior** [comment]
Ok i understand.
But it's strange, i remember MAME 2010 can make them work ... maybe i'm not remember fine :p
Or MAME 2010 is the 117 version and like you write it's complicated to back port.
Thanks

**Comment by edneyhelene** [comment]
It's sad....maybe someone could do it?

**Comment by Wilstorm** [comment]
>But it's strange, i remember MAME 2010 can make them work ... maybe i'm not remember fine :p
Or MAME 2010 is the 117 version and like you write it's complicated to back port.

Mame2010 is based off MAME 0.139.

**Comment by arcadez2003** [comment]
> 
> 
> It's sad....maybe someone could do it?

Sure someone else might come along and fancy giving it a try, the problem is so much of
the CPS3 code would need to be reworked for this core meaning the workload would be 
on the large side.

There was some whispers a few years back of some chinese coder who did the above that's
to say got the CPS3 games to work in a special MAME84 build, however he would not release
the source code, which is a pity as im confident should i have gotten my hands on it we'd
have the CPS3 games up and running in this core most likely.

**Comment by edneyhelene** [comment]
Why dont you try to talk with him and see if he releases the code? 
That would be too stupid to keep a code like this for himself, thats useless, the world is opensource.
We really need to take it to the next level porting cps3 to mame 2003 plus, this core is fantastic.

**Comment by arcadez2003** [comment]
Aye it might just be one of those urban legends, some fella posted that a friend of a friend had
another friend who had a special build of MAME84 with CPS3 support etc etc etc.

I asked the guy if he could get the sources for me and the build to lemmie see the games in action
and he could obtain neither, i wasn't the only developer after these sources and they all got the
same answer, so most likely it was all bullshit.

**Comment by edneyhelene** [comment]
> Aye it might just be one of those urban legends, some fella posted that a friend of a friend had
> another friend who had a special build of MAME84 with CPS3 support etc etc etc.
> 
> I asked the guy if he could get the sources for me and the build to lemmie see the games in action
> and he could obtain neither, i wasn't the only developer after these sources and they all got the
> same answer, so most likely it was all bullshit.
> 
> But hey even if it was legit i never knew the chinese coder who had apparently worked on it
> and i cannot remember the name of the guy who told me about it 5 years or so back, the trail
> as they say has gone cold :)


Yay..yeah unfortunately i think its a game over for now. but thanks anyways, if something changes i would be happy to help with testing.

best, eddy;
