### ISSUE TITLE
4-way joystick emulation support for Ghosts 'n Goblins and Ghouls 'n Ghosts

### ISSUE THREAD

**Issue by Gorxlor** [libretro/mame2003-plus-libretro#764]
I'm using RetroArch 1.8.2 on Windows 10. I was hoping to try out the "4-way joystick emulation" core option with Ghosts 'n Goblins and Ghouls 'n Ghosts after I noticed that the diagonals on my 8-way stick were producing strange behaviour in Ghosts 'n Goblins (running on the spot at ladders, getting stuck in crouch), but the option doesn't show up for these games. It's there for other 4-way games like Pac-Man, so I assume they're not categorised as 4-way games by the core (however that happens).

I don't have direct experience of the original arcade cabinets, but based on the arcade manuals I can find on the internet both seem to have used 4-way joysticks. Would it be possible to add support for the 4-way joystick emulation option to these games?

**Comment by arcadez2003** [comment]
Hi there

According to MAME and the official Arcade Museum Ghost's N Goblins is 8-way, however
Ghouls N Ghosts is 4-Way, our ole CPS1 driver still has Ghouls N Ghosts tagged as 8-way
although it would be easy enough to change it over to 4-way.

**Comment by Gorxlor** [comment]
Hi, thanks for the quick response! I remember noticing that the Arcade Museum had Ghosts 'n Goblins listed as 8-way when I first felt like there was a problem, but both the instruction manual and the dip switch guide linked to on their Ghosts 'n Goblins page reference a 4-way joystick/lever, so I'm wondering if it's a mistake on their part.

**Comment by dinkc64** [comment]
I've done experiments here - gng is one of my favorite games (actually, I'm obsessed with it.  fwiw, I can play the game endlessly on 1 coin).
Regardless of whether you have 8way or 4way type joysticks emulated, the game is going to be "weird" when it comes to ladders.  
things to look out for, the first one will be of use during the game:
Ladder warping: if you get close to a ladder, you can warp to it (aka instantly move to the ladder) by pressing up
When going up or down a ladder, make sure you're all the way to the top or bottom before pressing left or right, otherwise the game acts weird.  <-- after years of playing, this doesn't seem to bother me anymore because I account for it.

best regards,
- dink

**Comment by arcadez2003** [comment]
Yeah the change to 4-way isn't gonna make much difference overall to how the games control
or handle, but for that reason and the fact after consulting the arcade manuals for both games
and the joystick type they recommend im happy to switch em both over to 4-way.

**Comment by arcadez2003** [comment]
Ok Switched both games over to using 4-WAY
