### ISSUE TITLE
To do: add sample pause support for more games

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#805]
After updating things to support journey sample, two tigers could also be supported.  Will start working on this this week.

**Comment by arcadez2003** [comment]
Might as well make it a two for one deal and take greater advantage of the sample pausing code..

**Comment by mahoneyt944** [comment]
Thanks I was looking at this the other day and it looked pretty straight forward. I noticed the sample is pretty large for this game. It looks like twotiger does not use the sample as it doesn't have tape testing in the service menu but twotigra does have it. I know this game was sold as a Tron conversion too, so tron's code may be a resource to look at if needed. 

Also, any other games using pause should be included in this post on the to do list. I'll get to it soon.

**Comment by gomisensei** [comment]
0.102u2: Properly hooked up tape samples in Thief, NATO Defense, and Shark Attack now that sample pausing is available [Bart Tobalske].

**Comment by mahoneyt944** [comment]
> 0.102u2: Properly hooked up tape samples in Thief, NATO Defense, and Shark Attack now that sample pausing is available [Bart Tobalske].

It appears these are already supported in the thief.c driver. One of the updates made to journey was to properly support large samples, if these samples are larger than 10mb then they wouldn't have been working. However that issue has now been resolved and these samples should be working.

**Comment by mahoneyt944** [comment]
@gomisensei support added, untested. https://github.com/libretro/mame2003-plus-libretro/pull/806

**Comment by WindyWinston** [comment]
@mahoneyt944 or @arcadez2003 Partially related, I noticed in the datfile that the Custom Soundtrack Samples are listed for '`ffightae`'. Maybe these shouldn't be there as none of the other Custom Soundtrack Samples are in the datfile (I think because they're considered optional as opposed to the normal samples which are essential).

**Comment by arcadez2003** [comment]
Likely an oversight with regards to ffightae im sure someone will fix the dat at some point, as for
Street Fighter 2 custom soundtracks i ported the code across to MAME2003+ but it resulted in
compile errors i mentioned this to the guys responsible for creating those custom soundtracks
with a view that i'd leave it them to add support for the samples to this core.

I guess they haven't got around to it yet :)

**Comment by arcadez2003** [comment]
> 
> 
> 
> Also, any other games using pause should be included in this post on the to do list. I'll get to it soon.

Well a quick search of the MAME git turns up the following games, there are not all that many 
using the sample pausing feature...........
https://github.com/mamedev/mame/search?q=m_samples-%3Epause&unscoped_q=m_samples-%3Epause

**Comment by mahoneyt944** [comment]
Two Tigers now supported https://github.com/libretro/mame2003-plus-libretro/pull/807

**Comment by mahoneyt944** [comment]
looks like lrescue and trplhnt next.....

**Comment by arcadez2003** [comment]
> 
> 
> Two Tigers now supported #807

This might cause some build issues, im not saying it will but i've had compile errors with similar
code before, i think it's due to later MAME cores supporting c++ where as MAME78 only 
supports c

for (int i = 0; i < 2; i++)

Anyway if there are issues make it like so.........

static WRITE_HANDLER( twotiger_sample_select_w )
{
    int i = 0;

    for (i = 0; i < 2; i++)
  {

**Comment by mahoneyt944** [comment]
> > Two Tigers now supported #807
> 
> This might cause some build issues, im not saying it will but i've had compile errors with similar
> code before, i think it's due to later MAME cores supporting c++ where as MAME78 only
> supports c
> 
> for (int i = 0; i < 2; i++)
> 
> Anyway if there are issues make it like so.........
> 
> static WRITE_HANDLER( twotiger_sample_select_w )
> {
> int i = 0;
> 
> ```
> for (i = 0; i < 2; i++)
> ```
> 
> {

Are you getting any build issues with it? The code worked when I tested it. Can you test?

**Comment by arcadez2003** [comment]
Oh im just talking in general terms, i've never even compiled this core i tended to test code in my
MAME72 xbox core and then port it across here all being well, anyway if i try to compile mcr2.c
i get these errors but it could be confined to just the xbox and or VS3003.

mcr2.c
src\drivers\mcr2.c(221) : error C2143: syntax error : missing ';' before 'type'
src\drivers\mcr2.c(221) : error C2143: syntax error : missing ';' before 'type'
src\drivers\mcr2.c(221) : error C2143: syntax error : missing ')' before 'type'
src\drivers\mcr2.c(221) : error C2143: syntax error : missing ';' before 'type'
src\drivers\mcr2.c(221) : error C2065: 'i' : undeclared identifier
src\drivers\mcr2.c(221) : warning C4552: '<' : operator has no effect; expected operator with side-effect
src\drivers\mcr2.c(221) : error C2059: syntax error : ')'
src\drivers\mcr2.c(222) : error C2143: syntax error : missing ';' before '{'

**Comment by mahoneyt944** [comment]
It could be vs2003, I compile everything on my rpi3b+ in command for testing.

**Comment by arcadez2003** [comment]
Aye that'll be it then

**Comment by Wilstorm** [comment]
@WindyWinston - With @grant2258's help I submitted a pull request to remove the ```ffightae``` custom OST samples. We'll have to wait for it to be merged to get a clean DAT. I use them and think they are great but I agree they are optional and purists might not like the idea of an audio refresh. 

I don't know but I would assume none of the others are in the DAT as may interfere with the official samples (if there are any) due to clones being linked to the parent samples. They probably just slipped in with the addition of the Anniversary Edition.

**Comment by WindyWinston** [comment]
Nice one! Yeah, only the Final Fight OST samples were there and like you say, they probably got mistakenly added with the Anniversary ROM.
