### ISSUE TITLE
Revx volume setting initiation

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#856]
@KMFDManic @arcadez2003 @markwkidd 

I created a bootstrap for revx, #857 to eliminate the gun calibration and CMOS errors. Working great, and just merged thanks mark!

The volume level in this game is in the service menu. Right now the game is too quiet so you have to turn the volume up. I've added this corrected volume setting in the bootstrap and it indeed saves this setting. However, when you launch the game this setting is not initialized so even though the volume is up all the way the game hasn't read in this setting yet and doesn't use it. If you bind the volume up / down buttons under input this game you can force the volume level to initialize by pressing volume up or down one time. To fix this game we need to initialize the volume setting in the driver so the game uses it from the get go. So whatever the setting is that's what gets loaded. Right now it's only initialized once the volume button is pressed.

Midxunit.c

**Comment by KMFDManic** [comment]
I will take a peek at things when I wake up tomorrow.  If we can pinpoint and get that sound active from the get go at louder volume, it will be a true win win!  SO far, SO good, though!  You did an excellent job!  After I got off work yesterday, I really really wanted to get Virtua Fighter coded into Xtreme.  And, that worked out quite nicely, as I can now run it around 55-60 FPS.  Arcadez2003 gave a little creative input into some of the timing to help with the finality of it all!  

I am also gonna try to get the other bootstrap additions into Xtreme over the next day or two.  But, so happy you have taken an interest in these!  I really need to do the calibration for Race Drivin and Hard Drivin'.  I played Race Drivin' Arcade on PS2 Emulator in my currently uploading video, and it is damned fine and fun to play (albeit, you can notice the typical lower skewered volume artifacts when it plays the main theme that sounds like Holiday Road from Vacation!  

I will be sure to video showcase the bootstraps, too!

What would really be amazing is being able to work in the OTHER Model 1 game, Virtua Racing in.  It seems to have been fixed up for lr-mame2003.  But, otherwise, its coding wasn't really optimal for playability til MAME .115!  In any case, this is the video I posted.  The last few minutes are Race Drivin'!  And, fairly near 9:11 point (3rd test) is me running the Virtua Fighter on MAME 2003 Xtreme with 3 testing compile perimeters (other two tests are directly before the 9:11 mark).  I got 15 FPS, 45 FPS, and finally 55+!  Thanks again, and will communicate with you later today and tomorrow!

https://www.youtube.com/watch?v=vjWXTx5p9r0

**Comment by KMFDManic** [comment]
@mahoneyt944 

I will take a peek at things when I wake up tomorrow.  If we can pinpoint and get that sound active from the get go at louder volume, it will be a true win win!  SO far, SO good, though!  You did an excellent job!  After I got off work yesterday, I really really wanted to get Virtua Fighter coded into Xtreme.  And, that worked out quite nicely, as I can now run it around 55-60 FPS.  Arcadez2003 gave a little creative input into some of the timing to help with the finality of it all!  

I am also gonna try to get the other bootstrap additions into Xtreme over the next day or two.  But, so happy you have taken an interest in these!  I really need to do the calibration for Race Drivin and Hard Drivin'.  I played Race Drivin' Arcade on PS2 Emulator in my currently uploading video, and it is damned fine and fun to play (albeit, you can notice the typical lower skewered volume artifacts when it plays the main theme that sounds like Holiday Road from Vacation!  

I will be sure to video showcase the bootstraps, too!

What would really be amazing is being able to work in the OTHER Model 1 game, Virtua Racing in.  It seems to have been fixed up for lr-mame2003.  But, otherwise, its coding wasn't really optimal for playability til MAME .115!  In any case, this is the video I posted.  The last few minutes are Race Drivin'!  And, fairly near 9:11 point (3rd test) is me running the Virtua Fighter on MAME 2003 Xtreme with 3 testing compile perimeters (other two tests are directly before the 9:11 mark).  I got 15 FPS, 45 FPS, and finally 55+!  Thanks again, and will communicate with you later today and tomorrow!

https://www.youtube.com/watch?v=vjWXTx5p9r0

**Comment by mahoneyt944** [comment]
@KMFDManic 

For revx , I just need to figure out the sound setting. I was able to set it in the bootstrap but the driver doesn't actually use the setting until one of the volume buttons is touched. I have a few ideas how to quick bypass this but ideally the driver needs to check this setting before turning the sound on.

**Comment by KMFDManic** [comment]
@mahoneyt944 possibly check the MAME 2003 Plus Dat in Metadata, which seems to control dip switch variances.  I can try compile tests in the AM, too.

**Comment by KMFDManic** [comment]
@dinkc64 Hey, mate! Any input on forcing sound to be higher for games such as Revolution X.  Figure your extensive guru knowledge may be helpful here!

**Comment by mahoneyt944** [comment]
@KMFDManic
 It gets a little confusing so I'll try to simplify what's happening. You have the game's internal volume level, which is the actual volume level used. Then you have the volume setting stored in the service menu. This is the level preconfigured in the bootstrap. When the game boots it defaults to using the internal volume level and ignores where the service menu level is saved at. 

The internal volume level is maybe 40% of the max volume. In the bootstrap I saved the service menu volume level at 100%. When you boot the game the volume will always be at 40%. If you check the service menu you'll see the level is set at 100% yet it still playing at 40%. As soon as you press either volume button the internal level gets synced to the service menu level.

**Comment by mahoneyt944** [comment]
This looks promising. I'll play around with it later.
src/machine/midwunit_machine.c

**Comment by KMFDManic** [comment]
@mahoneyt944 I had remembered markwkidd has already played around with higher volumes for games, such as MK2, etc.  

https://github.com/libretro/mame2003-plus-libretro/issues/128

https://github.com/libretro/mame2003-plus-libretro/commit/3428c8915147a24ad4e844e895c098541967ace3

Then, he lowered volume in MK2, due to reports of clipping.  We can, of course, test, to see what works best for Rev X!

https://github.com/libretro/mame2003-plus-libretro/commit/c8834809edd094cb50c10be5791ae974fb81ee66

And, hopefully, he can lend some insight into this, as well.  But, should be a great fix up addition, regardless!

**Comment by mahoneyt944** [comment]
The new bootstrap already has the volume setting fixed I just need to get the driver to use it.

**Comment by KMFDManic** [comment]
Yeah, I noticed that, too.  Hopefully, @markwkidd can lend some insight as to a good way to enforce it?

**Comment by mahoneyt944** [comment]
@KMFDManic it looks like this functionality would be added here `src/machine/midwunit_machine.c` as this controls the sound initiation. Or perhaps in the dcs driver itself. Basically need to see how things behave when you press a volume button in the service menu and see if we can copy a piece of the code to initialize out new setting.

**Comment by KMFDManic** [comment]
@mahoneyt944 I wonder if this is specific to this particular game or also affects other machines.  It can be a learning experience, for sure, if it helps benefit other games.  Many of the Atari-Midway Games tend to have lower volume.  And, even in my PS2 playing of Race Drivin', the volume was low and screwy.  They must have left the sound alone, and mainly worried about calibration.

**Comment by mahoneyt944** [comment]
Well at least in mame2003-plus revx is on its own driver. So a fix will probably just be for this game.

**Comment by mahoneyt944** [comment]
@KMFDManic  volume Fixed #867

**Comment by KMFDManic** [comment]
@mahoneyt944 Right on the money!  Looks truly excellent, and so glad you pulled it off!  I can see from the commits, alone, that it was a bit of a headache to contend with.  Thanks again!  And, hopefully, you get a few minutes to enjoy these games!

**Comment by mahoneyt944** [comment]
@KMFDManic
 If you do a video on term2 / revx, post a link up. Carnevil should be very easy to bootstrap. I should be able to get that hooked up. Godzilla and Legionnaire are probably doable but I haven't looked into it. Bootstrapping driving games isn't an issue either but I don't really play them personally because my arcade cabinet is very limited on buttons. So those are lower on my list.

**Comment by KMFDManic** [comment]
@mahoneyt944 I will most definitely be throwing up a video about those two games.  Anything Midway related is always good to showcase fixes for, as well.  I'll link the video once I post.  Thanks again!

**Comment by arcadez2003** [comment]
> 
> 
> @KMFDManic
> If you do a video on term2 / revx, post a link up. Carnevil should be very easy to bootstrap. I should be able to get that hooked up. Godzilla and Legionnaire are probably doable but I haven't looked into it. Bootstrapping driving games isn't an issue either but I don't really play them personally because my arcade cabinet is very limited on buttons. So those are lower on my list.

Godzilla and Legionnaire dont work in this core so no point creating a bootstrap for those ones.

**Comment by mahoneyt944** [comment]
@arcadez2003  yeah, @KMFDManic was seeing if they could be fixed. 

Quoted: 
"Godzilla has graphical glitches, which are fixed up in FBNEO (backporting the fixes doable, or not?)
Legionnaire, (fixed in MAME 2010 and on), can't even see characters and truly play in Plus/Xtreme...backportable, I wonder)"

I'm probably going to bootstrap carnevil, and I want to check on rampage world tour to see if it needs it. Or if it even works. Haven't tried yet.

**Comment by arcadez2003** [comment]
The only game using the Seibu Cop protection i was able to get playable was Denjin Makai as it hardly uses it, other games
like Heated Barrel, Legionnaire, Raiden II and Zero Team use it to encrypt the inputs, sound and video code plus many aspects
of game logic and the hitboxes.

So much of the code dealing with all of the above is not compatible with this core without a total rewrite and im not shy to
say that is above my level.

**Comment by mahoneyt944** [comment]
There was some audio clipping in revx so I bumped the volume down a click. Seems better.

**Comment by KMFDManic** [comment]
@mahoneyt944 I will throw up a video tomorrow.  Friggin fantastic with the fixes in place.  I will do 3 Player Mode Activate, and possibly do a full run of the game.  I tested with the clipping audio, as well as without.  Worked great.  

@markwkidd Since we did bootstrapping a little differently in our original implementation, how do you feel I should proceed as far as adding any additional bootstraps to Xtreme?  In Plus, you are currently using combination of bootstrap.c, bootstrap.h, etc, whereas, the bootstrap we added for Run n' Gun we did directly within the rungun.c driver.  I am absolutely fine with maintaining this method, if it can parlay without conflict into Terminator 2 and Revolution X.  

I appreciate any input before I make any drastic changes to the Xtreme Code Set!  But, I will be sure to showcase both of these games tomorrow, and get a fun and enjoyable approach to them!

**Comment by mahoneyt944** [comment]
@KMFDManic I just did this conversation in mane2003. See these 3 for how to:
https://github.com/libretro/mame2003-libretro/pull/456
https://github.com/libretro/mame2003-libretro/pull/457
https://github.com/libretro/mame2003-libretro/pull/459

**Comment by KMFDManic** [comment]
@mahoneyt944 Kickass:)  I should have taken a look at the recent history since I didn't recall Standard using that setup before.  In any case, thanks so much for the food for thought.  I will have the Revolution X demonstration up tomorrow.  I will link you to it once posted.

**Comment by KMFDManic** [comment]
@mahoneyt944 Could be an interesting showcase, the Food Fight hack!  I will try to work a video demonstration in, regarding that.

**Comment by mahoneyt944** [comment]
> @mahoneyt944 Could be an interesting showcase, the Food Fight hack! I will try to work a video demonstration in, regarding that.

Yeah it's pretty cool and very few know about it. I created it because the Atari console version plays similar to this hack. In the arcade version, you would have been able to aim more actually so this hack makes the game enjoyable again in emulation.

**Comment by KMFDManic** [comment]
@mahoneyt944 Like with the Tron Deadly Disks game on Intellivision.  The initial implementation for that Core had you pulling up a virtual key pad, to tap the numbers...numbers which controlled your multi directions shooting!  That definitely doesn't work for a fast paced game like that!  So, it was nice to have it adapted so the numbers could easily be selected with JUST the right analog:)  True Twin Stick going on there!  

Food Fight will be fun to check out.  Even stuff like Ikari Warriors can be quite irritating with its oddball tank rotary controls.  That was one thing I wanted fixed up in my last posted MAME 2003 Xtreme Release, which Grant2258 graciously helped out with.  Joystick Hacks are great, too.  And, I need to add more of those, to have options.

I have fondness from way way way back, playing Food Fight.  It will be fun to revisit it, improper and way fixed up, courtesy of you:)

**Comment by mahoneyt944** [comment]
@KMFDManic nice. Yeah, make sure you read the "how to" link above to understand the adjustments.
