### ISSUE TITLE
Lucky & wild graphical glitches

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#882]
I just fixed the controls and bootstrapped the calibration for this game. It's now playable, however there are some graphical glitches when you enter underpasses / tunnels. This has been fixed in later mames. Need to look into backporting a fix if possible. I believe this may help the other games with imperfect graphic in that same driver but haven't looked into anything.

**Comment by arcadez2003** [comment]
The fix for Lucky And Wild is part of a wider graphical overhaul for the namco games which used a roz layer.........

0.88u2: Phil Stroffolino fixed a few things which missed the Namco update in 0.88u1.
0.88u1: Phil Stroffolino fixed imperfect graphics in Lucky & Wild.
0.88u1: Phil Stroffolino added POSIRQ support for Namco System 2. The games no longer requires game-specific hacks. Added Screen blanking (window) support and Sprite-tilemap orthogonality rendering.
0.87u3: Phil Stroffolino fixed the advanced ROZ chip used by some Namco System 2 games and the ROZ system used in older System2 games (Dragon Blade). The ROZ fixes unfortunately use a handful of custom code, to work around limitations of tilemap.c's roz support. Added abstraction for the tilemap system used in many Namco titles. Merged memory maps.

There are a fair few files which will need updated be prepared for some heavy graft :)

**Comment by mahoneyt944** [comment]
I think it would be worth it if it's not too painful. Since this would improve a few namco games.

**Comment by arcadez2003** [comment]
> 
> 
> I think it would be worth it if it's not too painful. Since this would improve a few namco games.

0.79u1: Big Namco NB1 update [Phil Stroffolino]: Hardware shadow support (used heavily in Greatest Slugger), dedicated random number generator chip, sprite stretch glitch (affects Outfoxies intro), tilemap tile banking feature (used by Mach Breakers), removed several game-specific hacks; now uses dedicated CPU registers for interrupts, preliminary support for screen blanking (hides garbage in Outfoxies), proper POSIRQ handling, for scanline effects. Fixes the water effects in Outfoxies. This same feature needs to be folded into System 2 emulation, but I haven't gotten around to it yet and various Mach Breaker-specific hacks for interpretting the ROZ layer registers; these aren't yet fully understood. In particular, the 'Monster Pull' stage is missing a '3d floor'. Changed 68EC020 CPU1 clock speed to 24.192 MHz and VSync to 59.700001 Hz.


You'll likely need this as well as the later code changes may well sit on top of the previous update, as for if it's a pain or
not i guess that's upto to how you feel around taking on a job as big as this one, the video and machine code changes
should drop in with minimal reworking required but ya never know what might crop up codewise which wont be
compatible with MAME78.

The drivers will be where the real graft is as for starters the mem maps have been merged and will require to be
split off into the old read and write style this core can only support, there might be more memory and CPU related
code which will need rolled back your compiler should help to pick those out.

Big Namco Roz update..........

drivers

namcof1.c
namconb1.c
namcos2.c
namcoic.c

includes

namcoic.h
namonb1.h
namcos2.h

machine

namcoic.c
namcos2.c

video

namcof1.c
namconb1.c
namcos2.c
