### ISSUE TITLE
Sega system32.c Big Endian issues

### ISSUE THREAD

**Issue by crystalct** [libretro/mame2003-plus-libretro#893]
svf, spidey, sonic, radm, jpark, holo, ga2, f1lap, f1en, darkedge, brival and alien3 black screen after this:

![image](https://user-images.githubusercontent.com/1675181/94653960-a8af3180-02fc-11eb-95b8-09495930656f.png)

svf, spidey, radm, jpark, holo, ga2, f1lap, f1en, brival and alien3 work on x86 cpu machines.
darkedge doesn't work (unplaybale), it was fixed with mame 0.100u4
sonic doesn't work (unplaybale), it was fixed with mame 0.101u5 and 0.104u7

**Comment by arcadez2003** [comment]
The fixes for Dark Edge and Sonic would require an update to the video code and new protection decryption, that is not a
problem in of it's self, it's the incompatible input code in the newer segas32 driver which is the sticking point, 

However there is a chance i might be able to get Dark Edge up and running as it uses the same v-blank prot as F1 Superlap
and i managed to hack some code into our system32 driver as a workaround so that racing game would work in MAME2003+.

It'll all depend if the video colour mixing in our older system32 video code will be correct for the game it wasn't for Slip Stream
when i tried to get that game up and running in MAME2003+ a couple of years back but F1 Lap and Air Rescue were fine
it'll be touch and go basically.

Anyway i'll look at Dark Edge later as for Sonic the prototype version romane sonicp.zip should actually work in this core

Regards.

**Comment by arcadez2003** [comment]
No joy with DarkEdge by adding the protection the game now works however as i suspected the video mixing layers
in the older system32 video code is plain wrong for this game you win some lose some.........

![darkedge](https://user-images.githubusercontent.com/51386955/94933224-06d94180-04c2-11eb-9d0d-146e89611fa5.png)

**Comment by wn2000** [comment]
Someone mentioned that for "sonicp" (prototype) you cannot actually finish the game. It'll kick you out at stage 5. So it'll still be desirable to make "sonic" (Japan ver. C) work.

**Comment by arcadez2003** [comment]
@wn2000  "sonic" (Japan ver. C) would be easy enough to fix you just add the prot code from a later MAME build
but it would still crash on stage five due to a palette rendering issue....

0.79u1: Roger Sanders emulated the protection in Segasonic (Japan rev. C) - still crashes due to video emulation bug.

Long story short we need the fix below but that was done after a huge rewrite to the sega32 video code circa MAME97
basically we still have the older sega32 video code from before the big rewrite, so effectively we dont have the indirect
palette supported and since that was where the fix for sonic was done i cant backport it here as the code simply does
not exist in our sega32 video know what i mean.??

0.104u7: Fixed indirect palettes in the System 32 driver [Anonymous]. This fixes SegaSonic The Hedgehog graphics finally.

We're snookered here more or less we cant backport the fix for sonic nor can we just simply update the sega32 driver
and video code to fix sonic and loads more besides due this core being incompatible with much of the code the newer
Sega32 source files use.

**Comment by wn2000** [comment]
Thanks for the update @arcadez2003 I see what you mean.
Off topic but is there a libretro core that is between mame2003 (0.78) and mame2010 (0.139)? Sounds like it should have been fixed in mame2010 but that core is a bit lagging on my low end RK3328 board (sound glitches).

**Comment by arcadez2003** [comment]
@wn2000 there are some AdvanceMAME ports you may wanna check out if any of them are the correct build
so sonic will be 100% playable, anything after 0.104u7 should do the trick, but keep in mind the Sega system 32
games will perform far worse after the video rewite as although it fixed alotta grahical problems the games
themselves took a major performance hit in the process.

**Comment by wn2000** [comment]
Thanks. Yes I saw someone in the rpi community mentioning the use of AdvanceMAME to get pass stage 5. Will check it out.

**Comment by KMFDManic** [comment]
@wn2000 When you say Sonic the Hedgehog is unplayable, you mean as in loads, but no good working controls?

**Comment by arcadez2003** [comment]
> 
> 
> @wn2000 When you say Sonic the Hedgehog is unplayable, you mean as in loads, but no good working controls?

He means it will lock up on level 4 or 5, it's a palette issue which i cant fix in this core, but yeah it's not the easiest 
of games to control.

**Comment by mahoneyt944** [comment]
Moving issue to #1587
