### ISSUE TITLE
Hacha Mecha Fighter (Location Test Prototype, 19th Sep. 1991)

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#909]
Looks like it's beyond my expertise but in theory it could be added to the nmk16 driver, authentic version of a game we already had a bootleg for in the core, added in MAME 204

http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=hachamfp

**Comment by arcadez2003** [comment]
We support two versions of this game already, one is broken due to protection problems which still happen
even in the current mame builds, however the unprotected set is not a bootleg per say and it works 100%

So i see no need to add support for another version which would be hampered due to the aforementioned protection
issues anyway.

**Comment by arnoldsecret** [comment]
Just to add, the prototype doesn't seem to be using any sort of protection, but then again we already have a working version, closing now.
