### ISSUE TITLE
3DS Port Crashes when Changing Games

### ISSUE THREAD

**Issue by MarioKartFan** [libretro/mame2003-plus-libretro#912]
This core runs many games extremely well on the 3DS.  But it currently crashes whenever I attempt to change the current game to a new game. The only option that I have found is to completely exit Retroarch and then restart Retroarch and choose the new game.

**Comment by mahoneyt944** [comment]
Is this a new issue after updating or an on going issue? This maybe an issue with retroarch and not the core itself.

**Comment by mahoneyt944** [comment]
Just looking through retroarch I found this. It looks like an issue with 3ds with retroarch. Since it's happening with other cores as well. 
https://github.com/libretro/RetroArch/issues/10583

**Comment by mahoneyt944** [comment]
@MarioKartFan what version of mame2003-plus are you on?

**Comment by MarioKartFan** [comment]
I was using the latest nightly when I posted. Solution for me is to select “Reset Retroarch” before changing any game.

**Comment by mahoneyt944** [comment]
Ok, this issue seems to be with retroarch and your specific platform since other cores experience the same issue on 3ds. I would recommend posting in the issue I linked above if you want to seek further into it. Not much we can do here. But feel free to post again if something new is discovered. I'll close this for now.
