### ISSUE TITLE
Default input mayhem.

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#975]
The default inputs in the core are a bit messy. Here's some of my thoughts / concerns / observations.

- analog / digital core option that automatically overrides the default when toggled in core options. This is less than desirable.
- the default "UI select" button defaults to X instead of A like it should be.
- our default classic layout alters the A, B, X, Y orientation from how it's setup in 2003. This also contributes to the "UI select" button being set wrong. (Update below)
- we default a 3rd mouse click but I don't believe we support a 3rd click officially. These are also not mapped to button 1 and 2 by default.
- our pedal defaults seem awkward.
- it would be nice to include analog controls in the "RA quick menu" controls officially.
- how useful are the alternate layouts? The typical user base using retropie would config each controller in emulationstation which would set the layout for them. This probably eliminates some of these layout issues for most. For Android builds I find the on screen controller options to be good out of the box without layout changes. This also relates to ipac users who have the option to setup their ipac as retropad or keyboard inputs, these are completely customizable.

For reference mame2003 default layout, focusing on A, B, X, Y
```
#define EMIT_RETRO_PAD(INDEX) \
    {"RetroPad" #INDEX " Left", ((INDEX - 1) * 18) + RETRO_DEVICE_ID_JOYPAD_LEFT, JOYCODE_##INDEX##_LEFT}, \
    {"RetroPad" #INDEX " Right", ((INDEX - 1) * 18) + RETRO_DEVICE_ID_JOYPAD_RIGHT, JOYCODE_##INDEX##_RIGHT}, \
    {"RetroPad" #INDEX " Up", ((INDEX - 1) * 18) + RETRO_DEVICE_ID_JOYPAD_UP, JOYCODE_##INDEX##_UP}, \
    {"RetroPad" #INDEX " Down", ((INDEX - 1) * 18) + RETRO_DEVICE_ID_JOYPAD_DOWN, JOYCODE_##INDEX##_DOWN}, \
    {"RetroPad" #INDEX " B", ((INDEX - 1) * 18) + RETRO_DEVICE_ID_JOYPAD_B, JOYCODE_##INDEX##_BUTTON1}, \
    {"RetroPad" #INDEX " Y", ((INDEX - 1) * 18) + RETRO_DEVICE_ID_JOYPAD_Y, JOYCODE_##INDEX##_BUTTON2}, \
    {"RetroPad" #INDEX " X", ((INDEX - 1) * 18) + RETRO_DEVICE_ID_JOYPAD_X, JOYCODE_##INDEX##_BUTTON3}, \
    {"RetroPad" #INDEX " A", ((INDEX - 1) * 18) + RETRO_DEVICE_ID_JOYPAD_A, JOYCODE_##INDEX##_BUTTON4}, \
    {"RetroPad" #INDEX " L", ((INDEX - 1) * 18) + RETRO_DEVICE_ID_JOYPAD_L, JOYCODE_##INDEX##_BUTTON5}, \
    {"RetroPad" #INDEX " R", ((INDEX - 1) * 18) + RETRO_DEVICE_ID_JOYPAD_R, JOYCODE_##INDEX##_BUTTON6}, \
    {"RetroPad" #INDEX " L2", ((INDEX - 1) * 18) + RETRO_DEVICE_ID_JOYPAD_L2, JOYCODE_##INDEX##_BUTTON7}, \
    {"RetroPad" #INDEX " R2", ((INDEX - 1) * 18) + RETRO_DEVICE_ID_JOYPAD_R2, JOYCODE_##INDEX##_BUTTON8}, \
    {"RetroPad" #INDEX " L3", ((INDEX - 1) * 18) + RETRO_DEVICE_ID_JOYPAD_L3, JOYCODE_##INDEX##_BUTTON9}, \
    {"RetroPad" #INDEX " R3", ((INDEX - 1) * 18) + RETRO_DEVICE_ID_JOYPAD_R3, JOYCODE_##INDEX##_BUTTON10}, \
    {"RetroPad" #INDEX " Start", ((INDEX - 1) * 18) + RETRO_DEVICE_ID_JOYPAD_START, JOYCODE_##INDEX##_START}, \
    {"RetroPad" #INDEX " Select", ((INDEX - 1) * 18) + RETRO_DEVICE_ID_JOYPAD_SELECT, JOYCODE_##INDEX##_SELECT}, \
    {"RetroMouse" #INDEX " Left Click", ((INDEX - 1) * 18) + 16, JOYCODE_MOUSE_##INDEX##_BUTTON1}, \
    {"RetroMouse" #INDEX " Right Click", ((INDEX - 1) * 18) + 17, JOYCODE_MOUSE_##INDEX##_BUTTON2}
```

Mame2003-plus our default is the classic layout
```
#define EMIT_RETROPAD_CLASSIC(DISPLAY_IDX) \
  {"RP"   #DISPLAY_IDX " HAT Left ",    ((DISPLAY_IDX - 1) * number_of_controls) + RETRO_DEVICE_ID_JOYPAD_LEFT +3000,   JOYCODE_##DISPLAY_IDX##_LEFT}, \
  {"RP"   #DISPLAY_IDX " HAT Right",    ((DISPLAY_IDX - 1) * number_of_controls) + RETRO_DEVICE_ID_JOYPAD_RIGHT +3000,  JOYCODE_##DISPLAY_IDX##_RIGHT}, \
  {"RP"   #DISPLAY_IDX " HAT Up   ",    ((DISPLAY_IDX - 1) * number_of_controls) + RETRO_DEVICE_ID_JOYPAD_UP +3000,     JOYCODE_##DISPLAY_IDX##_UP}, \
  {"RP"   #DISPLAY_IDX " HAT Down ",    ((DISPLAY_IDX - 1) * number_of_controls) + RETRO_DEVICE_ID_JOYPAD_DOWN +3000,   JOYCODE_##DISPLAY_IDX##_DOWN}, \
  {"RP"   #DISPLAY_IDX " B",            ((DISPLAY_IDX - 1) * number_of_controls) + RETRO_DEVICE_ID_JOYPAD_B +1000,      JOYCODE_##DISPLAY_IDX##_BUTTON1}, \
  {"RP"   #DISPLAY_IDX " A",            ((DISPLAY_IDX - 1) * number_of_controls) + RETRO_DEVICE_ID_JOYPAD_A +1000,      JOYCODE_##DISPLAY_IDX##_BUTTON2}, \
  {"RP"   #DISPLAY_IDX " Y",            ((DISPLAY_IDX - 1) * number_of_controls) + RETRO_DEVICE_ID_JOYPAD_Y +1000,      JOYCODE_##DISPLAY_IDX##_BUTTON3}, \
  {"RP"   #DISPLAY_IDX " X",            ((DISPLAY_IDX - 1) * number_of_controls) + RETRO_DEVICE_ID_JOYPAD_X +1000,      JOYCODE_##DISPLAY_IDX##_BUTTON4}, \
  {"RP"   #DISPLAY_IDX " L",            ((DISPLAY_IDX - 1) * number_of_controls) + RETRO_DEVICE_ID_JOYPAD_L +1000,      JOYCODE_##DISPLAY_IDX##_BUTTON5}, \
  {"RP"   #DISPLAY_IDX " R",            ((DISPLAY_IDX - 1) * number_of_controls) + RETRO_DEVICE_ID_JOYPAD_R +1000,      JOYCODE_##DISPLAY_IDX##_BUTTON6}, \
  {"RP"   #DISPLAY_IDX " L2",           ((DISPLAY_IDX - 1) * number_of_controls) + RETRO_DEVICE_ID_JOYPAD_L2 +1000,     JOYCODE_##DISPLAY_IDX##_BUTTON7}, \
  {"RP"   #DISPLAY_IDX " R2",           ((DISPLAY_IDX - 1) * number_of_controls) + RETRO_DEVICE_ID_JOYPAD_R2 +1000,     JOYCODE_##DISPLAY_IDX##_BUTTON8}, \
  {"RP"   #DISPLAY_IDX " L3",           ((DISPLAY_IDX - 1) * number_of_controls) + RETRO_DEVICE_ID_JOYPAD_L3 +1000,     JOYCODE_##DISPLAY_IDX##_BUTTON9}, \
  {"RP"   #DISPLAY_IDX " R3",           ((DISPLAY_IDX - 1) * number_of_controls) + RETRO_DEVICE_ID_JOYPAD_R3 +1000,     JOYCODE_##DISPLAY_IDX##_BUTTON10}, \
  {"RP"   #DISPLAY_IDX " Start",        ((DISPLAY_IDX - 1) * number_of_controls) + RETRO_DEVICE_ID_JOYPAD_START +1000,  JOYCODE_##DISPLAY_IDX##_START}, \
  {"RP"   #DISPLAY_IDX " Select",       ((DISPLAY_IDX - 1) * number_of_controls) + RETRO_DEVICE_ID_JOYPAD_SELECT +1000, JOYCODE_##DISPLAY_IDX##_SELECT}, \
  {"Mouse" #DISPLAY_IDX " LClick",      ((DISPLAY_IDX - 1) * number_of_controls) + 16 +1000,                            JOYCODE_MOUSE_##DISPLAY_IDX##_BUTTON1}, \
  {"Mouse" #DISPLAY_IDX " RClick",      ((DISPLAY_IDX - 1) * number_of_controls) + 17 +1000,                            JOYCODE_MOUSE_##DISPLAY_IDX##_BUTTON2}, \
  {"RP"   #DISPLAY_IDX " AXIS 0 X-",    ((DISPLAY_IDX - 1) * number_of_controls) + 18 +2000,                            JOYCODE_##DISPLAY_IDX##_LEFT_LEFT}, \
  {"RP"   #DISPLAY_IDX " AXIS 0 X+",    ((DISPLAY_IDX - 1) * number_of_controls) + 19 +2000,                            JOYCODE_##DISPLAY_IDX##_LEFT_RIGHT}, \
  {"RP"   #DISPLAY_IDX " AXIS 1 Y-",    ((DISPLAY_IDX - 1) * number_of_controls) + 20 +2000,                            JOYCODE_##DISPLAY_IDX##_LEFT_UP}, \
  {"RP"   #DISPLAY_IDX " AXIS 1 Y+",    ((DISPLAY_IDX - 1) * number_of_controls) + 21 +2000,                            JOYCODE_##DISPLAY_IDX##_LEFT_DOWN}, \
  {"RP"   #DISPLAY_IDX " AXIS 2 X-",    ((DISPLAY_IDX - 1) * number_of_controls) + 22 +2000,                            JOYCODE_##DISPLAY_IDX##_RIGHT_LEFT}, \
  {"RP"   #DISPLAY_IDX " AXIS 2 X+",    ((DISPLAY_IDX - 1) * number_of_controls) + 23 +2000,                            JOYCODE_##DISPLAY_IDX##_RIGHT_RIGHT}, \
  {"RP"   #DISPLAY_IDX " AXIS 3 Y-",    ((DISPLAY_IDX - 1) * number_of_controls) + 24 +2000,                            JOYCODE_##DISPLAY_IDX##_RIGHT_UP}, \
  {"RP"   #DISPLAY_IDX " AXIS 3 Y+",    ((DISPLAY_IDX - 1) * number_of_controls) + 25 +2000,                            JOYCODE_##DISPLAY_IDX##_RIGHT_DOWN},
```

I started a wip branch https://github.com/libretro/mame2003-plus-libretro/compare/input to address some of these. So far I have only focused on removing the analog / digital core option selection by mapping both of these by default in a single default map. This seems to be most logical and removes a lot of confusion out of the gate. 

One thing I would like to look into is how this single map effects netplay. I know analog was not fully setup in this core. My initial thought is if we map ("keyboard up" or "dpad up" or "analog up") to each directional input...would netplay still work properly?

Hopefully we can collaborate on some of this. I don't want to make judgements on this without having support from the other contributors. I know this has been a topic of frustration for many developers and end users. So hopefully we can iron some things out.

Thank you.

**Comment by markwkidd** [comment]
I've had the exact same question about netplay. Rather than think it
through, could we get a couple users together on discord and try it out?
Maybe verbose logging has enough info to figure this out without actually
doing it.


I've had my sights on implementing the libretro lightgun API as a way to
make a new contribution after my long break. I'll keep an eye on this issue
if I do so I can keep appraised of your branch.

**Comment by mahoneyt944** [comment]
@markwkidd a follow up to the A, B, X, Y orientation. I'm guessing our classic layout is geared to be compatible with a snes / nes controller. Which makes sense that if you only had A and B on nes that the default would use those. Snes has A, B, X, Y so it's not as much of a concern but I suppose this makes sense as well.

Since snes is probably the most basic classic controller I'd recommend using with mame. I'm thinking the gas / brake pedals should be mapped to the L and R bumper buttons. All playstation and xbox layouts have L and R bumpers as well so I think this makes sense. If your controller does not have these button it's probably not very compatible with the diverse buttons mame requires without remapping / compromise.

**Comment by mahoneyt944** [comment]
@markwkidd you'd probably be the guy to answer such question.... I've noticed with the layout changes we are directly altering our UI select and cancel buttons too. I don't think we want to change these from A and B no matter the layout.

Is it possible to hard map these to A and B so that they don't follow the layout when swapped? I'm not sure of an easy way to do this while still allowing the user to remap them.

**Comment by mahoneyt944** [comment]
Netplay doesn't seem to like this mapping. Having never used netplay, I could be doing something wrong. I think we just need to add official support for analog and everything will just work.

**Comment by markwkidd** [comment]
I have to admit I've never used netplay with any core other than briefly
for testing, so I'm not sure either.

The original port of this core predates some parts of the libretro input
API, plus maybe they just left some things for future coders to finish 😃
There used to be other core options for input that have been eliminated as
the API and core get better in sync, if I remember correctly

Anyway, I think more fully implementing the libretro side of things for
input can only be a good thing.

**Comment by Wilstorm** [comment]
>we default a 3rd mouse click but I don't believe we support a 3rd click officially. These are also not mapped to button 1 and 2 by default.

@mahoneyt944 - I know back in the day the 3rd button came in awful handy when running on Windows. I know RetroPie is able to run on Windows but if it's not mapped to anything in the core I suppose it doesn't make much sense unless it's easy to hook up. 

The dual maps between the RA keys and raw input from the keyboard on the TAB menu can get fairly confusing quickly. I spent hours tweaking to figure out what it's doing. I tried to dual map all games to both keyboard and the "Retroarch abstract controller" and it can _not_ be done without doing some sever compromises of the button layouts in certain games (i.e. basically making them no fun to play). 

For example in pinball games the L/R shoulders on controllers work great for flippers but they won't translate to the same L/R on a 6 button control panel layout which would be more like L2/R2 on the sides.  Wrapping your head around the idea the abstract layer is a "position" on a controller and not an actual button is a hard concept to grasp at first. The controllers have all been well defined by the Libretro folks and are known but control panel layouts (arcade machines) can be laid out any way you want.

On a side note. The one thing that I would love to see working is the XBOX 360 "Home" button (or silver button in the center). That is such a handy button for creating RA hotkeys, etc. It's such a waste to not map it when you have so few on a controller.

**Comment by mahoneyt944** [comment]
@markwkidd

On my input branch I've added to the describe inputs function count by using our "number_of_controls" def. I just need to add the case descriptions to return for mouse and analog but not sure how this should be done exactly. Any tips on this piece of the code?

https://github.com/libretro/mame2003-plus-libretro/blob/e9988a48f466caa24f665312041b9e0ca3f01d31/src/mame2003/mame2003.c#L1619-L1797

**Comment by Wilstorm** [comment]
@mahoneyt944 - Nice, that would be great. I wouldn't mind starting all my mappings over if only to simplify them a bit. The current mappings are incredibly complex I always thought. 

One thing I finally did was remove the "raw" keyboard inputs from the TAB menu. Unless you turn on "focus mode" they (RA inputs and hotkeys) can interfere with each other. 

I mainly use the core with RetroPie and they aren't really needed due to the abstraction layer handing the mappings but I think you have a much better understanding of what repercussions would be. I tried to come up with a scenario to keep raw mappings. I can't really think of one but maybe  other platforms and/or frontends it is beneficial. For standalone MAME raw inputs from the keyboard & mouse make perfect sense as a starting point.

**Comment by mahoneyt944** [comment]
Yeah keyboard input seems like carry over from official mame, but they may be used by some people. There's lots of pc gamers who prefer keyboard over gamepads. Personally I don't use keyboard but I guess it should be supported.

**Comment by Wilstorm** [comment]
@mahoneyt944 - Well the IPAC does fall into the keyboard family. A lot of folks use an IPAC only for their control panels. The core makes no distinction between a/b from an IPAC vs. a keyboard so it's probably good. I was more referring to the inputs and not necessarily the device they come from, removing keyboard device support would be catastrophic.

Basically what I have is two setups. One with RA mappings and specific game overrides for a controller. The other is RA mappings and specific game overrides for a keyboard or more specifically an IPAC in an arcade cab setup.

I guess I was questioning if the raw inputs are needed in the TAB menu in a Libretro core when using RA. Even if you run a Libretro core on a PC you shouldn't need the raw input but then again I don't know all the platforms people use OR maybe direct input is needed for certain frontends. It seems raw input has no use in a Libretro core.

For example if I map RetroPad A to "Left Ctrl" and in the core TAB menu if Button 1 = RetroPad A all is well, so do I need direct raw input also for Button 1, as in, Button 1 = "Left Ctrl", basically bypassing RA if that makes sense. 

So I see Button 1 = RetroPad A Left Ctrl. Well RetroPad A is already mapped to Left Ctrl so when in sync it's not a problem. The issue is if the raw input mappings have crossover with the RA input mappings you end up with two actions like jumping and moving left when you press just one button (unless in focus mode). That is one of the confusing aspects of the Libretro MAME cores.

I don't know the answer but it seems to get a nice clean interface either gut the MAME menu and go the way of Libretro (I think FBNeo did this) or deal with the complexities of multiple inputs per button, raw and RA. Cutting out the MAME TAB menu kills all kinds of functionality though. Such a dilemma. 

I understand it but can't explain it in writing very well.

**Comment by mahoneyt944** [comment]
Right now you can disable the keyboard input by changing the input interface in the core options. That might be the compromise for now.

**Comment by Wilstorm** [comment]
@mahoneyt944 - Yeah I'm aware of the options. I've used them all and they have some short comings but they are a nice compromise. I don't think you're understanding what I'm asking. You must not use (or haven't used?) a controller and keyboard to really see the confusion. 

It took me hours of tinkering with a real keyboard and a real controller to figure out what was happening. I've always knew standalone MAME and love it's simplistic elegance and it covers everything nicely. I've come to appreciate Libretro's highly configurable structure but it comes with a steep learning curve. You can override globally, "core family", core and individual game, in addition, to throwing the frontend into the mix. Sometimes it's difficult to troubleshoot where the issue is located. Standalone MAME has a one stop to troubleshoot, the TAB menu. 

Now when you combine the two together you have a mess to contend with hence the question.

I was just thinking more like Libretro. Gamepad --> Binding --> RetroPad --> Remap --> Core Map vs. Raw --> Core Map.

If there's value in salvaging both or just stick with the Libretro way. I find value in standalone MAME and will always keep it around and use it, especially when using the current version. I keep it up to date on every release.

The Libretro cores on the other hand can do things standalone can't which is multi-core unification with the reference frontend (Retroarch), it all works really nice. This being more of a Libretro core I was just questioning the value of Raw --> Core Map.

I think FBNeo doesn't support the TAB menu (or possibly never did?) and each game is automatic in using digital or analog depending on what game is launched. Now that's a user friendly core, even if you loose some functionality! :)

You can't really abandon layouts completely and map only through the TAB menu because you need the RetroPad --> Core Map bindings. Something has to bind your inputs to the core or the bindings upfront wouldn't make much sense and the core wouldn't function out of the box. In essence you'd be using standalone MAME.

I think one of the issues is having one foot in Libretro and the other foot in trying to maintain some semblance to the standalone counterpart.

Anyhow I know the complexities involved in trying to do what you're doing and trying to find a compromise is tough. I'll let you focus on your thing and look forward to seeing how things turns out. This is my main core for retro gaming and I appreciate all the additions, tweaks and fixes you've been adding to the core, nicely done!

**Comment by mahoneyt944** [comment]
@Wilstorm personally I don't override the default retroarch menu inputs for mame because how complex thid can get. I just open the tab menu set the default (input general) the way I prefer, then on each game I setup (input this game) for any game specific tweaks. This seems to be easiest for me.

For other cores this doesn't seem to be an issue, I setup my inputs in RA once and they are good for every game.

**Comment by mahoneyt944** [comment]
Right now in my branch I'm default mapping 6 players with analog and digital set by default to everything. No more core option to use analog vs digital. Both are set out of the box.

I'm trying to setup some Default.cfg protection so when users upgrade to this new version of 2003-plus their custom default.cfg carries over and isn't overwritten. The core isn't designed this way currently though. I only want to initiate the new default.cfg if one isn't provided. Still working on this.

**Comment by Wilstorm** [comment]
> No more core option to use analog vs digital. Both are set out of the box.

What, no more core option for analog vs digital...YAY!!! ;)

**Comment by mahoneyt944** [comment]
Ok big input update rolling out. Unfortunately at this time the default.cfg will get updated on any lines where the saved default sequence does not match the new default sequence standard. This maybe a bit annoying to users upgrading to the new version of 2003-plus but it's a safeguard built into the default configuration. Removing this safeguard could potentially corrupt it entirely so there's no way around it currently.

I recommend either giving your default.cfg a once over after updating as it will combine the new mapping with your existing mapping or delete it entirely and start fresh to get the full effect of the new input defaults.

**Comment by Wilstorm** [comment]
@mahoneyt944 - Sorry posted in the commit a quick question. At some point here I'm just going to delete all my cfgs and start over to see if I can make a go with it as a good OOBE with all these changes.

**Comment by mahoneyt944** [comment]
Yes the ui button defaults follow the retropad standard. Meaning for a xbox controller A and B are opposite. Try not to map based on your controllers physical labels and follow the retropad standard.

Xbox controller:
Xbox B : retropad button A
Xbox A : retropad button B
Xbox X : retropad button X
Xbox Y : retropad button Y

Like wise for a playstation controller:
Circle : retropad button A
Cross : retropad button B
Triangle : retropad button X
Square : retropad button Y

For our defaults we still follow the classic layout as usual
Button 1 : retropad B
Button 2 : retropad A
Button 3 : retropad Y
Button 4 : retropad X

**Comment by mahoneyt944** [comment]
X and Y are switched too. Sorry been awhile since I looked at a xbox controller, updated my last post.

**Comment by mahoneyt944** [comment]
Our retropad buttons will follow this:
https://retropie.org.uk/docs/Controller-Configuration/

**Comment by Wilstorm** [comment]
@mahoneyt944 - That looks great! I look forward to trying it out. With all the bootstraps you've done and these new defaults. This looks like a major step to a better [great] starting point. I'm going wipe it all and just see how it works with all defaults when I get a chance to spend some time just messing around.
